[TS-346] 별자리 페이지 API 연결, 모션 및 UI 추가
ConnectingStar/ConnectingStar-Front pull request #105
Opened 2024-06-21 08:29 UTC by khkh0109

[TS-346](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?assignee=616ccf7525f31300702d29cb&selectedIssue=TS-346)

## 💡 변경사항 & 이슈
- 별자리 API 연결
- 모션 및 UI 추가
<br>

## ✍️ 관련 설명
### API
- 별자리 API 추가
    - 별자리 정보 가져오기 ([별자리 메인 조회](https://documenter.getpostman.com/view/32872720/2sA35G53Dg#55287d89-26a3-461e-8986-05e6941d30ec))
        - 요청 엔드포인트 변경사항: id 포함하지 않고 조회함
    - 별자리에 별 등록하기 ([진행중인 별자리 별 등록](https://documenter.getpostman.com/view/32872720/2sA35G53Dg#c5ed9383-8491-4a16-9c98-3c92cfc479b6))

### UI
- 별자리 선택하지 않았을때 화면 추가
- 별 배경 고정
    - 별 채우기 버튼 누를때마다 별 위치가 바뀌고 리렌더링돼서 memo를 사용했습니다

### 기능
- 캐릭터 이름 뒤 이/가 조사 추가
    - 캐릭터 이름에 알맞은 조사 붙이는 기능 추가했습니다
    - 별자리 해금 모달에서만 조사가 달라지고, 바뀌는 조사도 이/가 밖에 없어서 직접 구현하는 방향을 택했습니다
    - 이후 추가되는 캐릭터 이름도 한글로 끝난다고 하니 참고 부탁드립니다
- 버튼 비활성화
    - 보유 별이 0이거나 해금 완료했다면 비활성화함
    - 화면상 변화는 없음

### 참고
- circle 배열 key
    - circle 배열 key는 index로 지정했습니다. (원래 cx값이었는데 중복되는 값이 존재함)
    - circle 배열은 조회만 하고 요소 순서 변경은 일어나지 않아서 index로 했는데, 혹시 예상되는 문제가 있다면 말씀 부탁드립니다

<br>

## ⭐️ Review point
- 동작에 문제 없는지
- 더 괜찮은 방법 없는지

확인 부탁드립니다

<br>

## 📷 Demo
### 별자리 선택하지 않았을때 화면
<img width="350" alt="스크린샷 2024-06-21 오후 5 18 08" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/d6adfc56-3ac5-4442-9f7f-4e30da48440f">

<br>

### 전체 동작

https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/66aebd92-a4cb-41b8-8f14-2550a0dfd000

<br>

2024-06-21 10:51 UTC, sikkzz commented
별이 없어서 별자리 완성을 못하는데 이거 테스트 방법이 있을까요?

2024-06-21 15:54 UTC, pizzaYami commented
별자리 획득 모달이 뜨고 폭죽나오는걸로 알고있는데 다른 브랜치에서 적용할 예정인가요?

2024-06-21 16:18 UTC, pizzaYami commented on src/components/StarPage/StarMain/StarBackground.tsx
>  	width: 500px;
rem?

2024-06-24 05:19 UTC, khkh0109 commented
> 별이 없어서 별자리 완성을 못하는데 이거 테스트 방법이 있을까요?

별 추가 요청드렸습니다!

2024-06-24 05:20 UTC, khkh0109 commented
> 별자리 획득 모달이 뜨고 폭죽나오는걸로 알고있는데 다른 브랜치에서 적용할 예정인가요?

넵 다른 브랜치에서 적용 예정입니다 
아직 폭죽의 형태에 관해서 상의된게 없기도 해서 폭죽 제외하고 봐주시면 됩니다!

2024-06-24 05:29 UTC, khkh0109 commented on src/components/StarPage/StarMain/StarBackground.tsx
>  	width: 500px;
이 부분은 글로벌 스타일 max-width와 동일하게 500px로 주었습니다 (rem은 브라우저 설정에 따라 글로벌 스타일에서 설정한 max-width를 벗어나서요..!)
계속 헷갈릴 수 있으니 옆에 주석 달아두겠습니다!

2024-06-26 01:17 UTC, khkh0109 commented
- 테스트용 별 추가했다고 합니다 
- axios 인스턴스 변경했습니다 
@sikkzz @pizzaYami

2024-06-26 10:38 UTC, pizzaYami approved these changes

2024-06-26 11:07 UTC, sikkzz requested changes

2024-06-26 11:07 UTC, sikkzz commented on src/pages/StarMainPage/StarMainPage.tsx
> +	const { addStarResult } = useAppSelector((state) => state.star);
구조분해할당으로 두개 합칠 수 있겠네요

2024-06-26 11:07 UTC, sikkzz commented on src/pages/StarMainPage/StarMainPage.tsx
> +						onClick={handleStarButtonClick}
그냥 인라인에 dispatch(addStar()); 사용해도 될 거 같은데요?

2024-06-27 10:05 UTC, sikkzz approved these changes

2024-06-27 10:51 UTC, merged