[TS-356] 온보딩 리펙토링
ConnectingStar/ConnectingStar-Front pull request #109
Opened 2024-06-26 09:50 UTC by pizzaYami

[TS-356](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109/backlog?assignee=712020%3A2697805c-34c2-4de5-99cb-4aab5f6d607a&selectedIssue=TS-356)

## 💡 변경사항 & 이슈
/onboarding (CreateAccount.tsx 67~69번째 코드 주석 후 확인)
/chatting (ChattingPage 34~39번째 코드 주석 후 확인)

- 온보딩 리펙토링
app.tsx 온보딩 영역 PATH 방식으로 변경
VisitorRoute -> referrer 명칭변경
전체적으로 코드 가독성 좋게 변경
- 채팅파트 모달 닫아도 바텀버튼 유지되도록 수정
- chatting 마지막 모달 추가

<br>

## ✍️ 관련 설명
<br>

## ⭐️ Review point
<br>

## 📷 Demo
<br>

2024-06-28 00:28 UTC, khkh0109 commented on src/constants/chatData.tsx
> +			botMessage: [
이름을 botMessage로 바꾸니까 훨씬 이해가 쉽네요! 👍

2024-06-28 00:28 UTC, khkh0109 commented on src/pages/ChattingPage.tsx
> +					comment={`환영의 의미로 n개의 별을 준비했어요.\n별을 별자리에 넣어보러 갈까요?`}
문구가 'n개의 별~'이라고 되어있는데
별이 몇개인지는 아직 정해지지 않은게 맞을까요?

2024-06-28 00:34 UTC, khkh0109 commented
ChattingPage.tsx 37번 라인 navigate 함수도 다른곳처럼 PATH 상수로 지정한 값을 사용하는게 어떨까요?

2024-06-28 00:39 UTC, khkh0109 commented
회원가입 진행하다 궁금한게 생겨서 여쭤봅니다

아래 영상처럼 성별, 나이대 선택 후 다시 input을 누르면 이전에 선택된 값이 체크된 채로 모달이 켜지는데, 닉네임은 예외인걸까요? 

피그마에는 관련 설명이 안보여서 질문 드립니다! 


https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/1d1fa6d1-ddd0-4714-81ea-04e01722cbca

2024-06-29 02:56 UTC, pizzaYami commented on src/constants/chatData.tsx
> +			botMessage: [
감사합니다ㅋㅋㅋ

2024-06-29 02:57 UTC, pizzaYami commented on src/pages/ChattingPage.tsx
> +					comment={`환영의 의미로 n개의 별을 준비했어요.\n별을 별자리에 넣어보러 갈까요?`}
기획에 한번 물어볼게요

2024-06-29 03:08 UTC, pizzaYami commented
> ChattingPage.tsx 37번 라인 navigate 함수도 다른곳처럼 PATH 상수로 지정한 값을 사용하는게 어떨까요?

다른곳사용중인 PATH상수로 가져와서 사용한다면 코드가 너무 길어지고
navigate(`${PATH.ONBOARDING}?step=${${ONBOARDING_STEP.CREATE_ACCOUNT}}`)

새롭게 만들자니 하나만 상수로 만들기 애매하네요
혹시 다른 방법이 있을까요?

2024-06-29 03:30 UTC, pizzaYami commented
> 회원가입 진행하다 궁금한게 생겨서 여쭤봅니다
> 
> 아래 영상처럼 성별, 나이대 선택 후 다시 input을 누르면 이전에 선택된 값이 체크된 채로 모달이 켜지는데, 닉네임은 예외인걸까요?
> 
> 피그마에는 관련 설명이 안보여서 질문 드립니다!
> 
>  2024-06-28.8.14.53.mov

닉네임도 남도록 변경했습니다!

2024-06-29 03:30 UTC, pizzaYami commented
> ChattingPage.tsx 37번 라인 navigate 함수도 다른곳처럼 PATH 상수로 지정한 값을 사용하는게 어떨까요?

PATH상수로 변경했습니다.

2024-06-29 03:31 UTC, pizzaYami commented on src/pages/ChattingPage.tsx
> +					comment={`환영의 의미로 n개의 별을 준비했어요.\n별을 별자리에 넣어보러 갈까요?`}
7개로 변경했습니다.
꼼꼼한 코드리뷰 감사합니다!!

2024-06-30 09:52 UTC, khkh0109 approved these changes

2024-06-30 23:46 UTC, sikkzz requested changes

2024-06-30 23:46 UTC, sikkzz commented on src/components/Chatting/ChattingMessage/ChattingMessage.style.ts
> +`;
chatWrap div에 스타일이 없다면 사실 div 말고 하위 태그인 ul에 스타일을 다는게 좋을 거 같네요

2024-06-30 23:46 UTC, sikkzz commented on src/components/common/Modal/CommonModal/SelectTagModal/SelectTagModal.tsx
> +			type === "identity" && updateInputValue && updateInputValue("behavior", updatedHabit);
두개 키값 잘못 입력된 거 같네요

2024-06-30 23:46 UTC, sikkzz commented on src/components/common/Modal/CommonModal/SelectTagModal/SelectTagModal.tsx
이거 수정하시면서 지금 습관 생성할 때 태그 선택 시 해당 내용이 표시가 안됩니다 확인 부탁드려요

추가적으로 같이 사용하는 컴포넌트들은 본인 파트 아닌 부분들은 꼭 잘 확인해주세요ㅠ 리뷰하면서 놓칠 수도 있습니다

2024-06-30 23:46 UTC, sikkzz commented on src/components/common/Modal/CommonModal/SelectTagModal/SelectTagModal.tsx
> +								className={selectedTag === tag ? "selected" : ""}
꼭 className으로 해결해야하는 이유가 있을까요?

2024-06-30 23:46 UTC, sikkzz commented on src/pages/ChattingPage.tsx
> +	const isExtraBtn = chatData[progress].bottomButton.length > 1 ? true : false;
const isExtraBtn = chatData[progress].bottomButton.length > 1;

이렇게만 잡으면 boolean 값으로 true false 지정이 가능하지 않나요?

2024-07-02 09:49 UTC, pizzaYami commented on src/components/common/Modal/CommonModal/SelectTagModal/SelectTagModal.tsx
> +			type === "identity" && updateInputValue && updateInputValue("behavior", updatedHabit);
큰일 날 뻔 했네요 ㅋㅋㅋ 감사합니다.

2024-07-02 09:51 UTC, pizzaYami commented on src/components/common/Modal/CommonModal/SelectTagModal/SelectTagModal.tsx
어떤 부분이 표시가 안될까요?

꼼꼼하게 봤어야하는데 ㅠㅠ 죄송합니다

2024-07-02 09:55 UTC, pizzaYami commented on src/components/common/Modal/CommonModal/SelectTagModal/SelectTagModal.tsx
> +								className={selectedTag === tag ? "selected" : ""}
classname을 사용안하면 css={tagStyle(isInputFocus)} 요걸 map안쪽으로 넣어야해서 코드가 더 지저분해질까봐 넣은건데 방법이 있을까요?

2024-07-08 09:08 UTC, sikkzz approved these changes

2024-07-09 10:08 UTC, merged