[TS-360] 해금 모달 별 로티 애니메이션 추가
ConnectingStar/ConnectingStar-Front pull request #110
Opened 2024-06-28 07:44 UTC by khkh0109

[TS-360](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?assignee=616ccf7525f31300702d29cb&selectedIssue=TS-360)

## 💡 변경사항 & 이슈
- 해금 모달 별 로티 애니메이션 추가
- 축하 문구 변경
<br>

## ✍️ 관련 설명
- /star 경로에서 해금 완료 시 등장
  - 참고: 세림님과 화면 공유 하면서 로티 애니메이션 위치를 맞춘거라 피그마 디자인에는 없습니다
- '축하합니다' 문구 뒤에 폭죽 아이콘 추가
  - 참고: 이 부분도 화면 공유 하면서 나온 의견이라 피그마 디자인에는 없습니다
  - 변경전: `축하합니다!` / 변경후: `축하합니다🎉`
<br>

## ⭐️ Review point
- 로티 애니메이션 이름 괜찮은지
- 그 외 이상한 부분 있는지

확인 부탁드립니다
<br>

## 📷 Demo

https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/6425d7f2-d2d3-4bee-892f-4d88b1365a30

<br>

2024-06-29 03:45 UTC, pizzaYami commented
로티 이름이 와닿지는 않네요
starGetEffectAnimation
starGetEffect
어렵네요 ㅋㅋ

2024-06-30 21:24 UTC, pizzaYami approved these changes

2024-06-30 23:52 UTC, sikkzz requested changes

2024-06-30 23:52 UTC, sikkzz commented on src/components/StarPage/Modal/CharacterUnlockModal.tsx
> +import starBurstAnimation from "@/assets/lottie/lottie-star-burst-animation.json";
첫글자 대문자가 낫지 않을까요? assets들은 컴포넌트 취급이라고 생각해야할 거 같아서요

2024-07-02 11:34 UTC, khkh0109 commented
@sikkzz 로티 이름 파스칼 케이스로 수정했습니다!

2024-07-02 11:36 UTC, sikkzz approved these changes

2024-07-02 11:52 UTC, merged