[TS-373] 스플래시 스크린 설정
ConnectingStar/ConnectingStar-Front pull request #124
Opened 2024-07-18 06:35 UTC by khkh0109

[TS-373](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?assignee=616ccf7525f31300702d29cb&selectedIssue=TS-373)

## 💡 변경사항 & 이슈
안드로이드, iOS 스플래시 스크린 추가
<br>

## ✍️ 관련 설명
- iOS는 디바이스 사이즈마다 스플래시 스크린 이미지를 만들고 link로 연결해야 한다고 합니다 ([만드는 곳](https://progressier.com/pwa-icons-and-ios-splash-screen-generator))
- 애플 터치 아이콘은 192 사이즈 이미지도 된다고 해서 180 사이즈 이미지를 추가하지 않고 192 사이즈 이미지를 지정했습니다 ([참고](https://developer.chrome.com/docs/lighthouse/pwa/apple-touch-icon?hl=ko))
- 크롬에서 페이지 번역 팝업이 계속 등장해서 lang을 ko로 변경했습니다
<br>

## ⭐️ Review point
<br>

## 📷 Demo

iOS 화면입니다
<img src="https://github.com/user-attachments/assets/1b844e52-a659-4efa-8d4f-e07532bb11ee" width="360"/>

아이콘 입니다
<img src="https://github.com/user-attachments/assets/459b5645-58e9-450e-83c1-2d1c025b13c1" width="360"/>

<br>

2024-07-19 00:03 UTC, sikkzz commented
혹시 스플래쉬 스크린 이미지 네이밍이 정해져 있는게 아니라면 하나를 정해서 통일하는건 어떻게 생각하세요?

필수적인 사항은 아닙니다만 현재는 이미지 네임이 조금 중구난방인 느낌이 있어서 정리하면 어떤가 싶었습니다

2024-07-19 00:03 UTC, sikkzz requested changes

2024-07-19 00:03 UTC, sikkzz commented on public/assets/splash_screens/4__iPhone_SE__iPod_touch_5th_generation_and_later_portrait.png
혹시 스플래쉬 스크린 이미지 네이밍이 정해져 있는게 아니라면 하나를 정해서 통일하는건 어떻게 생각하세요?

필수적인 사항은 아닙니다만 현재는 이미지 네임이 조금 중구난방인 느낌이 있어서 정리하면 어떤가 싶었습니다

2024-07-19 02:13 UTC, khkh0109 commented on public/assets/splash_screens/4__iPhone_SE__iPod_touch_5th_generation_and_later_portrait.png
전체적으로 변경하면 좋겠다는 말씀 맞을까요? 

만약 맞다면 저도 깔끔하게 통일하는게 좋을 것 같긴 한데 어떤 식으로 해야할지 모르겠네요

현재는 스플래시 스크린 제너레이트 사이트에서 지어준대로 사용했습니다. (아마 [여기](https://developer.apple.com/design/human-interface-guidelines/layout#Specifications) 적힌 기기 이름 그대로 사용한게 아닐까 싶어요)

2024-07-19 02:21 UTC, khkh0109 commented on public/assets/splash_screens/4__iPhone_SE__iPod_touch_5th_generation_and_later_portrait.png
지금 당장 생각나는건 아래 두 가지 방법입니다

1. 중복되는 iPhone 단어를 빼버리고 기종명을 띄어쓰기 없이 작성하는 방법
`iPhone_15ProMax_15Plus_14ProMax_Portrait.png` (아이폰_기종명1_기종명2_방향.png)

2. 기기 사이즈 + 방향 작성하는 방법
`430x932_portrait.png`
-> 깔끔하지만 현재 스플래시 스크린 이미지가 적용된 기기 명을 알기 힘들것 같아요

2024-07-19 02:36 UTC, sikkzz commented on public/assets/splash_screens/4__iPhone_SE__iPod_touch_5th_generation_and_later_portrait.png
portrait가 꼭 붙어야 하는건가요? 그게 아니라면 iphone 단어도 빼고 기종명만 나열하는게 어떤가 싶네요

2024-07-19 02:46 UTC, khkh0109 commented on public/assets/splash_screens/4__iPhone_SE__iPod_touch_5th_generation_and_later_portrait.png
네 그럼 아이패드랑 가로 이미지는 추가될 일이 없을것 같으니 빼고 아래처럼 통일하겠습니다
`15ProMax_15Plus_14ProMax.png`

2024-07-22 06:46 UTC, sikkzz approved these changes

2024-07-22 06:46 UTC, merged