[Ts 2] SignUpPage
ConnectingStar/ConnectingStar-Front pull request #13
Opened 2024-02-07 06:07 UTC by pizzaYami

[JIRA](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109/timeline?selectedIssue=TS-2)

## 💡 변경사항 & 이슈
signup page 레이아웃 제작
oauthsignup page 레이아웃 제작 
<br>

## ✍️ 관련 설명
피그마와 다르게 화면 크기에 따라서 레이아웃이 변경이 되야하는데 어느 것을 기준으로 해야할 지 고민이 되었습니다.
하단과 상단부분은 간격을 맞추고 중앙부분은 화면크기에 따라서 중앙에 위치하도록 조정하였다.
<br>

## ⭐️ Review point
피그마와 비교해서 화면이 어색한 지.
OauthSignUp.style.ts - nth-child(2)부분에 background-color: white를 안 넣으면 구글로고가 노란색이 되는데 nth-child(1)이 모든 첫번쨰 자식에게 적용되어서 그런거 같은데 어떻게 해결해야할지 모르겠네요
<br>

## 📷 Demo
<br
![Uploading 스크린샷 2024-02-07 오후![스크린샷 2024-02-07 오후 3 07 12](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/d338faa1-5334-421f-a929-ddb004397ede)
>

2024-02-07 09:54 UTC, sikkzz requested changes

2024-02-07 09:54 UTC, sikkzz commented on src/App.tsx
> +import SignUp from "./pages/SignUp/SignUp";
절대경로

2024-02-07 09:54 UTC, sikkzz commented on src/pages/SignUp/OauthSignUp.style.ts
> +		}
2가지 해결책 제공해드려요

1번
<img width="402" alt="스크린샷 2024-02-07 오후 6 48 15" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/0c840e7d-2bc3-42a1-8a5e-75709952b8fe">
<img width="515" alt="스크린샷 2024-02-07 오후 6 48 11" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/1c07bec0-b9a1-49ed-a3d7-3ab0a80f884f">

2번
<img width="547" alt="스크린샷 2024-02-07 오후 6 49 31" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/57778fc3-8bef-477c-9479-989a3a281fee">

2024-02-07 09:54 UTC, sikkzz commented on src/pages/SignUp/OauthSignUp.tsx
> +				<img src="" alt="" />
img source는 그렇다 쳐도 alt값은 넣어놓는게 좋을 거 같네요

2024-02-07 09:54 UTC, sikkzz commented on src/pages/SignUp/OauthSignUp.tsx
> +				<p>서비스 이용약관 | 개인정보 처리방침</p>
디자인상이랑 다른거 같네요 &:after로 content 활용하면 두 요소 사이에 원하는 문자 요소 넣을 수 있습니다

2024-02-07 09:54 UTC, sikkzz commented on src/pages/SignUp/SignUp.tsx
> +	];
data값은 constants에서 관리해주세요 특히 온보딩쪽 고정된 텍스트 요소들 엄청 많아질텐데 잘 관리해주는게 좋겠죠?

2024-02-07 09:54 UTC, sikkzz commented on src/pages/SignUp/SignUp.tsx
> +			<img src="" alt="" />
alt 입력

2024-02-08 07:30 UTC, khkh0109 commented on src/pages/SignUp/OauthSignUp.style.ts
> +export const OauthSignUpStyle = {
OauthSignUpStyle는 일반 객체니 카멜 케이스를 따르는게 일관성 있어서 좋을 것 같습니다! 
```suggestion
export const oauthSignUpStyle = {
```

2024-02-08 07:42 UTC, khkh0109 commented on src/pages/SignUp/SignUp.style.ts
> +export const SignUpStyle = css`
여기도 마찬가지로 컴포넌트가 아닌 일반 변수니까 카멜 케이스를 따르는게 일관성 있을것 같습니다~
```suggestion
export const signUpStyle = css`
```

2024-02-08 10:55 UTC, sikkzz approved these changes, later dismissed

2024-02-08 13:44 UTC, youngTkim approved these changes, later dismissed

2024-02-09 08:03 UTC, sikkzz approved these changes, later dismissed

2024-02-09 08:25 UTC, khkh0109 approved these changes, later dismissed

2024-02-10 02:14 UTC, sikkzz requested changes

2024-02-10 02:14 UTC, sikkzz commented on src/pages/SignUp/OauthSignUp.style.ts
> +		width: 312px;
이 친구는 rem이 아닌 이유가 있을까요

2024-02-11 15:03 UTC, sikkzz approved these changes

2024-02-12 09:27 UTC, youngTkim approved these changes

2024-02-12 11:25 UTC, khkh0109 approved these changes

2024-02-15 00:02 UTC, merged