[TS-244] 별자리 카드 상세 페이지 기본 UI 작업
ConnectingStar/ConnectingStar-Front pull request #17
Opened 2024-02-07 11:51 UTC by khkh0109

[TS-244](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?selectedIssue=TS-244)

## 💡 변경사항 & 이슈
별자리 카드 상세 페이지 기본 UI 작업
<br>

## ✍️ 관련 설명
별자리 카드 상세 페이지의 기본 UI를 만들었습니다. 
- 사용자의 행동에 따라 UI 가 바뀌는 작업은 하지 않았습니다(ex. 토스트, 버튼 disabled 등)
- 공통 Header, Button 컴포넌트가 머지 되면 교체할 예정입니다. (새 브랜치에서 작업 예정)
- 서버에서 전달해주는 데이터 구조를 몰라 값은 대부분 하드코딩 했습니다. 다만 상태에 따라 바뀌는 UI 때문에 임시 data를 작성했습니다(아래 부분). 
  - API 작업 이후 삭제 예정이라 따로 분리하지 않았습니다. 
```tsx
// state 값을 바꿔서 상태에 따라 바뀌는 UI를 확인할 수 있습니다. 
// Img, Button 컴포넌트만 바뀝니다. 
// 상태 종류: default(기본), selected(선택), possession(보유)
const data: dataType = {
  state: "default",
};
```
<br>

## ⭐️ Review point
- [ ] 디자인 시안과 다른 부분 없는지
- [ ] 상태에 따른 Img, Button UI가 잘 변경 되는지
- [ ] 더 괜찮은 이름 있는지

확인 부탁드립니다. 
<br>

## 📷 Demo

|default(기본)|selected(선택)|possession(보유)|
|:---:|:---:|:---:|
|<img width="320" alt="스크린샷 2024-02-07 오후 8 43 14" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/15f1fc8f-a3f5-4897-abb3-221f3c5b9930">|<img width="320" alt="스크린샷 2024-02-07 오후 8 46 39" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/65de8a11-f225-41eb-91c4-816d1581dc96">|<img width="320" alt="스크린샷 2024-02-07 오후 8 47 12" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/d3453d77-bb41-4d3c-9b0c-0d706ac8a047">|

<br>

2024-02-07 16:01 UTC, sikkzz requested changes

2024-02-07 16:01 UTC, sikkzz commented on src/App.tsx
> +import CardDetailPage from "@/pages/CardDetailPage";
StarCardDetailPage가 좋지 않을까요? 어떤 Card인지 이해하기 어려울 거 같아서요

2024-02-07 16:01 UTC, sikkzz commented on src/components/CardDetail/CardDetailPage.style.ts
section에만 padding-bottom값이 있어서 페이지 아래쪽에 여백이 없네요. 아래 여백 필요할거 같아요 디자인상도 여백이 있네요

2024-02-07 16:01 UTC, sikkzz commented on src/components/CardDetail/CardDetailPage.style.ts
> +	background-color: #fff;
없어도 될 거 같네요

2024-02-07 16:01 UTC, sikkzz commented on src/components/CardDetail/CardDetailPage.style.ts
아래 코드처럼 간소화가 가능하지 않을까요?

<img width="565" alt="스크린샷 2024-02-08 오전 12 50 19" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/aa9f92bc-63da-4679-a52b-acae37096b71">
<img width="455" alt="스크린샷 2024-02-08 오전 12 50 23" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/9831ef2c-f96c-4da6-84f2-ef01d5a62a83">

2024-02-07 16:01 UTC, sikkzz commented on src/components/CardDetail/CategoryLabel/CategoryLabel.tsx
label과 categoryLabel을 따로 작성하신 이유가 있을까요? 다른 부분에 재사용되는 컴포넌트도 아닌거 같아서 따로 작성할 이유가 없을 거 같아서요

2024-02-07 16:01 UTC, sikkzz commented on src/components/CardDetail/Img/PossessionLabel.style.ts
> +	padding: 16px 0;
rem

2024-02-07 16:01 UTC, sikkzz commented on src/components/CardDetail/Img/PossessionLabel.style.ts
> +	font-weight: 700;
theme body_a_bold -> 1rem weight 700 값 동일해보이네요

2024-02-07 16:01 UTC, sikkzz commented on src/components/CardDetail/Img/Star.style.ts
> +		font-size: 20px;
rem

2024-02-07 16:01 UTC, sikkzz commented on src/components/CardDetail/Title.tsx
as라는 명칭에 의미가 있나요? 좀 더 직관적인 명칭으로 바꾸는게 좋을 거 같아요. 저게 뭔지 한참을 고민했습니다 코드를 처음 보는 사람 입장에서는 이해할 길이 없어보여요

2024-02-07 16:01 UTC, sikkzz commented on src/components/CardDetail/CardDetailPage.style.ts
해당 파일은 page 디렉토리에 작성하는게 좋지 않을까요? 여기에 있어야할 이유가 없어보이네요. 위에서 말씀드렸듯 Star 명칭 붙이는게 좋을 거 같구요

2024-02-07 16:07 UTC, sikkzz requested changes

2024-02-07 16:07 UTC, sikkzz commented on src/pages/CardDetailPage.tsx
> +	state: "default" | "selected" | "possession";
possession -> have, own 등의 단어가 더 이해하기 쉽지 않을까요?

2024-02-08 03:24 UTC, khkh0109 commented on src/App.tsx
> +import CardDetailPage from "@/pages/CardDetailPage";
그러네요! 더 구체적인 이름으로 변경했습니다~

2024-02-08 03:26 UTC, khkh0109 commented on src/components/CardDetail/CategoryLabel/CategoryLabel.tsx
처음에는 label과 categoryLabel을 함께 작성했는데 조금 복잡해보여서 분리했습니다. label을 재사용 하지 않는다면 굳이 분리할 필요 없이 하나로 작성하는게 더 읽기 편하신가요?

2024-02-08 03:33 UTC, khkh0109 commented on src/components/CardDetail/Img/PossessionLabel.style.ts
> +	font-weight: 700;
앗 그러네요 theme으로 변경하는 중에 빼먹었는데 매의 눈이시네요😃
font와 color 전부 theme에 있는 값으로 교체하겠습니다~

2024-02-08 03:45 UTC, khkh0109 commented on src/components/CardDetail/Img/PossessionLabel.style.ts
> +	padding: 16px 0;
padding 부분 말씀하시는건가요? 이 부분을 px로 한 이유는 폰트 사이즈가 확대 됐을때 rem으로 하니까 비율이 조금 이상하더구요. 그래서 위 아래 여백은 고정되는게 나을것 같아서 px로 했는데, 다시 보니 차라리 width와 padding을 전부 rem으로 변경해서 확대되어도 동일한 비율을 유지하는게 낫겠네요

2024-02-08 04:23 UTC, khkh0109 commented on src/components/CardDetail/Img/Star.style.ts
> +		font-size: 20px;
이 부분도 폰트 사이즈만 rem으로 하면 폰트 사이즈가 확대 됐을때 strong 부분이 이미지를 벗어나기 때문에 전부 rem으로 변경했습니다

2024-02-08 04:35 UTC, khkh0109 commented on src/components/CardDetail/Title.tsx
Title 컴포넌트가 h1 '처럼' / h2 '처럼' 쓰인다는 의미에서 as로 작명했습니다. 
그럼 직관적으로 작명한다면 html 요소를 의미하는 Element는 어떠세요? 또는 Tag도 있을 것 같아요

2024-02-08 04:44 UTC, khkh0109 commented on src/pages/CardDetailPage.tsx
> +	state: "default" | "selected" | "possession";
그러게요 have가 더 이해하기 쉬울것 같네요!

2024-02-08 05:26 UTC, khkh0109 commented on src/components/CardDetail/CategoryLabel/CategoryLabel.tsx
이 부분은 PossessionLabel과 스타일만 다르고 구조가 완전히 똑같아서 Label 컴포넌트를 재사용하게 되었습니다. 그래서 분리해두는걸로 하겠습니다 !

2024-02-08 05:47 UTC, khkh0109 commented on src/components/CardDetail/CardDetailPage.style.ts
디자인 상에는 버튼이 사각형 박스 내부에 있어서 스크롤 될 때 화면에 고정될거라고 착각했네요 ! 수정해두겠습니다 ~

2024-02-08 07:21 UTC, khkh0109 commented on src/components/CardDetail/CardDetailPage.style.ts
넵 이렇게 간소화할 수 있을 것 같네요 우선 디자인과 동일하게 이렇게 변경해두고 나중에 버튼 컴포넌트 만들어지면 교체하겠습니다 ~

2024-02-08 09:49 UTC, sikkzz commented on src/components/CardDetail/Title.tsx
tag가 낫지 않을까 싶네요!

2024-02-08 11:53 UTC, pizzaYami commented on src/pages/CardDetailPage.tsx
> +				<Title as="h2">캐릭터에 대한 설명</Title>
캐릭터에 대한 설명 -> 캐릭터 설명 문구

2024-02-08 13:59 UTC, pizzaYami approved these changes, later dismissed

2024-02-09 08:02 UTC, sikkzz approved these changes, later dismissed

2024-02-09 08:14 UTC, khkh0109 commented
dev theme color에 이름 바뀐 부분을 반영했습니다 (main_light_blut, main_blue)

2024-02-09 09:47 UTC, sikkzz submitted a review, later dismissed

2024-02-12 11:13 UTC, youngTkim submitted a review, later dismissed

2024-02-15 00:03 UTC, pizzaYami approved these changes, later dismissed

2024-02-15 10:46 UTC, sikkzz approved these changes

2024-02-18 06:50 UTC, pizzaYami approved these changes

2024-02-18 06:52 UTC, pizzaYami requested changes

2024-02-18 06:52 UTC, pizzaYami commented on src/components/StarCardDetail/Img/Star.style.ts
> +	right: 16px;
rem으로 변경해야겠네요

2024-02-18 07:26 UTC, khkh0109 commented on src/components/StarCardDetail/Img/Star.style.ts
> +	right: 16px;
이 부분을 rem으로 했을때 별 위치에 영향이 가서 px로 했는데, 이 경우에도 rem이 나을까요? 폰트 사이즈가 커지면 빨간색 화살표 부분이 더 길어져서 별이 이미지 안쪽으로 이동 하더라구요
<img width="200" alt="스크린샷 2024-02-18 오후 4 20 14" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/118bfcf5-36fe-45b2-b521-e011a6722888">

2024-02-18 07:43 UTC, pizzaYami commented on src/components/StarCardDetail/Img/Star.style.ts
> +	right: 16px;
테스트 해봤는데 px로 하는게 낫겠네요 ㅎㅎ

2024-02-19 07:11 UTC, pizzaYami approved these changes

2024-02-19 11:11 UTC, youngTkim approved these changes

2024-02-19 11:17 UTC, merged