[TS-241] Design MyInfoPage Landing
ConnectingStar/ConnectingStar-Front pull request #18
Opened 2024-02-07 13:55 UTC by sikkzz

[TS-241](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109/backlog?epics=visible&selectedIssue=TS-241)

## 💡 변경사항 & 이슈
내 정보 페이지 랜딩 디자인

## ✍️ 관련 설명
내 정보 페이지 디자인 구현입니다. 기능들은 새 브랜치에서 구현 예정입니다.

## ⭐️ Review point
/myinfo로 접근 가능합니다.

## 📷 Demo
<img width="365" alt="스크린샷 2024-02-05 오후 7 32 46" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/967f7ec0-d8d8-4b3a-9838-679becc684c4">
<img width="364" alt="스크린샷 2024-02-05 오후 7 32 52" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/ed38fddd-04f3-454e-84ae-e70410954345">

[TS-241]: https://m2jun.atlassian.net/browse/TS-241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TS-241]: https://m2jun.atlassian.net/browse/TS-241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-02-08 11:35 UTC, pizzaYami requested changes

2024-02-08 11:35 UTC, pizzaYami commented on src/components/MyPage/MyInfo/MyInfo.style.ts
> +	width: 360px;
질문입니다
width 320px 이하가 되면 화면이 짤리는데 대부분 스마트폰 화면 width가 320이상이라서 상관없나요?

그리고 px를 대부분 rem으로 바꿔야 할 것 같네요

2024-02-08 11:35 UTC, pizzaYami commented on src/components/MyPage/Button/Button.style.ts
>  	width: 100%;
${theme.font.body_b_bold};
추가

2024-02-08 11:35 UTC, pizzaYami commented on src/components/MyPage/Button/Button.style.ts
> +		font-weight: 400;
${theme.font.body_b};
추가

2024-02-08 11:35 UTC, pizzaYami commented on src/components/MyPage/MyInfo/MyInfo.tsx
> +								isSubText={true}
isSubText만 넣는건 어떤가요?

2024-02-08 11:35 UTC, pizzaYami commented on src/components/MyPage/MyInfo/MyInfo.tsx
> +			<div css={dividerStyle} />
저번 프로젝트때 화면 전체를 가로지르는 선을 요구하셨는데 이번에 어떻게 물어봐야겠네요

2024-02-08 13:46 UTC, youngTkim approved these changes

2024-02-08 13:47 UTC, youngTkim commented on src/components/MyPage/Button/Button.style.ts
> +		font-weight: 400;
main_Blue 나중에 theme.js 받으면 요 변수명 아마 바꿔질꺼같네영

2024-02-08 13:48 UTC, youngTkim approved these changes

2024-02-09 08:32 UTC, khkh0109 commented on src/pages/MyInfoPage.tsx
> +			<MyInfo />;
`<MyInfo />` 뒤에 세미콜론이 들어가있어서 화면에 보여요! 

<img width="456" alt="스크린샷 2024-02-09 오후 5 31 22" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/48cb72a2-2bf8-40d9-b1f3-c3b3529b0497">

2024-02-09 08:44 UTC, khkh0109 commented on src/components/MyPage/Landing/Landing.style.ts
>  	border-radius: 16px;
이게 혹시 아래 사진에서 회색 프로필 사진 부분이 맞나요? 맞다면 피그마에서는 border-radius가 15px인 것 같은데 확인 부탁드립니다 ~
<img width="336" alt="스크린샷 2024-02-09 오후 5 42 37" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/69281c62-1c56-4d43-a0a3-f7130a6fa634">

2024-02-12 11:12 UTC, youngTkim approved these changes

2024-02-12 11:26 UTC, khkh0109 approved these changes

2024-02-15 00:57 UTC, pizzaYami approved these changes

2024-02-15 07:01 UTC, merged