[Ts-206] eslint package.json 삭제복구 및 theme.color.main_Blue -> blue
ConnectingStar/ConnectingStar-Front pull request #19
Opened 2024-02-07 14:54 UTC by pizzaYami

[JIRA]()

## 💡 변경사항 & 이슈
eslint package.json 삭제복구 및 theme.color.main_Blue -> blue
<br>

## ✍️ 관련 설명
node_module이 생성되어서 .yarn/sdks/eslint/package.json이 삭제된 것 같습니다.
node_module은 왜 자꾸 생성되는지 모르겠네요
1. yarn set version berry
2. yarn install
3. 버전에러 뜨면 yarn dlx @yarnpkg/sdks vscode
4. type변경 후 사용
이런 순서로 사용하는데 잘 못 된게있나요?
<br>

## ⭐️ Review point
<br>

## 📷 Demo
<br>

2024-02-07 14:58 UTC, sikkzz requested changes

2024-02-07 14:58 UTC, sikkzz commented on src/styles/theme.ts
>  		main_lightBlue: "#E6F1FE",
snake case면 deep_blue light_blue 얘도 수정해야 하는거 아닐까요!

2024-02-07 15:11 UTC, sikkzz submitted a review, later dismissed

2024-02-07 16:02 UTC, sikkzz approved these changes

2024-02-08 01:29 UTC, khkh0109 approved these changes

2024-02-08 11:35 UTC, youngTkim approved these changes

2024-02-08 11:36 UTC, merged