[TS-253] Design MyStarTrace Page
ConnectingStar/ConnectingStar-Front pull request #20
Opened 2024-02-07 15:40 UTC by sikkzz

[TS-253](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?assignee=712020%3Add928be4-89fa-4c60-9aa8-e0ad8f6b5a7b&selectedIssue=TS-253)

## 💡 변경사항 & 이슈
나의 별자취 페이지 디자인

## ✍️ 관련 설명
[나의 별자취 페이지 디자인](https://www.figma.com/file/deVOGLOqzbCjKJP9fDeB3i/%EC%BB%A4%EB%84%A5%ED%8C%85%EC%8A%A4%ED%83%80?type=design&node-id=3722-3675&mode=design&t=Xg5roP9dxIJCrUm0-4)입니다. 기능은 다른 브랜치에서 구현 예정이고 헤더 아직 제외했습니다.

## ⭐️ Review point
/star-trace로 접근 가능합니다.

마찬가지로 241번 브랜치가 merge가 안된 상태라 TS-253 커밋만 확인하시면 됩니다.

## 📷 Demo
<img width="390" alt="스크린샷 2024-02-08 오전 12 39 14" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/d8606984-bd45-42c7-a799-e978c5cc82e6">

2024-02-08 11:34 UTC, pizzaYami requested changes

2024-02-08 11:34 UTC, pizzaYami commented on src/components/MyPage/StarTrace/ButtonCarousel.style.ts
> +	margin: 0 auto;
overflow: auto; // 좌우 스크롤

	scrollbar-width: none; /* 파이어폭스 스크롤바 없애기*/
	::-webkit-scrollbar {
		display: none; /* 크롬, 사파리, 오페라, 엣지  스크롤바 없애기*/
	}
	요거 추가해주면 좋겠네요
	
	360px 넘어가도 버튼이 보이도록 설정해야 될 것 같네요

2024-02-08 11:34 UTC, pizzaYami commented on src/components/MyPage/StarTrace/Content.tsx
> +				{habitIconData.map((data) => (
map을 쓴 이유가 있을까요?

2024-02-08 16:45 UTC, sikkzz commented on src/components/MyPage/StarTrace/Content.tsx
> +				{habitIconData.map((data) => (
icon data를 순회하면서 해당 데이터값에 맞는 아이콘을 리턴해주려고 사용했습니다. 이렇게 안하면 조건문으로 하나하나 걸러줘야 하는데 그 코드보다는 간소화된 코드라고 생각해서 사용했어요.

더 좋은 방법이 있다면 말씀해주세요!

2024-02-12 11:19 UTC, youngTkim approved these changes

2024-02-12 11:36 UTC, khkh0109 commented on src/pages/MyStarTracePage.tsx
> +			<StarTrace />;
컴포넌트 끝에 세미콜론이 있어서 화면에 보입니다 !
<img width="400" alt="스크린샷 2024-02-12 오후 8 36 04" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/63e8632a-52dd-46f5-a22a-f221c7cd1185">

2024-02-12 11:49 UTC, khkh0109 commented on src/components/MyPage/StarTrace/SortButton.style.ts
> +	border: 2px solid ${theme.color.button_disabled};
SortButton에서 제일 첫번째 버튼(최신순 버튼)의 세로 길이가 디자인 시안과 조금 다릅니다. 뒤에 있는 버튼 두개의 세로 길이와 동일하게 36px로 맞춰야 할 것 같아요
<img width="341" alt="스크린샷 2024-02-12 오후 8 48 49" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/d361d61b-1bca-47d9-9bc8-3074e4460f4f">

2024-02-12 12:20 UTC, khkh0109 commented on src/constants/myPageConstants.tsx
> +];
habitIconData를 배열로 작성하신 이유가 무엇일까요? 아이콘의 순서가 중요해서 배열로 작성하신걸까요? 객체로도 작성할 수 있을것 같은데 배열을 선택하신 이유가 궁금해서 여쭤봅니다!

2024-02-12 13:21 UTC, sikkzz commented on src/constants/myPageConstants.tsx
> +];
id값과 이에 대응하는 icon value가 같이 들어가야 하는데 객체로는 각각 대응하는 값을 한번에 선언 못하지 않나요? 또한 용주님 리뷰에 달아드렸듯 id값에 맞는 아이콘을 map으로 리턴해주기 위해서 작성했습니다. id 값은 추후에 백엔드에서 어떻게 넘어오게 될지는 모르겠지만 구조가 변하지는 않을 거 같아서요

2024-02-15 01:02 UTC, pizzaYami approved these changes

2024-02-15 06:42 UTC, khkh0109 approved these changes

2024-02-15 07:02 UTC, merged