[TS-258] 공통 Header 컴포넌트 리팩토링
ConnectingStar/ConnectingStar-Front pull request #22
Opened 2024-02-09 07:28 UTC by khkh0109

[TS-258](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?selectedIssue=TS-258)

## 💡 변경사항 & 이슈
Header 컴포넌트 리팩토링
<br>

## ✍️ 관련 설명
Header 컴포넌트 리팩토링
- eslint import order 적용
- font, color를 theme 값으로 변경 (큰 제목일때 font-weight도 함께 적용됨)
- common/Header 폴더 내부로 컴포넌트 파일 이동 (Header.tsx, Header.style.ts)
<br>

## ⭐️ Review point
변경 잘 되었는지 확인 부탁드립니다. 
<br>

## 📷 Demo
<img width="385" alt="스크린샷 2024-02-09 오후 4 27 00" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/0890b3cf-c541-4135-9063-4eb924f406db">

<br>

2024-02-09 08:02 UTC, sikkzz requested changes

2024-02-09 08:02 UTC, sikkzz commented on src/components/common/Header/Header.tsx
import order는 설정파일 문제였네요 제가 올려놓은 pr 머지되면 rebase해서 이 pr도 머지해주세요!

2024-02-09 08:17 UTC, khkh0109 commented on src/components/common/Header/Header.tsx
넵 알겠습니다 !

2024-02-12 11:19 UTC, youngTkim approved these changes, later dismissed

2024-02-12 13:29 UTC, sikkzz commented on src/components/common/Header/Header.tsx
머지했으니 받아와서 수정하시면 될 거 같네요

2024-02-14 05:57 UTC, sikkzz approved these changes

2024-02-15 01:13 UTC, pizzaYami approved these changes

2024-02-19 07:12 UTC, pizzaYami approved these changes

2024-02-19 11:11 UTC, youngTkim approved these changes

2024-02-19 11:18 UTC, merged