[TS-255] Design Notification Setting Page
ConnectingStar/ConnectingStar-Front pull request #24
Opened 2024-02-11 11:52 UTC by sikkzz

[TS-255](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?assignee=712020%3Add928be4-89fa-4c60-9aa8-e0ad8f6b5a7b&selectedIssue=TS-255)

## 💡 변경사항 & 이슈
알림 설정 페이지 디자인

## ✍️ 관련 설명
[알림 설정 페이지 디자인](https://www.figma.com/file/deVOGLOqzbCjKJP9fDeB3i/%EC%BB%A4%EB%84%A5%ED%8C%85%EC%8A%A4%ED%83%80?type=design&node-id=3722-3627&mode=design&t=SkcB6EK4P7BXnjjt-4)입니다. 기능은 다른 브랜치에서 구현 예정입니다.

## ⭐️ Review point
/notification-setting으로 접근 가능합니다.
TS-255 커밋 한개만 보시면 됩니다.
토글 버튼 기능은 작동합니다.

## 📷 Demo
<img width="407" alt="스크린샷 2024-02-11 오후 8 51 37" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/b2bfdf04-bbc5-41c0-aa62-49d749332eed">

2024-02-12 11:21 UTC, youngTkim approved these changes

2024-02-15 01:20 UTC, pizzaYami requested changes

2024-02-15 01:20 UTC, pizzaYami commented on src/components/MyPage/NotificationSetting/Button.tsx
> +	isHabit?: boolean | undefined;
undefined 지워도 실행되지 않나요?

2024-02-19 03:09 UTC, khkh0109 approved these changes

2024-02-19 07:12 UTC, pizzaYami approved these changes

2024-02-19 07:17 UTC, merged