TS-4/Feat/HomePage
ConnectingStar/ConnectingStar-Front pull request #28
Opened 2024-02-15 06:32 UTC by youngTkim

[TS-4](https://m2jun.atlassian.net/browse/TS-4)

## 💡 변경사항 & 이슈
HomePage.tsx 및 이하 컴포넌트 제작
<br>

## ✍️ 관련 설명
현재 시각과 타겟 시각을 계산, 화면에 표기
화면에 렌더링되는 dateList의 29로 제한해서 캐러셀 스크롤값에 따라 이전 14일 값과 이후 14일 값을 렌더링
,slice하여 29개로 유지, dateList가 업데이트되면 스크롤 중앙값으로 정렬 

api로 fetch할 때는 dateList를 업데이트하고 한꺼번에 날짜데이터를 fetch해서 값을 넣게 되고, fetch할 때는 plan이 있는지 여부만 표기하고, 타겟 날짜를 클릭하면 해당 날짜의 계획을 그 때 fetch하는 식으로 만들 것 같습니다.
<br>

## ⭐️ Review point
캐러셀 스크롤을 오늘로 정렬하는 기능이 필요한지? 날짜를 계산하는 매커니즘을 더 짧게 줄일 수 있는지?
<br>

## 📷 Demo
<img width="503" alt="스크린샷 2024-02-15 오후 3 20 37" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/117588223/5777671a-ac58-458b-aa2b-e1d4775c3cff">
<img width="499" alt="스크린샷 2024-02-15 오후 3 20 55" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/117588223/a04f3ab1-1bf2-4113-a4e8-d7c1ecbef1fc">
<br>

2024-02-15 07:42 UTC, sikkzz requested changes

2024-02-15 07:42 UTC, sikkzz commented on src/components/common/Gnb/Gnb.style.ts
gnb 같은 경우 공통 컴포넌트로 다른 페이지들에서도 사용되는 컴포넌트입니다.
이렇게 개인 페이지 작업에서만 필요한 코드 수정시 다른 페이지에서는 어긋나고 깨질 수가 있어요.
현재 영택님이 작성하신 코드 가져와서 mypage에 적용하면 하단 버튼들이 가려집니다.

다른곳에서도 사용되는 공통 컴포넌트는 따로 브랜치 파서 리팩토링 진행해주세요. 다른 페이지에서도 테스트를 해봐야 하는데 그렇다고 현재 영택님이 작업하신 브랜치 전체를 끌고와서 테스트해보는건 비효율적이니까요.

해당 브랜치에서 코드 삭제하고 다른 pr 새로 올려주세요

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/Advices.style.ts
컴포넌트 폴더 대문자 시작으로 알고있네요

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/Advices.style.ts
> +		height: 120px;
rem

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/Advices.style.ts
> +		margin-bottom: 20px;
rem

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/Advices.style.ts
> +		border-radius: 20px;
radius 15px입니다

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/Advices.style.ts
해당 컴포넌트 격려 문구는 고정된 문구들인거 같은데 디자인 확인해보시고 추가해주셔야할거 같네요

2초 간격으로 자동 넘어가고 유저가 스와이프하여 좌우로 넘길 수 있다고 되어있는데 기능은 다른 브랜치에서 구현 예정이신가요? pr에 내용 작성 부탁드려요

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/Advices.style.ts
> +		overflow-x: hidden;
스크롤 액션 여부에 따라 수정되어야 하는 스타일입니다

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/Advices.tsx
> +import { AdvicesStyle } from "./Advices.style";
절대경로

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/Advices.tsx
> +function Advices(): ReactNode {
react node 명시 안해도 작동에는 문제 없을텐데 명시하신 이유가 있을까요?

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/Advices.tsx
> +		<section
<section css={AdvicesStyle.container} />

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/ComprehensiveHabits.style.ts
> +export const ComprehensiveHabitsStyle = {
camel Case 적용 부탁드려요

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/Advices.style.ts
> +export const AdvicesStyle = {
camelCase

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/ComprehensiveHabits.style.ts
> +		width: 100%;
불필요해보이네요

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/ComprehensiveHabits.style.ts
> +		display: flex;
flex에서는 gap을 사용하면 요소간 간격 조절이 가능합니다. gap 사용시 내부 요소 margin값 모두 삭제 가능해요

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/ComprehensiveHabits.tsx
Comprehensive라고 작성하면 무슨 컴포넌트인지 이해가 어려울 거 같은데 변경하는게 어떠신가요? 우선 어떤 의미로 작성하신 컴포넌트 단위인지 현재도 이해가 안가네요

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/ComprehensiveHabits.tsx
> +	const DOTW = today.getDay();
무슨 변수명인지 알 수 있을까요?

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/ComprehensiveHabits.tsx
> +import Habits from "./ComprehensiveHabitsDetail/Habits.tsx";
절대경로

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/ComprehensiveHabits.tsx
> +	const convertTimeDiff = (diff: number): string => {
util쪽으로 빼는게 나을 거 같네요

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/ComprehensiveHabits.tsx
> +		const TD: Date = new Date(`${year}.${month}.${day}`);
변수명의 의미 해석하기가 어렵네요 주석을 달아놓으셔도 변수명은 직관적인 네이밍이 좋습니다. 또한 특별한 사유가 없으면 camelCase 적용 시켜주시고요

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/ComprehensiveHabits.tsx
> +			css={css`
인라인에 css` 별도 작성 필요 없어요 전체 코드에 해당되는 리뷰입니다 모두 수정해주세요

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/ComprehensiveHabitsDetail/Calender.style.ts
> +		margin-bottom: 20px;
rem (gap 적용하면 불필요 코드)

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/ComprehensiveHabitsDetail/Calender.style.ts
> +		width: 100%;
불필요

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/ComprehensiveHabitsDetail/Calender.style.ts
> +		height: 100%;
불필요

2024-02-15 07:42 UTC, sikkzz commented on src/components/homepages/ComprehensiveHabitsDetail/Calender.style.ts
> +	timeDiff: css`
미사용되고 있는 코드네요

2024-02-15 07:47 UTC, sikkzz commented
리뷰 하다 말았는데 전체적으로 수정하고 리뷰하는게 나을 거 같아서 먼저 그냥 코멘트 달아요 말씀 안드리면 리뷰할게 너무 많아질 거 같네요

1. rem 전체적으로 코드 확인하면서 적용시켜주세요
2. css 적용시킬때 인라인에 css`` 추가할 필요 없습니다. css 스타일 파일에서 이미 선언해주기에 인라인에 간단하게 스타일 파일 빼서 작성하는건데 이러면 두번 사용할 뿐만 아니라 장점이 사라집니다.
3. 불필요 코드가 너무 많습니다. 사용되지 않는 코드부터 시작해서 부모, 자식 태그 간에 width, height 들은 기본적으로 부모 요소 따라가기 때문에 적용 안시켜도 최대값 안에 들어가는 경우가 많습니다. 코드 전체적으로 확인하면서 미사용 코드도 같이 삭제해주세요

우선 pr 코드양이 너무 많습니다. 분명 처음 얘기할 때 2~300줄 정도가 적당하다 얘기를 했었던 거 같은데 제가 브랜치 나누고 pr 나눠서 작성하는 이유입니다. 다음부터는 코드 양 확인하면서 작업 세분화하고 pr 올려주세요

저희가 앞서 회의하면서 정한 내용들과 컨벤션에 나와있는 내용들이 많은데 이런 부분들은 꼼꼼하게 체크하고 작성 부탁드려요ㅠ 리뷰하면서 이런 리뷰가 한 두개가 아니면 다 짚어드리기도 리뷰하는 사람 입장에서 힘듭니다. 신경써서 작성부탁드릴게요

리팩토링 한번 싹 진행하면 리뷰 다시 할게요

2024-02-15 09:35 UTC, pizzaYami requested changes

2024-02-15 09:35 UTC, pizzaYami commented on src/pages/HomePage.style.tsx
> +		min-width: 100%;
display: flex;
flex-direction: column;
min을 제거해도 될거같네요

2024-02-15 09:35 UTC, pizzaYami commented on src/components/homepages/Profile.tsx
> +						color: ${theme.color.main_Blue};
Profile.style.ts에서 사용하지 않는 이유가 있나요?

2024-02-15 09:35 UTC, pizzaYami commented on src/components/homepages/Profile.style.ts
> +		border-radius: 4px;
border-radius: 5px

2024-02-15 09:35 UTC, pizzaYami commented on src/components/homepages/Profile.tsx
> +						${theme.font.head_c};
body_c

2024-02-15 09:35 UTC, pizzaYami commented on src/components/homepages/Profile.tsx
> +						${theme.font.head_a}
head_c

2024-02-15 09:35 UTC, pizzaYami commented on src/components/homepages/Profile.tsx
> +						height: 75%;
크기가 맞지 않아요 %보다는 1.75rem으로 바뀌어야 하겠네요

2024-02-15 09:37 UTC, pizzaYami commented
저도 리뷰하다가 전체적인걸 이야기하면 좋을 것 같아서 comment 남겨봅니다.
준식님이 언급하신 것 이외에도 피그마와 맞지 않는 부분이 많은 것 같네요.
피그마를 보고 디자이너 요구한대로 상세하게 크기를 맞춰가야합니다!

거의 처음으로 PR하시는거라서 어려움이 많겠지만 익숙해지면 금방입니다!

2024-02-19 13:00 UTC, sikkzz requested changes

2024-02-19 13:00 UTC, sikkzz commented on src/App.tsx
> +import RestCommentPage from "./pages/RestCommentPage";
절대 경로

2024-02-19 13:00 UTC, sikkzz commented on src/components/homepages/Advices.style.ts
수정 안된 거 같아요

그리고 src/components/Home 으로 변경하시는게 좋을 거 같네요

2024-02-19 13:00 UTC, sikkzz commented on src/components/homepages/Advices.tsx
> +import banner05 from "@/assets/image/img-homepage-banner-05.png";
constants로 빼는게 좋겠죠?

2024-02-19 13:00 UTC, sikkzz commented on src/components/homepages/Advices.tsx
> +	}, [currentIndex]);
같은 조건의 useEffect인데 따로 작성하신 이유가 있을까요?

2024-02-19 13:00 UTC, sikkzz commented on src/components/homepages/Advices.tsx
> +						<li css={advicesStyle.adviceWrapper} key={idx}>
constants로 빼서 image값들 사용하시면 idx 말고 고유의 id 키값으로 사용할 수 있겠네요 그럼 idx도 필요 없겠구요

추가적으로 index를 키값으로 사용하는건 좋지 않습니다. 고유의 키값이 아닌 겹칠 수 있는 number 값이거든요

2024-02-19 13:00 UTC, sikkzz commented on src/components/homepages/Advices.tsx
> +							<img src={image}></img>
`<img src={image} />` 로 변경, alt값 추가

2024-02-19 13:00 UTC, sikkzz commented on src/components/homepages/Calender.tsx
> +interface DateListEl {
prop type이면 맞게 명칭을 바꿔주는게 낫겠죠?

2024-02-19 13:00 UTC, sikkzz commented on src/components/homepages/Calender.tsx
> +					</span> */}
불필요 주석 제거

2024-02-19 13:00 UTC, sikkzz commented on src/components/homepages/Calender.tsx
인라인 css`` 제거

2024-02-19 13:00 UTC, sikkzz commented on src/pages/HomePage.tsx
HomePage 폴더 만들어서 style file이랑 같이 넣어주세요

2024-02-19 13:00 UTC, sikkzz commented on src/pages/HomePage.tsx
> +	const DOTW = today.getDay();
변수명 의미가 뭔가요?

2024-02-19 13:00 UTC, sikkzz commented on src/pages/HomePage.tsx
> +	const convertTimeDiff = (diff: number): string => {
util로 빼는게 나을 거 같네요 다른곳에서도 사용될 거 같기도 하구요

2024-02-19 13:00 UTC, sikkzz commented on src/pages/HomePage.tsx
> +};
이렇게 작성할 필요가 없을 거 같은 코드입니다.

2024-02-19 13:00 UTC, sikkzz commented on src/pages/HomePage.tsx
> +			<HomePage.InnerWrapper>
그냥 일반 컴포넌트로 작성하면 될 거 같아요

2024-02-19 13:00 UTC, sikkzz commented on src/pages/RestCommentPage.tsx
comment보다는 record(기록)이 나을 거 같네요 comment는 누구나 직관적으로 댓글로 인식하니까요 이부분은 코드 전체 확인하면서 변경해주세요

2024-02-19 13:00 UTC, sikkzz commented on src/pages/HomePage.style.tsx
> +		min-width: 100%;
불필요 코드 같네요

2024-02-19 13:00 UTC, sikkzz commented on src/pages/HomePage.style.tsx
> +		width: 100%;
불필요

2024-02-19 13:00 UTC, sikkzz commented on src/pages/HomePage.style.tsx
> +		gap: 1.25rem;
gap 다시 확인해주세요 시안 보면 각 컴포넌트별로 gap 다릅니다

2024-02-19 13:00 UTC, sikkzz commented on src/pages/HomePage.style.tsx
> +		padding: 1.5rem;
위 아래 padding 값은 24px이 아닌 거 같아요 시안 확인해주세요

2024-02-19 13:00 UTC, sikkzz commented on src/pages/HomePage.tsx
> +	const daysOfTheWeek = ["일", "월", "화", "수", "목", "금", "토"];
상수 처리 해주세요 이부분은 저랑 겹치는 데이터긴 한데 이후에 공통화 시켜드릴게요 상수쪽으로 빼주세요 일단

2024-02-19 13:00 UTC, sikkzz commented on src/pages/HomePage.tsx
> +	const [timeDiff, setTimeDiff] = useState<string>("오늘");
시간 차이 변수명인데 너무 길어서 이렇게 작성한게 맞다면 timeGap을 사용하면 되지 않을까요? 변수명은 줄이지 말아주세요
다른 사람들이 보기에도 직관적인 변수, 함수명이 좋습니다. 길어지더라도요

2024-02-19 13:00 UTC, sikkzz commented on src/pages/HomePage.tsx
> +		const daysDiff = Math.floor(timeDiffInMs / (1000 * 60 * 60 * 24));
여기도 util 함수로 제작해보는게 나을 거 같네요

2024-02-19 13:00 UTC, sikkzz commented on src/components/homepages/Calender.tsx
> +	};
상위 컴포넌트인 home에서 분명 본 코드인데 여기 또 있을 이유가 있나요? 분명 넘겨서 사용할 수 있을텐데요

2024-02-19 13:00 UTC, sikkzz commented on src/components/homepages/Calender.tsx
> +interface DateListEl {
심지어 homepage 컴포넌트에 있는 타입이네요 types 파일로 뺴주세요

2024-02-19 13:02 UTC, sikkzz commented
여전히 불필요 코드도 많고 시안이랑 다른 부분도 너무 많습니다. 꼼꼼하게 확인 하면서 작성 부탁드려요.. 

체크해야할 부분이 많아서 제가 피그마 보고 코드 보고 구현된 상황 보고 다 체크하면서 리뷰하는데 이러면 제가 구현하는거랑 다른 점이 없습니다. 

아직 전체 파일의 반도 못봐서 계속 리뷰 해드릴게요 수정해주세요

2024-02-19 13:06 UTC, youngTkim commented on src/components/homepages/Advices.style.ts
넵 수정하겠습니다 components는 대문자로 바꿀까요 둘까요?

2024-02-19 13:07 UTC, youngTkim commented on src/components/homepages/Advices.tsx
> +import banner05 from "@/assets/image/img-homepage-banner-05.png";
넵 수정하겠습니당

2024-02-19 13:07 UTC, youngTkim commented on src/components/homepages/Advices.tsx
> +	}, [currentIndex]);
아 합치겠습니다

2024-02-19 13:08 UTC, youngTkim commented on src/components/homepages/Advices.tsx
> +						<li css={advicesStyle.adviceWrapper} key={idx}>
넵 동시에 수정하겠습니다

2024-02-19 13:10 UTC, youngTkim commented on src/components/homepages/Calender.tsx
> +	};
넵 이것도 수정하겠습니다

2024-02-19 13:13 UTC, youngTkim commented on src/pages/HomePage.tsx
> +	const convertTimeDiff = (diff: number): string => {
@/utils/* 요기에 따로 폴더 만들어서 빼면될까요?

2024-02-19 13:15 UTC, youngTkim commented on src/pages/HomePage.tsx
> +	const DOTW = today.getDay();
getday()자체는 숫자로 반환되서 daysOfTheWeek이렇게 처리한다음에 daysOfTheWeek[DOTW]로 만들긴해서 다른변수명 고려해보겠습니다. 그리고 상수처리가 constants로 빼달라하시는거맞으시죠?

2024-02-19 15:25 UTC, sikkzz commented on src/components/homepages/Advices.style.ts
src/components/Home/Advices.style.ts 이렇게요

2024-02-19 15:33 UTC, sikkzz commented on src/pages/HomePage.tsx
> +	const DOTW = today.getDay();
네 constants로 빼고 상수처리해달라는 얘기 맞습니다. 

아래 리뷰에 달아드렸는데 축약 안하시는게 좋습니다. 또한 camelCase로 작성하셔야 하고요

2024-02-19 15:38 UTC, sikkzz requested changes

2024-02-19 15:38 UTC, sikkzz commented on src/components/homepages/Calender.tsx
> +				}}
코드 내부에 이렇게 복잡한 로직의 코드들이 들어가면 안좋습니다. 각 용도에 따라 hook이나 util로 빼서 제작하고 handle 함수로 동작시켜주는게 좋습니다.

그리고 비슷한 로직들은 간소화 및 공통화해서 사용하시구요 하나하나 이렇게 다 작성하시면 코드량도 늘어나고 성능적으로 비효율적입니다.

2024-02-19 15:38 UTC, sikkzz commented on src/components/homepages/Calender.tsx
> +								</section>
여기도요 위랑 동일하게요 기능 로직을 뺴서 구현하고도 내부 코드가 길어지면 그땐 컴포넌트 단위를 나눠야겠죠?

2024-02-19 15:40 UTC, sikkzz commented
컴포넌트와 스타일 파일들이 한 디렉토리에 많으면 폴더 만들어서 관리해주세요

모달 코드들은 이후에 리뷰하겠습니다. 우선 제 모달 브랜치 확인하시고 로직 바꿔주세요.

모달 오픈 여부 관리를 useState로 내부에서 관리 안하는 이유는 필요시에만 작동되어야 하는 코드이기 때문입니다. react portal 관련 내용 서칭 해보세요 root와 modal이 따로 렌더링 되는 방식으로 진행됩니다. 제가 구현한 방식도 동일하고요

2024-02-19 15:44 UTC, sikkzz commented
다른 사람들의 코드를 확인하고 로직들과 기능들을 참고하는게 코드리뷰를 진행하는 이유중 하나이기도 합니다.  본인이 구현은 안하는 부분들이지만 학습하고 코드 작성에 도움될 수 있어야 하니까요.

현재 달아드리는 리뷰들과 질문중에 분명 제 코드 작성 과정에서 확인하실 수 있는 부분들이 많았을텐데 코드들을 제대로 확인 안하시게 되면 타인이 리뷰해서 본인이 수정해야 하는 이런 번거로움이 생기게 됩니다.

팀원들 코드 잘 확인하면서 진행해주세요

2024-02-19 15:55 UTC, sikkzz requested changes

2024-02-19 15:55 UTC, sikkzz commented on src/components/restcommentpages/RestComment.tsx
> +	];
상수

2024-02-19 15:55 UTC, sikkzz commented on src/components/restcommentpages/RestComment.tsx
얘도 폴더명 수정해주세요

2024-02-19 15:55 UTC, sikkzz commented on src/components/restcommentpages/RestComment.tsx
> +				<div css={restCommentStyle.innerTitle}>쉬는 날이셨군요?</div>
div가 아닌 heading 태그 사용해야겠죠?

2024-02-19 15:55 UTC, sikkzz commented on src/components/restcommentpages/RestComment.tsx
> +					<div css={restCommentStyle.lineWrapper}>
여기도 div가 아닌 paragraph가 더 맞아보입니다

2024-02-19 15:55 UTC, sikkzz commented on src/components/restcommentpages/RestComment.tsx
> +						{lines.map((line) => {
map에서 "{}" 가 아닌 "()" 를 사용하면 return문 불필요합니다

2024-02-19 15:55 UTC, sikkzz commented on src/components/restcommentpages/RestComment.tsx
하단 버튼은 공통 버튼으로 적용시킨다 쳐도 시안에 있는 글자수 제한 관련이 안들어갔네요

미완성이라면 미완성 상태에서는 pr을 올리는게 아닙니다. 추후에 리뷰를 다시해야하면 이중으로 일을 만드는거니까요

2024-02-19 15:55 UTC, sikkzz commented on src/components/homepages/Profile.tsx
> +				<img src="" alt="" />
빈코드로 두지 말고 샘플로 넣어주세요 pr작성할때 추후 연결 or 추가 예정이라고 적어주면 됩니다

2024-02-19 15:55 UTC, sikkzz commented on src/components/homepages/Profile.tsx
여기도 인라인 css 코드 삭제 안된거같네요

2024-02-19 15:55 UTC, sikkzz commented on src/components/homepages/Profile.tsx
> +			>
비슷하거나 동일한 로직은 간소화 시켜주세요 같은 코드 반복되는거 확인 가능하실꺼에요

2024-02-19 15:55 UTC, sikkzz commented on src/components/homepages/Habits.tsx
> +	}, [targetDate]);
api코드 주석처리하거나 제거해주세요 에러 계속 뜨는거 콘솔에서 확인 가능합니다.

무엇보다 redux toolkit 사용시 api 해당 방식으로 작성할 일 전혀 없으니 불필요하기도 합니다

2024-02-19 15:57 UTC, sikkzz commented
일부 파일들 리뷰 일부로 안했습니다. 제가 달아드린 리뷰 참고하셔서 모든 코드 한바퀴 수정하시고 리뷰해달라고 말씀해주세요. 코드량 많고 코드가 허술한 부분이 많아서 수정사항 계속 이루어질 예정입니다.

꼭 리뷰 달아드린 부분이 아니여도 그 리뷰에 대한 비슷한 수정사항이 있는지 모든 파일에서 확인 한번 해보시는게 좋을 거 같습니다

2024-02-20 05:38 UTC, youngTkim commented on src/components/homepages/Advices.tsx
> +							<img src={image}></img>
혹시 alt값은 따로 어떻게 설정하시나요?

2024-02-27 06:18 UTC, sikkzz requested changes

2024-02-27 06:18 UTC, sikkzz commented on src/App.tsx
> +				<Route path="/star/:id" element={<StarCardDetailPage />} />
리베이스 하실떄 코드 잘 확인하면서 해주세요 star/:id 라우팅 중복된거 보이시죠?

2024-02-27 06:18 UTC, sikkzz commented on src/components/Home/Advices.tsx
> +				})}
리뷰 드렸었는데 map에서 "{" 말고 "(" 사용하면 return문 제거 가능하다고 말씀 드렸습니다. 꼼꼼히 확인해주세요

2024-02-27 06:18 UTC, sikkzz commented on src/components/Home/Advices.tsx
> +						<li css={advicesStyle.adviceWrapper} key={image.src}>
여기 인라인 스타일링이 사라지겠죠?

2024-02-27 06:18 UTC, sikkzz commented on src/components/Home/Advices.style.ts
<img width="535" alt="스크린샷 2024-02-26 오후 6 49 41" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/4a78434f-7da4-459e-b932-9b83771b531a">

해당 파일 제가 주석한 부분 다 불필요 코드 아닌가요? 제거시에도 변화가 없습니다. 앞으로 작성하실때도 무작정 넣지 마시고 하나씩 넣으면서 차이점 확인하면서 넣어주세요 제가 처음 리뷰드릴때부터 말씀드렸는데 불필요코드가 엄청 많습니다.

2024-02-27 06:18 UTC, sikkzz commented on src/components/Home/Advices.tsx
<img width="524" alt="스크린샷 2024-02-26 오후 6 58 14" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/51463c51-164f-4dc1-b6cd-f370a9c2b3b0">

이렇게 하면 옵셔널 체이닝 삭제 가능합니다. 옵셔널 체이닝을 아무때나 쓰면 디버깅 과정에서 어려움이 높아질 수 있어요

2024-02-27 06:18 UTC, sikkzz commented on src/components/Home/Calender.style.ts
> +		background-color: ${props.isSelected ? "rgba(1, 118, 249, 0.1)" : "none"};
props 지칭 불필요합니다

2024-02-27 06:18 UTC, sikkzz commented on src/components/Home/Calender.style.ts
> +		background-color: ${props.isSelected ? "rgba(1, 118, 249, 0.1)" : "none"};
background-color는 default 값 transparent에요 none 코드 굳이 필요 없지 않나요?

2024-02-27 06:18 UTC, sikkzz commented on src/components/common/Header/Header.style.ts
rebase 오류 코드 존재

2024-02-27 09:00 UTC, sikkzz requested changes

2024-02-27 09:00 UTC, sikkzz commented on src/components/Home/Calender.style.ts
<img width="502" alt="스크린샷 2024-02-27 오후 5 25 37" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/c3d2e909-3de8-4e0d-88be-408ea260bfaf">
<img width="459" alt="스크린샷 2024-02-27 오후 5 25 40" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/bbc1d2e0-9ab5-4c96-ac9f-d1dab7fe402c">
<img width="261" alt="스크린샷 2024-02-27 오후 5 25 44" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/520912f4-0364-4afb-a3d7-4858fb0b6dd8">
<img width="210" alt="스크린샷 2024-02-27 오후 5 25 46" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/e134ed25-5a08-4982-8920-f1dbf776d865">
<img width="358" alt="스크린샷 2024-02-27 오후 5 25 51" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/437b946c-4f1f-469b-a281-6c56b939479e">

수정 가능합니다

2024-02-27 09:00 UTC, sikkzz commented on src/components/Home/Habits.style.ts
> +	habitWrapper: ({ status }: habitStyleStatus) => css`
여기도 위랑 동일하게 수정

2024-02-27 09:00 UTC, sikkzz commented on src/components/Home/Calender.tsx
> +								key={`${year}.${month}.${date}`}
여기도 꼭 내부 로직이여야 하나요? map에서 리턴문도 그렇고요

2024-02-27 09:00 UTC, sikkzz commented on src/components/Home/Calender.tsx
> +	};
얘는 인라인으로 적을 수 있을 거같네요

2024-02-27 09:00 UTC, sikkzz commented on src/components/Home/HabitCheckModal/HabitCheckModal.style.ts
스타일링 방식을 꼭 이렇게 할 이유가 있을까요? 인라인 css 네이밍이 상당히 길어진다는 단점이 있을텐데요

2024-02-27 09:00 UTC, sikkzz commented on src/components/Home/Advices.tsx
<img width="375" alt="스크린샷 2024-02-27 오후 5 32 30" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/046ebeaa-a96d-4ab7-9a18-3b006f2c3250">

보시면 짤립니다.. 확인하시면서 수정해주세요 제발ㅠ

2024-02-27 09:18 UTC, khkh0109 commented
저희 우선 가로 길이를 360px로 제한하기로 했는데 이 부분은 나중에 추가할 예정일까요?

2024-03-01 00:52 UTC, pizzaYami approved these changes

2024-03-01 01:24 UTC, pizzaYami requested changes

2024-03-01 01:24 UTC, pizzaYami commented on src/components/Home/Landing/Profile/Profile.style.ts
> +		height: 2.5rem;
![스크린샷 2024-03-01 오전 10 11 09](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/88d5b1e1-fba6-4c7d-924a-137adbbbc3f5)
이미지가 짤려서 크기 조정이 필요하겠네요

2024-03-01 01:24 UTC, pizzaYami commented on src/components/Home/Landing/Advices/Advices.tsx
> +					</li>
![스크린샷 2024-03-01 오전 10 14 14](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/9a9827b3-c9ce-4edd-91b0-02b496b82bf5)
몇 번째 배너를 띄우고 있는지 보여주는 게 필요하겠네요

2024-03-01 01:58 UTC, pizzaYami requested changes

2024-03-01 01:58 UTC, pizzaYami commented on src/components/Home/Landing/Profile/Profile.style.ts
> +			${theme.font.body_b_bold}
head_c 같네요

2024-03-01 01:58 UTC, pizzaYami commented on src/components/Home/Landing/Profile/Profile.tsx
> +			<ProfileButtonIcon onClick={() => navigate("/habitgenerate")} />
요런 방식은 처음보는거 같은데 이렇게 사용하는건 준식님한테 배우신건가요?

2024-03-01 01:58 UTC, pizzaYami commented on src/components/Home/Landing/HabitHelp.tsx
> +	background-color: ${theme.color.line};
color.line이 아니라 color.bg 같네요

2024-03-01 01:58 UTC, pizzaYami commented on src/components/Home/Landing/HabitHelp.tsx
> +	}
& > span 제거하고 ${theme.font.body_b}만 넣어도 됩니다.

2024-03-01 01:58 UTC, pizzaYami commented on src/components/Home/Landing/Calendar/Calender.style.ts
> +		background-color: ${isSelected && "rgba(1, 118, 249, 0.1)"};
rgba 형식보단 # 형식을 많이 사용합니다.

2024-03-01 01:58 UTC, pizzaYami commented on src/components/Home/Landing/Calendar/Calender.style.ts
> +		height: 80px;
px제거

2024-03-01 01:58 UTC, pizzaYami commented on src/components/Home/Landing/Calendar/Calender.style.ts
> +					height: 24px;
px

2024-03-01 02:24 UTC, youngTkim commented on src/components/Home/Landing/Calendar/Calender.style.ts
> +		background-color: ${isSelected && "rgba(1, 118, 249, 0.1)"};
이거는 피그마에서보니까 mainblue값에 알파값 변화를 주셔서 이렇게 표현했슴다

2024-03-01 04:44 UTC, pizzaYami requested changes

2024-03-01 04:44 UTC, pizzaYami commented on src/components/Home/Landing/Calendar/Calender.style.ts
> +		background-color: ${isSelected && "rgba(1, 118, 249, 0.1)"};
"rgba(1, 118, 249, 0.1)" -> #E6F1FE
rgba쓰는거 거의 본적이 없어요.
아니면 mainblue에 opacity: 10%넣는 방법도 있습니다.

2024-03-01 05:11 UTC, youngTkim commented on src/components/Home/Landing/Calendar/Calender.style.ts
> +		background-color: ${isSelected && "rgba(1, 118, 249, 0.1)"};
opacity 10퍼%넣으면 글자도 흐려져서 색상값으로 수정한다음 넣겠습니다

2024-03-01 12:54 UTC, khkh0109 commented on src/components/common/Gnb/Gnb.style.ts
> +		gap: 54px;
dev에 있는 Gnb 컴포넌트 스타일과 코드가 다른데 확인 부탁드려요~

2024-03-01 15:50 UTC, khkh0109 commented on src/components/Home/Landing/Calendar/Calender.style.ts
> +		border-radius: 8px;
피그마 보면 여기 border-radius가 10px인 것 같은데 확인 부탁드려요~

2024-03-01 15:56 UTC, khkh0109 commented on src/components/Home/Landing/Profile/Profile.style.ts
> +		border-radius: 4px;
피그마 border-radius와 값이 달라요 피그마에는 5px로 되어있는데 확인 부탁드려요~

2024-03-01 16:04 UTC, khkh0109 commented on src/components/Home/Landing/HabitList/HabitList.style.ts
> +				font-size: 0.6875rem;
피그마 보면 xsmall 사이즈 폰트로 사용되었습니다. theme font에 body_xs 값 있으니 이걸로 교체하면 될 것 같아요

2024-03-01 16:06 UTC, khkh0109 commented on src/components/Home/Landing/HabitList/HabitList.style.ts
> +		border-radius: 20px;
이 부분도 피그마에서는 15px로 되어있는데 확인 부탁드려요~

2024-03-01 16:19 UTC, khkh0109 commented on src/components/Home/Landing/Calendar/Calender.style.ts
> +		background-color: ${isSelected && "#E6F1FE"};
해당 배경 컬러 theme color에 main_light_blue라는 이름으로 있습니다. 맞는지 확인해 보시고 교체 부탁드려요~

2024-03-03 16:29 UTC, sikkzz commented
리베이스하다가 꼬이실까봐 제가 리베이스 해드렸습니다. 코드량이 많은데 중간에 리베이스 땡기시니 코드량은 더 늘어나고 무엇보다 리베이스하다 꼬이면 커밋 히스토리가 꼬입니다. 보시면 TS-4번 커밋말고 다른부분도 들어가있는거 보이실거에요 리베이스 때문에 그렇습니다.

리베이스는 리뷰 다 받고 수정 끝낸 다음에 머지 직전에 해야 합니다. 또한 불가피하게 dev에서 받아와야 할 코드가 있다면 거기서 작업을 멈추고 하던 부분까지 dev에 pr 올려서 머지 받은 후 다른 브랜치에서 작업 시작해야 합니다. 참고 부탁드려요

문제 없으시면 확인하시고 머지하면 됩니다.

2024-03-03 16:30 UTC, sikkzz approved these changes

2024-03-04 01:27 UTC, pizzaYami approved these changes

2024-03-04 01:30 UTC, merged