[Ts-250] Feat CommonButton
ConnectingStar/ConnectingStar-Front pull request #29
Opened 2024-02-15 08:46 UTC by pizzaYami

[JIRA](https://m2jun.atlassian.net/browse/TS-250)

## 💡 변경사항 & 이슈
공통적으로 사용되는 하단 버튼을 제작하였습니다.

<br>

## ✍️ 관련 설명

text: 기본 버튼 텍스트
leftText: 사이드 버튼 텍스트
isSquare: 버튼 모양 (default : round)
disabled: 버튼 비활성화(blur)
isTransparent : 배경 투명하게 (default: white)
isPositionStatic : position: fixed 제거 (모달에 사용시)
handleBtnClick : 우측버튼 onclick
handleLeftBtnClick : 좌측버튼 onclick

isSquare, isPositionStatic 경우에는 width가 100%로 좌우로 다 붙습니다.
기본 widht는 360px로 잡았습니다.
<br>

## ⭐️ Review point
position: fixed를 사용했는데 모달에 넣는 경우 이상이 생기지 않는지.

<br>

## 📷 Demo

![스크린샷 2024-02-15 오후 5 41 40](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/15127cfa-f29c-4170-acfc-ac61aacb4d4b)

![스크린샷 2024-02-15 오후 5 41 56](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/6054366a-7465-4c6c-95f0-49ec42b7f435)

![스크린샷 2024-02-15 오후 5 42 21](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/f3138bd1-0796-4a02-b24a-3002285b50d6)

![스크린샷 2024-02-15 오후 5 42 45](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/16c7b089-a297-4933-98c9-7ef7e9915747)

![스크린샷 2024-02-15 오후 5 43 12](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/3bc5d262-2110-41c4-9d6b-ea40fd68625f)

![스크린샷 2024-02-15 오후 5 43 17](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/8f1dd5eb-f446-4a92-b3e3-f0a4eb867439)

![스크린샷 2024-02-15 오후 5 43 28](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/cf27296f-ecaf-402e-999f-997598086fa8)

2024-02-15 09:35 UTC, sikkzz commented
아마 오늘 회의에서 width에 대한 얘기 진행할 거 같은데 해당 회의 이후에 리뷰 진행할게요!

2024-02-16 11:46 UTC, sikkzz requested changes

2024-02-16 11:46 UTC, sikkzz commented on src/components/common/FooterBtn/FooterBtn.tsx
> +export default function FooterBtn({ text, cancleText, shape, blur, transparent }: FooterBtnType) {
blur prop및 스타일링은 필요 없어보입니다. 버튼 배경색이 다른 부분들은 제가보기에는 disabled 상태 때문에 존재하는거 같은데 disabled 처리를 추가하고 스타일링도 disabled에 맞춰서 하는게 맞아보입니다. disabled prop도 하나 필요하겠네요. 사용되는 컴포넌트마다 disabeld 조건이 다를테니

2024-02-16 11:46 UTC, sikkzz commented on src/components/common/FooterBtn/FooterBtn.tsx
> +export default function FooterBtn({ text, cancleText, shape, blur, transparent }: FooterBtnType) {
transparent prop도 필요한건가요? 예시에서 투명색 배경에 버튼은 찾지 못한거 같아서요

불필요라면 삭제해주세요

2024-02-16 11:46 UTC, sikkzz commented on src/components/common/FooterBtn/FooterBtn.tsx
> +export default function FooterBtn({ text, cancleText, shape, blur, transparent }: FooterBtnType) {
[시안](https://www.figma.com/file/deVOGLOqzbCjKJP9fDeB3i/%EC%BB%A4%EB%84%A5%ED%8C%85%EC%8A%A4%ED%83%80?type=design&node-id=5228-9404&mode=dev)을 모두 확인해봤을 때 왼쪽 버튼이 꼭 취소 버튼으로만 사용되는건 아닌거 같네요 

그렇기에 cancelText prop 명칭으로 사용하는게 그리 좋아보이지는 않아요. cancle로 오타나기도 했네요

2024-02-16 11:46 UTC, sikkzz commented on src/components/common/FooterBtn/FooterBtn.tsx
> +			) : null}
{cancelText && (컴포넌트)

2024-02-16 11:53 UTC, sikkzz commented
바텀 시트 팝업 모달에 넣어도 안깨지긴 합니다. 
다만 fixed 처리인 경우 모든 케이스에서 이 버튼의 공간만큼 여백을 줘야지 모달에서 컴포넌트 요소들이 안깨지고 정상으로 보입니다. (모든 코드의 여백 코드가 추가되는거니 그렇게 좋은 부분은 아닐 수 있습니다)

저였으면 공통 컴포넌트를 다른 방법으로 제작했을 거 같아요 이건 제 의견이니 적용시키셔도 되고 그냥 이대로 진행하셔도 됩니다. 다만 이후에 리팩토링 여지는 남아있기에 1차 스프린트 이후 제가 손댈 가능성이 높을 거 같네요

1. Footer 버튼만이 아닌 전체 버튼 컴포넌트 공통화 (이 방법은 쉽지는 않으실거에요. 다만 해놓은다면 나중에 편리하긴 합니다)

2. Footer 버튼만 공통화 하신다면 저라면 버튼 1개만 공통화 시켰을 거 같아요. 취소 버튼과 확인 버튼 구분 없이 하나로 통일하고 배경색, 글자색, 버튼 모양, 버튼 텍스트 이정도를 prop으로 받을 수 있겠죠? 그리고 이외의 추가 스타일링이나 설정은 해당 컴포넌트에서 사용할 때 커스텀해서 사용했을 거 같네요. 이 방식으로 한다면 꼭 fix로 바텀에 붙어있는 버튼이 아니니 다른 곳에서도 사용할 수 있고 버튼 컴포넌트 위치 조정들도 안해줘도 되서 코드도 더 줄어들테구요 (bottom, fixed, left, transform 등의 코드)

개인 견해이니 한번 읽어보시면 좋을 거 같아요. 수정의 여부는 관여하지 않겠습니다. 만약 수정하신다해도 공통 컴포넌트 제작으로 인해 다른 레이아웃 제작이 느려지면 곤란하니까요

2024-02-16 11:54 UTC, sikkzz commented
> 바텀 시트 팝업 모달에 넣어도 안깨지긴 합니다. 다만 fixed 처리인 경우 모든 케이스에서 이 버튼의 공간만큼 여백을 줘야지 모달에서 컴포넌트 요소들이 안깨지고 정상으로 보입니다. (모든 코드의 여백 코드가 추가되는거니 그렇게 좋은 부분은 아닐 수 있습니다)
> 
> 저였으면 공통 컴포넌트를 다른 방법으로 제작했을 거 같아요 이건 제 의견이니 적용시키셔도 되고 그냥 이대로 진행하셔도 됩니다. 다만 이후에 리팩토링 여지는 남아있기에 1차 스프린트 이후 제가 손댈 가능성이 높을 거 같네요
> 
> 1. Footer 버튼만이 아닌 전체 버튼 컴포넌트 공통화 (이 방법은 쉽지는 않으실거에요. 다만 해놓은다면 나중에 편리하긴 합니다)
> 2. Footer 버튼만 공통화 하신다면 저라면 버튼 1개만 공통화 시켰을 거 같아요. 취소 버튼과 확인 버튼 구분 없이 하나로 통일하고 배경색, 글자색, 버튼 모양, 버튼 텍스트 이정도를 prop으로 받을 수 있겠죠? 그리고 이외의 추가 스타일링이나 설정은 해당 컴포넌트에서 사용할 때 커스텀해서 사용했을 거 같네요. 이 방식으로 한다면 꼭 fix로 바텀에 붙어있는 버튼이 아니니 다른 곳에서도 사용할 수 있고 버튼 컴포넌트 위치 조정들도 안해줘도 되서 코드도 더 줄어들테구요 (bottom, fixed, left, transform 등의 코드)
> 
> 개인 견해이니 한번 읽어보시면 좋을 거 같아요. 수정의 여부는 관여하지 않겠습니다. 만약 수정하신다해도 공통 컴포넌트 제작으로 인해 다른 레이아웃 제작이 느려지면 곤란하니까요

수정 여부에 따라 위에 작성한 코드 리뷰들이 불필요할 수 있으니 참고 바랍니다. 코드 리뷰는 현 상태 유지 조건으로 리뷰 달아드린거라서요!

2024-02-18 07:01 UTC, pizzaYami commented on src/components/common/FooterBtn/FooterBtn.tsx
> +export default function FooterBtn({ text, cancleText, shape, blur, transparent }: FooterBtnType) {
disabled 처리가 입력을 해야되서 버튼이 흐리게 되는 부분을 말씀하신건가요?
맞다면 blur로 명명해서 props로 넣어놓은건데 disabled 명칭이 맞는거 같네요
아니라면 설명부탁드립니다

2024-02-18 07:05 UTC, pizzaYami commented on src/components/common/FooterBtn/FooterBtn.tsx
> +export default function FooterBtn({ text, cancleText, shape, blur, transparent }: FooterBtnType) {
버튼 배경이 기본적으로 흰색으로 하여 스크롤시 깔끔해보이도록하고

아래와 같은 상황에서는 투명배경이 필요할 것 같아서 넣어놨습니다.
![스크린샷 2024-02-18 오후 4 04 32](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/7f89cb7c-3a08-4667-a0aa-9c2bc9321da4)

2024-02-18 07:17 UTC, pizzaYami commented on src/components/common/FooterBtn/FooterBtn.tsx
> +export default function FooterBtn({ text, cancleText, shape, blur, transparent }: FooterBtnType) {
sideBtnText로 변경했는데 이름 괜찮나요?

2024-02-18 07:49 UTC, sikkzz commented on src/components/common/FooterBtn/FooterBtn.tsx
> +export default function FooterBtn({ text, cancleText, shape, blur, transparent }: FooterBtnType) {
알고계시겠지만 button tag에 기본으로 제공되는 disabled prop이 있습니다. disabled 상태에서의 스타일링도 &:disabled 선택자 사용해서 따로 가능하고요 

제가 생각하기에는 디자이너분이 버튼 배경색을 흐리게 해놓은 부분들이 disabled 처리일때를 표현하신거 같은데 보통 버튼색이 동일하면 disabled 상태의 버튼색도 동일합니다. 그렇기에 해당 버튼 prop을 blur가 아닌 disabled로 바꾸고 버튼 컴포넌트 사용시 disabled 조건을 prop으로 넘겨주는 방향성을 말씀드린겁니다. blur prop보다 훨씬 직관적일테니까요

이해가 안가시면 말씀해주세요 코드 예시로 보여드릴게요

2024-02-18 07:50 UTC, pizzaYami commented on src/components/common/FooterBtn/FooterBtn.tsx
> +export default function FooterBtn({ text, cancleText, shape, blur, transparent }: FooterBtnType) {
아 이해했습니다.
disabled를 까먹고있었네요.
반영해서 push할게요

2024-02-18 08:01 UTC, sikkzz commented on src/components/common/FooterBtn/FooterBtn.tsx
> +export default function FooterBtn({ text, cancleText, shape, blur, transparent }: FooterBtnType) {
현재 구성처럼 버튼만이 아닌 버튼 배경의 일정 공간들을 컴포넌트로 사용하는거기 때문에 배경색을 흰색으로 구분하면 아래처럼 구분선이 생기게 됩니다. prop 제거하고 배경색도 그냥 제거하면 default 값이 transparent이기 때문에 정상으로 보이고 사용하는 컴포넌트에서 배경색 조정해야 하지 않을까 싶네요

결론적으로는 불필요가 맞아보인다는 의견입니다.

<img width="402" alt="스크린샷 2024-02-18 오후 4 59 21" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/e1c814fa-f657-47b6-8248-0f697c826de7">

2024-02-18 08:33 UTC, sikkzz requested changes

2024-02-18 08:33 UTC, sikkzz commented on src/components/common/FooterBtn/FooterBtn.Style.ts
> +			background-color: ${theme.color.main_Blue};
main blue 테마 수정

2024-02-18 08:33 UTC, sikkzz commented on src/components/common/FooterBtn/FooterBtn.Style.ts
> +		width: 22.5rem;
width 100%가 맞습니다. 바텀 시트 팝업은 360으로 제한 하면 영역이 짤려요

2024-02-18 08:35 UTC, sikkzz commented on src/components/common/FooterBtn/FooterBtn.tsx
> +export default function FooterBtn({ text, cancleText, shape, blur, transparent }: FooterBtnType) {
side vs left 골라 쓰시면 될 거 같아요! 저는 left 생각했던거 같아요

2024-02-18 08:36 UTC, sikkzz commented on src/components/common/FooterBtn/FooterBtn.tsx
> +export default function FooterBtn({ text, cancleText, shape, blur, transparent }: FooterBtnType) {
onClick prop도 결정하신 부분에 통일해서 부탁드려요!

2024-02-18 08:38 UTC, sikkzz requested changes

2024-02-18 08:38 UTC, sikkzz commented on src/components/common/FooterBtn/FooterBtn.Style.ts
> +		${positionStatic ? null : "position: fixed;bottom: 0;left: 50%;	transform: translateX(-50%);"}
${!positionStatic && 로 동작 가능하지 않을까요?

2024-02-19 05:38 UTC, youngTkim approved these changes, later dismissed

2024-02-19 13:06 UTC, sikkzz submitted a review, later dismissed

2024-02-19 15:58 UTC, sikkzz commented
rebase 해보셔야 할 거 같네요 그리고 eslint 작동 안하는거 같은데 아닌가요?

2024-02-20 03:57 UTC, khkh0109 commented
궁금한 점이 있어서 질문 드립니다. 

<img width="312" alt="스크린샷 2024-02-20 오후 12 40 24" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/5e6a9988-35c6-474e-b41c-0b41afc81c59">

위 사진처럼 가로로 긴 형태의 버튼은 항상 가로로 쭉 늘어나는 건가요? 
starDetail 페이지는 360px로 고정해둔 상태인데 여기에 버튼을 넣으니까 사진처럼 버튼만 길어져서 이렇게 되는게 맞는지 확인차 질문드립니다. 

저는 디자인 시안을 보고 내용물과 버튼 가로 사이즈가 항상 동일한 형태라고 이해 했거든요 (아래 사진처럼)
만약 아니라면 이대로 가도 괜찮습니다~

<img width="312" alt="스크린샷 2024-02-20 오후 12 49 37" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/8f7d7d38-823f-4415-a6a1-5d557794e618">

2024-02-20 04:23 UTC, khkh0109 commented on src/components/common/FooterBtn/FooterBtn.Style.ts
> +		padding: ${!isSquare && "0 1.5rem"};
height가 버튼 배경 영역 때문에 잡은것 맞을까요? 
맞다면 이 부분을 padding으로만 할 수 있을것 같은데 어떤가요? 
아래처럼 사각형이 아닐때만 사방에 패딩을 주면 height가 없어도 동일하더라구요 
```suggestion
		padding: ${!isSquare && "1rem 1.5rem"};
```

2024-02-21 03:02 UTC, pizzaYami commented on src/components/common/FooterBtn/FooterBtn.Style.ts
> +		padding: ${!isSquare && "0 1.5rem"};
padding만 주는 방법도 있군여
수정했습니다.

2024-02-21 03:04 UTC, pizzaYami commented
isSquare, isPositionStatic 경우에는 width가 100%로 좌우로 다 붙습니다.
기본 widht는 360px로 잡았습니다.

2024-02-21 11:25 UTC, youngTkim approved these changes, later dismissed

2024-02-21 12:58 UTC, sikkzz approved these changes, later dismissed

2024-02-21 13:06 UTC, khkh0109 approved these changes, later dismissed

2024-02-21 20:28 UTC, merged