[Ts-144] OnboardingChatting에 들어가는 SelectTagModal
ConnectingStar/ConnectingStar-Front pull request #37
Opened 2024-02-21 10:30 UTC by pizzaYami

[JIRA-144](https://m2jun.atlassian.net/browse/TS-144)

## 💡 변경사항 & 이슈
OnbardingChatting에 태그선택에 필요한 모달 컴포넌트제작
<br>

## ✍️ 관련 설명
/chat 에 들어가 확인가능
태그또는 인풋 선택시 배경이 변하는지
배경변한 부분이 제대로 전송이 되는지 (console.log에 뜸)

<br>

## ⭐️ Review point
태그
코드가 너무 지저분한거 같아서 컴포넌트화를 해야할까요?
onclick에 들어가는 내용 함수로 빼서 넣었는데 괜찮은지
input focus시 width가 유지된 상태로 하단에 붙는데 width를 100%할지 고민
<br>

## 📷 Demo
![스크린샷 2024-02-21 오후 7 30 27](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/5733e2ee-18d2-4636-bbb1-4fa0c530f9db)

2024-02-21 12:59 UTC, sikkzz commented
250 브랜치 머지 되면 리뷰할게요 250 금방 리뷰 될 거 같아서!

2024-02-21 13:02 UTC, youngTkim approved these changes, later dismissed

2024-02-22 04:51 UTC, khkh0109 commented
전체적으로 다 보면 되는건가요? 아니면 TS-144 관련 코드만 보면 될까요?

2024-02-22 05:20 UTC, sikkzz commented
rebase 해주시면 250번 관련 코드 사라질거 같은데 rebase 부탁드려요

2024-02-22 12:30 UTC, sikkzz requested changes

2024-02-22 12:30 UTC, sikkzz commented on src/App.tsx
> +import ChatPage from "./pages/ChatPage";
절대 경로

2024-02-22 12:30 UTC, sikkzz commented on src/components/Chat/SelectTagModal.style.ts
> +			flex-direction: row;
row가 default value라 없어도 됩니다

2024-02-22 12:30 UTC, sikkzz commented on src/components/Chat/SelectTagModal.style.ts
> +			justify-content: center;
gap 6px 넣으면 아래 margin 코드 제거 가능할 거 같네용

2024-02-22 12:30 UTC, sikkzz commented on src/components/Chat/SelectTagModal.style.ts
> +				margin: 0 6px 6px 0;
제거

2024-02-22 12:30 UTC, sikkzz commented on src/components/Chat/SelectTagModal.style.ts
> +				max-width: 8.125rem;
width 95px로 고정해야 할 거 같아요 현재 상태에서는 사이즈에 따라 깨집니다. 그리고 태그 글자 제한 수가 없다면 긴 글자들의 태그는 어떻게 할지 논의해보시면 좋을 거 같아요

<img width="495" alt="스크린샷 2024-02-22 오후 8 59 23" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/82147ee1-fbaf-4019-af5e-3990b1784ef7">

2024-02-22 12:30 UTC, sikkzz commented on src/components/Chat/SelectTagModal.style.ts
> +				white-space: nowrap;
두개다 현재 상태에서는 불필요한 코드에요

2024-02-22 12:30 UTC, sikkzz commented on src/components/Chat/SelectTagModal.style.ts
> +			margin-top: 14px;
시안 확인해보시면 20px입니다 그리고 rem

2024-02-22 12:30 UTC, sikkzz commented on src/components/Chat/SelectTagModal.tsx
> +import Header from "../common/Header/Header";
절대 경로

2024-02-22 12:30 UTC, sikkzz commented on src/components/Chat/SelectTagModal.tsx
> +	};
한줄짜리 함수는 인라인에 넣는게 낫지 않을까요?

2024-02-22 12:30 UTC, sikkzz commented on src/components/Chat/SelectTagModal.tsx
> +	};
여기도요

2024-02-22 12:30 UTC, sikkzz commented on src/pages/ChatPage.style.ts
> +		margin: 12px 0;
rem

2024-02-22 12:31 UTC, sikkzz commented
<img width="507" alt="스크린샷 2024-02-22 오후 8 58 59" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/9e9f50fc-1b54-42ad-9249-d85f033b4d69">

버튼 확인해보시면 구분선 생깁니다

2024-02-22 12:32 UTC, sikkzz commented
chat page 쪽 코드는 혹시 리뷰 해드려야 하나요? 브랜치가 잘못 연동된거 같은데 나중에 chat page pr에서 리뷰하는게 낫지 않을까 싶어서요

2024-02-22 22:32 UTC, pizzaYami commented
chat page쪽 코드는 나중에 PR올리면 부탁드릴게여

2024-02-23 00:50 UTC, pizzaYami commented
![스크린샷 2024-02-23 오전 9 50 22](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/aefc0aa9-1e9e-48e2-a02f-3d3ccf4f81aa)
저는 안 생기는데 다른 분들은 어떠신가여?

2024-02-23 05:56 UTC, sikkzz commented
> ![스크린샷 2024-02-23 오전 9 50 22](https://private-user-images.githubusercontent.com/116322645/307196995-aefc0aa9-1e9e-48e2-a02f-3d3ccf4f81aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NjgwNzMsIm5iZiI6MTcwODY2Nzc3MywicGF0aCI6Ii8xMTYzMjI2NDUvMzA3MTk2OTk1LWFlZmMwYWE5LTFlOWUtNDhlMi1hMDJmLTNkM2NjZjRmODFhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QwNTU2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDc4NGYyMjQ4YTdhZDM3YWQ4YTdjOTVlMmU4NDliNDIxY2MyOGVlN2FhNWIyOTE2YTA5ZTgwZGI3MmE3Y2UwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H62Msv6kZt9AREfibBPewjFe9jOYYkayjGrG6XyuCm8) 저는 안 생기는데 다른 분들은 어떠신가여?

witdh 360이신 상태라 그런거 아니에요? 디바이스 witdh 한번 늘려보실래요

2024-02-23 08:32 UTC, khkh0109 commented
> ![스크린샷 2024-02-23 오전 9 50 22](https://private-user-images.githubusercontent.com/116322645/307196995-aefc0aa9-1e9e-48e2-a02f-3d3ccf4f81aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NzY5NTcsIm5iZiI6MTcwODY3NjY1NywicGF0aCI6Ii8xMTYzMjI2NDUvMzA3MTk2OTk1LWFlZmMwYWE5LTFlOWUtNDhlMi1hMDJmLTNkM2NjZjRmODFhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QwODI0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzA5Mzc1NWI4ZjA4OGM5ZDViYzVkMDM0NzAwYTg2MWM2M2U5ZGViY2QyNTc1YzExN2JiZDJiYTJjZDY2NzA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eEHrRrtwFn05GuaWFHHc1ml9_7EeNGRWKsdzBxXaPDU) 
저는 안 생기는데 다른 분들은 어떠신가여?

저는 처음에는 보였는데 새로고침 하니까 사라졌어요

2024-02-23 08:35 UTC, khkh0109 commented
<img width="424" alt="스크린샷 2024-02-23 오후 5 34 40" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/eebc988d-626f-49d7-8cf9-4997feb02e7e">

입력할때 배경이 파란색으로 바뀌네요..!

2024-02-24 09:00 UTC, sikkzz commented
<img width="368" alt="스크린샷 2024-02-24 오후 6 00 29" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/bd9d760b-d78b-4267-95c5-689359d956eb">

저는 여전히 생기는거로 확인되네요

2024-02-26 11:48 UTC, sikkzz commented on src/components/Chat/SelectTagModal.style.ts
> +				max-width: 8.125rem;
이거 회의에서 얘기해봤는데 위 텍스트들 변동이 없을 예정이라 95px 고정에 정렬만 맞추시면 될 거 같아요!

2024-02-28 20:48 UTC, pizzaYami commented
줄 생기는 거는 어떻게 해결을 해야할 지 모르겠는데 나중에 배포해보고 문제있으면 수정할까요? #

2024-02-28 23:13 UTC, pizzaYami commented
> <img alt="스크린샷 2024-02-23 오후 5 34 40" width="424" src="https://private-user-images.githubusercontent.com/77181642/307262807-eebc988d-626f-49d7-8cf9-4997feb02e7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNjE3NDYsIm5iZiI6MTcwOTE2MTQ0NiwicGF0aCI6Ii83NzE4MTY0Mi8zMDcyNjI4MDctZWViYzk4OGQtNjI2Zi00OWQ3LThjZjktNDk5N2ZlYjAyZTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDIzMDQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3Mjk0YTcyMjhmMDc1MTgyZjQ2ZTQ0NTdhNGNmMGE1NjZmOWY4NDgwY2RmODMwMWNlMjgzNjdhYThjYThhYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9dU7U02KoiAEF0yFCObW7CXLR4V7f7-EuHi6MBjomgk">
> 입력할때 배경이 파란색으로 바뀌네요..!
> 
> PR에 있는 내용이었군요 😅 이건 테스트용이라 배경이 파란색으로 바뀌는건가요?

변경했습니다

2024-02-29 13:34 UTC, sikkzz requested changes

2024-02-29 13:34 UTC, sikkzz commented on src/components/Chat/SelectTagModal.style.ts
> +				max-width: 8.125rem;
max-width는 빼는게 맞는 거 같아요

2024-02-29 13:34 UTC, sikkzz commented on src/components/Chat/SelectTagModal.style.ts
> +		padding: 1.25rem 1.5rem 1rem 1.5rem;
padding: 1.25rem 1.5rem 1rem으로 수정해주세요

2024-02-29 13:35 UTC, sikkzz requested changes

2024-02-29 13:35 UTC, sikkzz commented on src/components/Chat/SelectTagModal.tsx
> +					}}
여기 isTransparent prop주면 구분선 사라지긴 합니다

2024-03-05 21:17 UTC, sikkzz requested changes

2024-03-05 21:17 UTC, sikkzz commented on src/App.tsx
> +				<Route path="/chat" element={<ChatPage />} />
잘못들어간거 같네요

2024-03-05 21:17 UTC, sikkzz commented on src/components/Chat/SelectTagModal.style.ts
<img width="516" alt="스크린샷 2024-03-06 오전 6 15 57" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/571c8bf7-ddc1-4d00-861c-e9ae519d460b">
<img width="533" alt="스크린샷 2024-03-06 오전 6 15 59" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/338aa045-ea16-4af4-9e04-28f7c53e37db">

제가보기에는 위 코드가 더 시안에 알맞는 코드가 아닌가 싶습니다.

현재는 글자가 긴 태그가 생기면 아래 사진처럼 변합니다.

<img width="433" alt="스크린샷 2024-03-06 오전 6 15 35" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/620c8779-5ae3-4eb6-a66f-2b2b89af7114">

2024-03-06 12:16 UTC, khkh0109 commented
input에 값 입력하고 '선택' 버튼 누르면 input 배경이 파란색으로 되는데 이 부분은 원래 이렇게 되는건가요? 

<img width="230" alt="스크린샷 2024-03-06 오후 9 15 15" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/a37c1b65-910f-41ce-9a1f-dcf27b039bf8">

2024-03-07 12:53 UTC, youngTkim submitted a review, later dismissed

2024-03-07 20:26 UTC, sikkzz requested changes

2024-03-07 20:26 UTC, sikkzz commented on src/components/Chat/SelectTagModal.style.ts
>  				height: 3.438rem;
이 코드도 없어도 동일합니다

2024-03-10 08:41 UTC, sikkzz approved these changes

2024-03-10 10:13 UTC, sikkzz requested changes

2024-03-10 10:13 UTC, sikkzz commented on src/components/Chat/SelectTagModal.tsx
> +					disabled={inputText === "" ? true : false}
{inputText === ""}

2024-03-10 10:17 UTC, sikkzz requested changes

2024-03-10 10:17 UTC, sikkzz commented on src/components/Chat/SelectTagModal.tsx
> +					disabled={selectedTag || inputText !== "" ? false : true}
얘도 뒤에 조건 없애주세요 disabled prop은 해당 조건이 트루일때 disabled처리입니다

2024-03-10 10:17 UTC, sikkzz commented on src/components/Chat/SelectTagModal.tsx
> +						onBlur={() => setIsInputFocus(false)}
불필요 옵션 아닌가요?

2024-03-10 10:18 UTC, sikkzz commented
작동 과정에서 오류가 조금 있네요 텍스트로 말씀드리기 어려워서 내일 회의때 잠깐 말씀드릴게요!

2024-03-10 18:08 UTC, sikkzz commented
혹시 브랜치 관리간 머지 하시나요? 이 커밋이 생기면 안되는거거든요

![스크린샷 2024-03-11 오전 3 07 41](https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/72a64244-e55b-413d-a4e1-fe76f4032d1b)

2024-03-11 09:07 UTC, youngTkim approved these changes, later dismissed

2024-03-11 10:46 UTC, pizzaYami commented on src/components/Chat/SelectTagModal.style.ts
> +				max-width: 8.125rem;
![스크린샷 2024-02-23 오전 9 36 44](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/f41328ae-80fa-42d3-b5bf-af21bfea2cae)
다른 곳에서 사용해야해서 width고정은 안 했고 tag내용은 어차피 외부에 api에서 가져오는게 아니라서 넣지는 않았습니다.

2024-03-11 10:46 UTC, pizzaYami commented on src/components/Chat/SelectTagModal.style.ts
> +				white-space: nowrap;
![스크린샷 2024-02-23 오전 9 36 44](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/f41328ae-80fa-42d3-b5bf-af21bfea2cae)
요렇게 만들때 사용될 코드네요.
📷 Demo에 넣었어야 했는데 헤갈리게했네요

2024-03-11 10:46 UTC, pizzaYami commented on src/components/Chat/SelectTagModal.style.ts
> +				max-width: 8.125rem;
"스스로를 믿는", "매일 발전하는" 같은 텍스트가 있어도 95px로 고정하나요?

2024-03-11 10:46 UTC, pizzaYami commented on src/components/Chat/SelectTagModal.style.ts
세림님한테 두 개 비교해서 물어보니 기존 코드의 디자인이 더 낫다고 하셔서 수정은 안 하겠습니다.

2024-03-11 10:46 UTC, pizzaYami commented on src/components/Chat/SelectTagModal.style.ts
```
	tags: (isInputFocus: boolean) => css
		${theme.font.body_a};
		& > ul {
			display: flex;
			flex-wrap: wrap;
			justify-content: center;
			gap: 0.375rem;
			& > li {
				display: flex;
				justify-content: center;
				flex-grow: 1;
				/* white-space: nowrap; */
				background-color: ${theme.color.bg};
				border-radius: 20px;
				`height: 3.438rem;`
				padding: 1rem;
			}
		}`
```
white-space: nowrap 요거는 지우고 
height: 3.438rem; 이거 지우면 버튼이 조금 커져서 그대로 유지할게요

2024-03-11 10:46 UTC, pizzaYami commented on src/components/Chat/SelectTagModal.tsx
> +						onBlur={() => setIsInputFocus(false)}
input에 포커스 on 될때 input이 하단에 붙어야되서 필요한 옵션입니다.

2024-03-11 10:49 UTC, pizzaYami commented
> 혹시 브랜치 관리간 머지 하시나요? 이 커밋이 생기면 안되는거거든요
> 
> ![스크린샷 2024-03-11 오전 3 07 41](https://private-user-images.githubusercontent.com/100590110/311534305-72a64244-e55b-413d-a4e1-fe76f4032d1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTQzMzcsIm5iZiI6MTcxMDE1NDAzNywicGF0aCI6Ii8xMDA1OTAxMTAvMzExNTM0MzA1LTcyYTY0MjQ0LWU1NWItNDEzZC1hNGUxLWZlNzZmNDAzMmQxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQxMDQ3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDQ4NzgzNjRjOTMxNTZlYjU4OTEyOTdkZjk3MTJlZGNkNDY5YTQ3MjllMGIzYzNiZDFiOTk2ODRkMTZlYmUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gHIs8B4vFKDDuFibMUmtxws_5aXqCxRdXa4AonOytEM)

과거에 ts-25를 불러왔던적이 있는데 그거 떄문에 문제가 생긴 것 같네요

2024-03-12 11:21 UTC, sikkzz commented
변동사항 없이 동일하게 가는걸까요? 논의에서 변동이 있다면 말씀해주세요! 아니면 approve하려구요

2024-03-12 12:26 UTC, khkh0109 submitted a review, later dismissed

2024-03-12 12:47 UTC, pizzaYami commented
> 변동사항 없이 동일하게 가는걸까요? 논의에서 변동이 있다면 말씀해주세요! 아니면 approve하려구요

넵 동일하게 가기로했습니다.

2024-03-12 12:58 UTC, sikkzz commented
dev 리베이스 부탁드려요 변동사항 문제없나 확인해볼게용

2024-03-13 09:26 UTC, sikkzz submitted a review, later dismissed

2024-03-14 10:37 UTC, khkh0109 submitted a review, later dismissed

2024-03-14 11:21 UTC, youngTkim approved these changes

2024-03-14 11:21 UTC, youngTkim approved these changes, later dismissed

2024-03-15 08:43 UTC, closed without merging