[TS-267] Star 페이지 UI 추가
ConnectingStar/ConnectingStar-Front pull request #38
Opened 2024-02-21 13:25 UTC by khkh0109

[TS-267](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?selectedIssue=TS-267)

## 💡 변경사항 & 이슈
Star 페이지 UI 추가
<br>

## ✍️ 관련 설명
### 설명
Star 페이지 UI를 만들었습니다. (기능 X)
- /star 경로에서 확인할 수 있습니다. 
- StarCardDetail 페이지 라우팅은 추가하지 않았습니다. (다른 브랜치에서 작업 예정)
- 토글 transition은 다른 페이지와 동일하게 `0.5s ease`로 했습니다. (혹시 아니라면 알려주세요)

### 질문
- 카테고리 탭 항목 중 '휴식 | 취미'가 있는데 여기서 `|` 이 부분은 가상요소로 삽입하는게 나을까요? 
  이 텍스트는 스타일링의 성격이 강한 것 같아 after나 before를 사용해서 넣을지 고민이 되어서 여쭤봅니다. 

  <img width="100" alt="스크린샷 2024-02-21 오후 9 03 47" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/ff56f3b3-1962-4510-91db-a88580489fdf">

### 참고사항
> 리뷰 시 참고용도로 함께 적어둡니다. StarCard 페이지에 해당하는 부분은 아니지만 어느정도 연관 있는것 같아 함께 작성합니다. 

**추후 리팩토링 예정 사항**
1) StarCardDetail에 있는 Title 컴포넌트 삭제 
이전에 이야기 나눴는데, 작업 하다보니 Title 컴포넌트를 자주 쓰지 않아서 삭제할 예정입니다. 

2) StarCardDetail에 있는 Star, Label 컴포넌트 삭제
이것도 굳이 컴포넌트로 나누지 않아도 될 것 같아서 삭제하고 Img 컴포넌트와 합치려고 합니다. 
(Star 관련 페이지에만 있고 자주 사용하지 않기 때문)

혹시 의견 있으시면 남겨주세요~

<br>

## ⭐️ Review point
- [ ] 디자인 시안과 다른 부분 없는지
- [ ] 탭 눌렀을때 배경이 파란색으로 잘 바뀌는지
- [ ] 그 외 이상한 부분 없는지..

확인 부탁드립니다. 

<br>

## 📷 Demo
<img width="330" alt="스크린샷 2024-02-21 오후 9 43 55" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/ba2f48d0-1748-48dd-aa54-c20f3ae4b0a6">

<br>

2024-02-22 03:09 UTC, pizzaYami commented
디자인적으로 문제없습니다.
저는 '휴식 | 취미' 괜찮습니다.
title, label, star컴포넌트는 삭제해도 될 것 같네요.

2024-02-22 07:12 UTC, sikkzz requested changes

2024-02-22 07:12 UTC, sikkzz commented on src/pages/StarPage.tsx
> +	width: 360px;
rem 일부로 설정 안하신건가요? 확인 부탁드려요~

2024-02-22 07:12 UTC, sikkzz commented on src/constants/starCategoryConstants.tsx
> +	{ id: 5, content: "휴식ㅣ취미" },
id값이 없어도 되지 않을까 싶기는 해요 key 값은 content로도 사용 가능할 거 같아서요

2024-02-22 07:13 UTC, sikkzz commented
현재 구조에서는 말씀하신 "|"부분 텍스트로 현재 상태 유지하셔도 될 거 같기는한데 편하신대로 하시면 되지 않을까 싶네요

2024-02-22 13:14 UTC, khkh0109 commented on src/constants/starCategoryConstants.tsx
> +	{ id: 5, content: "휴식ㅣ취미" },
그러네요 id 빼고 content로 key를 사용할수도 있네요
그럼 이 부분은 id를 빼고 문자열만 있는 배열로 수정하겠습니다~

2024-02-22 13:16 UTC, khkh0109 commented on src/pages/StarPage.tsx
> +	width: 360px;
rem으로 수정했습니다
Header나 StarCardDetail에도 360px로 했던것 같은데 다른 브랜치에서 작업하고 올리겠습니다~

2024-02-22 13:35 UTC, khkh0109 commented
'휴식 | 취미' 이 부분은 그냥 텍스트로 남겨두겠습니다~ 
나중에 `|` 이 부분만 스타일이 달라진다면 그때 바꾸는게 나을 것 같네요

2024-02-22 13:45 UTC, sikkzz approved these changes

2024-02-22 22:33 UTC, pizzaYami approved these changes

2024-02-26 08:37 UTC, youngTkim approved these changes

2024-02-26 11:00 UTC, merged