[TS-272] Feat notification page notification setting modal
ConnectingStar/ConnectingStar-Front pull request #40
Opened 2024-02-25 10:08 UTC by sikkzz

[TS-272](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?assignee=712020%3Add928be4-89fa-4c60-9aa8-e0ad8f6b5a7b&selectedIssue=TS-272)

## 💡 변경사항 & 이슈
알림 설정 일시 정지 기간 모달 제작

## ✍️ 관련 설명
알림 설정 일시 정지 기간 모달입니다.
캘린더에서 현재 날짜 이전 달로는 이동 불가합니다.
정지 버튼 날짜 텍스트는 api 연결되면 변경 예정이라 이에 따라 로직도 조금 변동 될 예정입니다.
날짜 선택 로직도 이후 같이 변경 하려 합니다. (현재는 선택만 가능하고 디테일한 부분들 수정 안함)
스와이프 로직은 우선 보류 하겠습니다. 

## ⭐️ Review point
.

## 📷 Demo
<img width="365" alt="스크린샷 2024-02-25 오후 7 07 47" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/ab9b7f1d-faad-4a07-bec1-666948a471d3">

2024-02-26 08:47 UTC, youngTkim commented on src/components/MyPage/NotificationSetting/StopHabitModal/StopHabitModal.tsx
나중에는 해당 날짜의 해당 습관을 일정기간 멈추는 작업을 하게 되는건가요?

2024-02-26 08:56 UTC, sikkzz commented on src/components/MyPage/NotificationSetting/StopHabitModal/StopHabitModal.tsx
네 맞습니다 [해당 정보](https://www.figma.com/file/deVOGLOqzbCjKJP9fDeB3i/%EC%BB%A4%EB%84%A5%ED%8C%85%EC%8A%A4%ED%83%80?type=design&node-id=5739-10512&mode=dev) 확인하시면 됩니다

2024-02-27 10:17 UTC, khkh0109 submitted a review, later dismissed

2024-02-28 21:32 UTC, pizzaYami requested changes

2024-02-28 21:32 UTC, pizzaYami commented on src/components/MyPage/NotificationSetting/StopHabitModal/StopHabitModal.tsx
> +		${theme.font.header};
"일시 정지 기간을 선택해주세요"부분
달력이랑 동일하게 넣어야하지 않을까요?
    margin: 0 auto;
    width: 19.25rem;

2024-02-28 21:32 UTC, pizzaYami commented
디테일한 부분은 나중에 수정하신다고 했지만 혹시몰라서 언급할게요.
1. 선택된 날짜 사이에 회색줄 생성 안됨
 ![Uploading 스크린샷 2024-02-29 오전 5.58.32.png…]()
2. 모달바깥쪽 영역 클릭시에도 취소가 아니라 선택완료가 됨
3. gap이랑 margin 6px 하나만 들어가야되는데 둘다 들어간거같네요
![스크린샷 2024-02-29 오전 6 20 30](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/44329af5-ff31-4d97-b33a-2c077668f5bc)
![스크린샷 2024-02-29 오전 6 20 57](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/0074add0-b83c-4433-b506-09eda8a6789c)

2024-02-29 05:59 UTC, youngTkim submitted a review, later dismissed

2024-03-03 16:33 UTC, sikkzz commented on src/components/MyPage/NotificationSetting/StopHabitModal/StopHabitModal.tsx
> +		${theme.font.header};
시안상 현재가 맞습니다. 캘린더 시안 보시면 여백 존재합니다

2024-03-03 16:35 UTC, sikkzz commented
> 디테일한 부분은 나중에 수정하신다고 했지만 혹시몰라서 언급할게요.
> 
> 1. 선택된 날짜 사이에 회색줄 생성 안됨
>    ![스크린샷 2024-02-29 오전 6 32 48](https://private-user-images.githubusercontent.com/116322645/308720854-91af6e79-32f4-4ae0-92db-f1ee877ab168.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0ODM3MjcsIm5iZiI6MTcwOTQ4MzQyNywicGF0aCI6Ii8xMTYzMjI2NDUvMzA4NzIwODU0LTkxYWY2ZTc5LTMyZjQtNGFlMC05MmRiLWYxZWU4NzdhYjE2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwM1QxNjMwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDVkMzE1ZWNkMjhiODNiYmMzNjBlYjBjM2MxM2RhMGUzY2JjYmU2ZTU3ODgzNjVmMTU0NWVmZDY3ZDYzZWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nKCX_tT4SEPP7WQpqQ-SmeEehsMPb1jw5WC9K2AyucQ)
> 2. 모달바깥쪽 영역 클릭시에도 취소가 아니라 선택완료가 됨
> 3. gap이랑 margin 6px 하나만 들어가야되는데 둘다 들어간거같네요
>    ![스크린샷 2024-02-29 오전 6 20 30](https://private-user-images.githubusercontent.com/116322645/308718044-44329af5-ff31-4d97-b33a-2c077668f5bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0ODM3MjcsIm5iZiI6MTcwOTQ4MzQyNywicGF0aCI6Ii8xMTYzMjI2NDUvMzA4NzE4MDQ0LTQ0MzI5YWY1LWZmMzEtNGQ5Ny1iMzNhLTJjMDc3NjY4ZjViYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwM1QxNjMwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWQwMGUwOTU1NWY0MGNhN2YwZDA2ZjU3OTMyZjc0ZDE2MjI3ZDc1MmU4ZGJjNGU3YTNmNTMwNzc4YzIyZTE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z2YPIhtuOcfbGK3ewDcu2KGyuyYWAWop_qO9hQhr80k)
>    ![스크린샷 2024-02-29 오전 6 20 57](https://private-user-images.githubusercontent.com/116322645/308718057-0074add0-b83c-4433-b506-09eda8a6789c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0ODM3MjcsIm5iZiI6MTcwOTQ4MzQyNywicGF0aCI6Ii8xMTYzMjI2NDUvMzA4NzE4MDU3LTAwNzRhZGQwLWI4M2MtNDQzMy1iNTA2LTA5ZWRhOGE2Nzg5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwM1QxNjMwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTE4YzliYjZmYjJhODQ0YTNjMTAzMzQ3Mjc0NzAxYThkYjg1NjRiNDgyZjhjZWY0OTgxMjEyYTg0ODNjNTUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.baA3XCdY6eCznzFO4sr5pyCNrAt2--zFABtajPCv4k4)

1, 2번은 api 연결하면서 수정 예정입니다.
3번은 오류가 맞네요 수정했습니다.

2024-03-04 08:42 UTC, khkh0109 approved these changes, later dismissed

2024-03-04 09:58 UTC, pizzaYami approved these changes, later dismissed

2024-03-04 10:07 UTC, merged