[TS-286] StarPage, StarCardDetailPage 리팩토링
ConnectingStar/ConnectingStar-Front pull request #44
Opened 2024-03-02 15:00 UTC by khkh0109

[TS-286](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?selectedIssue=TS-286)

## 💡 변경사항 & 이슈
StarPage, StarCardDetailPage 리팩토링
<br>

## ✍️ 관련 설명
StarPage, StarCardDetailPage 리팩토링 했습니다. 

1. 경로 및 폴더 이름 피그마와 동일하게 수정
  - 피그마에 있는 페이지 이름과 통일시키는게 찾기 편할 것 같아서 기존 StarPage를 StarCardPage로 변경
  - 별자리 관련 컴포넌트는 StarPage 내부에 넣을 예정
  - 관련 폴더 및 파일 이름, 컴포넌트 이름, 경로 이름도 함께 변경
  - 별자리 메인 페이지까지 추가되면 StarPage는 아래와 같은 폴더 구조가 됨 (괄호 안은 경로 이름)
 ```
 components/StarPage
  ㄴ StarMain(star) -> 별자리 메인
  ㄴ StarCard(star-card) -> 별자리 카드
  ㄴ StarCardDetail(star-card/:id) -> 별자리 카드 상세
 ```

<br>

2. StarCardDetailPage와 style 폴더 합침
기존에는 컴포넌트 파일과 스타일 파일이 분리되어 있었음. 하지만 스타일 코드가 짧아서 두 파일을 하나로 합침

<br>

3. StarCardDetailPage 버튼을 공통 버튼으로 교체 
공통 버튼으로 교체 후 필요없어진 코드, 주석, 파일 삭제함

<br>

4. 별자리 페이지 관련 상수 파일을 하나로 합침
기존에 분리되어 있던 별자리 페이지 관련 상수를 보기 편하게 starPageConstants 파일로 합침

<br>

5. 자주 쓰지 않는 Title, Star 컴포넌트 삭제 

<br>

6. Label 컴포넌트 분리
기존에는 category, have 라벨을 Label 컴포넌트로 합쳐서 사용함. 하지만 해당 컴포넌트 이름만 보고 어떤 라벨인지 유추하기 어려워서 분리함
  - 카테고리 라벨은 기존에 있던 컴포넌트(CategoryLabel)를 그대로 사용
  - 보유 라벨은 Img 컴포넌트와 합침

<br>

7. 360px -> rem 단위로 변경 

<br>

8. StarCardDetailPage에 있는 titleStyle 분리
기존에는 titleStyle.h1, titleStyle.h2 이렇게 작성했음. 하지만 어떤 종류의 제목인지 명확하지 않아서 titleStyle, subTitleStyle로 분리

<br>

## ⭐️ Review point
잘 동작하는지 확인 부탁드립니다
<br>

## 📷 Demo
없음
<br>

2024-03-03 17:11 UTC, sikkzz requested changes

2024-03-03 17:11 UTC, sikkzz commented on src/components/StarPage/StarCardDetail/Img.style.ts
> +		height: 3.75rem;
이미지 크기가 고정이다 보니 사실상 width, height가 필요한 코드는 아니긴 합니다. 하지만 혹시 모르니 넣어서 정해주고 싶으시다면 div나 이미지 둘 중 하나만 넣으셔도 될 거 같네요

2024-03-03 17:11 UTC, sikkzz commented on src/pages/StarCardDetailPage.tsx
<img width="520" alt="스크린샷 2024-03-04 오전 2 09 00" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/30adebcb-4375-4950-aca7-a5dba6d1bb84">

구분선 생깁니다. 임시 해결 방편은 FooterBtn에 isTransparent prop 넣으시면 됩니다.

2024-03-03 17:11 UTC, sikkzz commented on src/pages/StarCardDetailPage.tsx
> +	padding: 1.25rem 1.5rem 5.4375rem 1.5rem;
padding: 1.25rem 1.5rem 5.4375rem

2024-03-03 17:11 UTC, sikkzz commented on src/pages/StarCardDetailPage.tsx
> +`;
sectionStyle에 & > h1, & > h2 쓰면 제거할 수 있겠네요. 인라인 스타일 코드도 사라질거구요

2024-03-04 09:12 UTC, khkh0109 commented on src/components/StarPage/StarCardDetail/Img.style.ts
> +		height: 3.75rem;
그러네요 둘 다 주석처리 했는데 화면상 아무 변화가 없어서 둘 다 삭제했습니다~

2024-03-04 09:14 UTC, khkh0109 commented on src/pages/StarCardDetailPage.tsx
> +`;
이 부분도 sectionStyle 내부로 이동했습니다. 인라인 스타일 코드가 사라지니 보기 편해져서 좋네요

2024-03-04 09:19 UTC, sikkzz submitted a review, later dismissed

2024-03-05 21:18 UTC, sikkzz approved these changes

2024-03-06 11:57 UTC, pizzaYami approved these changes

2024-03-07 12:57 UTC, youngTkim approved these changes

2024-03-07 13:00 UTC, merged