[Ts-53] 유저정보입력모달 CreateAccountPage
ConnectingStar/ConnectingStar-Front pull request #45
Opened 2024-03-04 10:07 UTC by pizzaYami

[JIRA-53](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109/backlog?assignee=712020%3A2697805c-34c2-4de5-99cb-4aab5f6d607a&selectedIssue=TS-53)

## 💡 변경사항 & 이슈
/createAccount
<ChangeNicknameModal> placeholder "닉네임을 입력해주세요" 변경했습니다.

<br>

## ✍️ 관련 설명
모달을 연결했습니다.
유저데이터는 redux로 전역state 만들면 연결하겠습니다.
이름이 뭔가 마음에 안 들지만 나중에 한꺼번에 통일성있게 고칠 예정입니다.
<br>

## ⭐️ Review point
rebase하면서 고친코드가 과거로 좀 돌아간 것 같아서 상세하게 리뷰 부탁드립니다. -> 저도 계속 확인할게요
모달 사용법이 알맞는지 궁금합니다.
<br>

## 📷 Demo
<br>
![스크린샷 2024-03-04 오후 6 59 54](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/7f1aed07-660b-4196-a0d1-65d26f61c4bd)
88774236a726)

2024-03-05 21:52 UTC, sikkzz requested changes

2024-03-05 21:52 UTC, sikkzz commented on src/components/common/FooterBtn/FooterBtn.Style.ts
> -		padding: ${!isSquare && !isPositionStatic && "1rem 1.5rem"};
이게 최신 버전이 맞습니다.

2024-03-05 21:52 UTC, sikkzz commented on src/components/common/FooterBtn/FooterBtn.Style.ts
> -		background-color: ${!transparent && "white"};
얘도 이게 최신버전이에요

2024-03-05 21:52 UTC, sikkzz commented on src/pages/CreateAccountPage.style.ts
> +		width: 100%;
없어도 동일합니다

2024-03-05 21:52 UTC, sikkzz commented on src/pages/CreateAccountPage.style.ts
> +			width: 100%;
없어도 동일합니다

2024-03-05 21:52 UTC, sikkzz commented on src/pages/CreateAccountPage.style.ts
> +			height: 5.438rem;
없어도 동일합니다

2024-03-05 21:52 UTC, sikkzz commented on src/pages/CreateAccountPage.style.ts
> +				justify-content: space-between;
align-items: center 추가해야할거 같네요 자세히보시면 아이콘이 중앙이 아니에요

2024-03-05 21:52 UTC, sikkzz commented on src/pages/CreateAccountPage.style.ts
> +				width: 100%;
없어도 동일합니다

2024-03-05 21:52 UTC, sikkzz commented on src/pages/CreateAccountPage.style.ts
> +				height: 3.438rem;
이친구도요

2024-03-05 21:52 UTC, sikkzz commented on src/pages/CreateAccountPage.tsx
> +import ArrowDown from "@/assets/icon/arrow-down.svg?react";
ArrowDownIcon으로 변경 부탁드려요

2024-03-05 21:52 UTC, sikkzz commented on src/pages/CreateAccountPage.tsx
> +						return (
map 안에서 "{" 대신 "("를 쓰면 return 문 제거 가능해요

2024-03-05 21:52 UTC, sikkzz commented on src/pages/CreateAccountPage.tsx
> +			<FooterBtn text="다음" />
구분선 있어서 isTransparent 필요합니다

2024-03-05 21:52 UTC, sikkzz commented on src/pages/CreateAccountPage.tsx
내부 index 이용한 코드들 간소화 하나하나 리뷰 드리기 좀 번거로워서 전체 코드 드립니다. 이해 안가시는부분 있으면 말씀해주세요

```jsx
import { useState } from "react";

import ArrowDown from "@/assets/icon/arrow-down.svg?react";

import FooterBtn from "@/components/common/FooterBtn/FooterBtn";
import Header from "@/components/common/Header/Header";
import ChangeNicknameModal from "@/components/common/Modal/CommonModal/ChangeNicknameModal";
import SelectAgeModal from "@/components/common/Modal/CommonModal/SelectAgeModal";
import SelectGenderModal from "@/components/common/Modal/CommonModal/SelectGenderModal/SelectGenderModal";

import { useAppDispatch, useAppSelector } from "@/api/hooks";
import { openModal } from "@/api/modal/modalSlice";

import { modalType } from "@/constants/modalConstants";

import { createAccountStyle } from "@/pages/CreateAccountPage.style";

export default function CreateAccountPage() {
	const dispatch = useAppDispatch();

	const { modal } = useAppSelector((state) => state.modal);

	const [nickName, setNickName] = useState<string>("");
	const [gender, setGender] = useState<string>("");
	const [age, setAge] = useState<string>("");

	const accountInputData = [
		{
			state: nickName,
			title: "닉네임",
			content: "닉네임을 입력해 주세요",
			modalType: modalType.CHANGE_NICKNAME,
		},
		{
			state: gender,
			title: "성별",
			content: "성별을 선택해 주세요",
			modalType: modalType.SELECT_GENDER,
		},
		{
			state: age,
			title: "나이대",
			content: "나이대를 선택해 주세요",
			modalType: modalType.SELECT_AGE,
		},
	];

	return (
		<>
			<Header>
				<Header.PrevButton></Header.PrevButton>
			</Header>
			<div css={createAccountStyle.container}>
				<h1>내 정보 입력을 완료해 주세요</h1>
				<ul css={createAccountStyle.wrap}>
					{accountInputData.map((item) => (
						<li key={item.title}>
							<h2>{item.title}</h2>
							<div
								onClick={() => {
									dispatch(openModal(item.modalType));
								}}
							>
								{item.state === "" ? item.content : item.state}

								{item.title !== "닉네임" && <ArrowDown />}
							</div>
						</li>
					))}
				</ul>
			</div>

			<FooterBtn text="다음" isTransparent />

			{modal === modalType.CHANGE_NICKNAME && <ChangeNicknameModal changeNickname={setNickName} />}
			{modal === modalType.SELECT_GENDER && <SelectGenderModal changeGender={setGender} />}
			{modal === modalType.SELECT_AGE && <SelectAgeModal changeAge={setAge} />}
		</>
	);
}
```

2024-03-05 21:52 UTC, sikkzz commented on src/pages/VisitTrackPage.tsx
> +import { visitTrackStyle } from "./VisitTrackPage.style";
절대경로

2024-03-05 21:52 UTC, sikkzz commented on src/pages/VisitTrackPage.tsx
> +				<Header.PrevButton></Header.PrevButton>
<Header.PrevButton />

2024-03-05 21:52 UTC, sikkzz commented on src/pages/VisitTrackPage.style.ts
> +		width: 100%;
불필요

2024-03-05 21:52 UTC, sikkzz commented on src/pages/VisitTrackPage.style.ts
> +		width: 100%;
불필요

2024-03-06 12:39 UTC, khkh0109 commented
입력 완료했을때 글자 색이 원래 회색인건가요? 다른 페이지에서는 input에 입력 하고 나서도 검정색이던데 여기는 회색으로 처리하는건지 궁금해서 여쭤봐요!

<img width="300" alt="스크린샷 2024-03-06 오후 9 37 18" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/d0c30724-f5f1-4cff-a8d1-8e9e3342629d">

2024-03-06 14:10 UTC, khkh0109 commented
닉네임 입력할때 유효하지 않은 값(ex. 이모티콘)이 들어오면 빨간 에러 뜨는 부분은 다른 브랜치에서 작업 예정인가요?

2024-03-06 14:21 UTC, khkh0109 commented
그리고 방금 발견했는데 바텀시트 내부 버튼의 상하좌우 여백이 디자인 시안과 다릅니다! 실제 구현된 바텀시트에 여백이 더 들어가있네요 

디자인 시안
<img width="300" alt="스크린샷 2024-03-06 오후 11 15 45" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/66d3370c-4722-469d-a4d9-c3f08989d70b">

실제 
<img width="300" alt="스크린샷 2024-03-06 오후 11 16 15" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/b3861c25-9b02-4514-927b-60f882efb393">

2024-03-07 04:56 UTC, pizzaYami commented
> 그리고 방금 발견했는데 바텀시트 내부 버튼의 상하좌우 여백이 디자인 시안과 다릅니다! 실제 구현된 바텀시트에 여백이 더 들어가있네요
> 
> 디자인 시안 <img alt="스크린샷 2024-03-06 오후 11 15 45" width="300" src="https://private-user-images.githubusercontent.com/77181642/310530262-66d3370c-4722-469d-a4d9-c3f08989d70b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODY4ODUsIm5iZiI6MTcwOTc4NjU4NSwicGF0aCI6Ii83NzE4MTY0Mi8zMTA1MzAyNjItNjZkMzM3MGMtNDcyMi00NjlkLWE0ZDktYzNmMDg5ODlkNzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA0NDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNzMxZmY1YzA5OGUyMzJiNTllOGM3NWQyNDM2ODM2NDJhZDQ5YmQzNTU0ZDYyMzZjN2U3NmJhMmNmMjc0MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CUsP8brsM2EZgdX8ee1qMW2V1yliSOFyEX95nPJskFM">
> 
> 실제 <img alt="스크린샷 2024-03-06 오후 11 16 15" width="300" src="https://private-user-images.githubusercontent.com/77181642/310530400-b3861c25-9b02-4514-927b-60f882efb393.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODY4ODUsIm5iZiI6MTcwOTc4NjU4NSwicGF0aCI6Ii83NzE4MTY0Mi8zMTA1MzA0MDAtYjM4NjFjMjUtOWIwMi00NTE0LTkyN2ItNjBmODgyZWZiMzkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA0NDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MGZjYTc3YTNkY2U1ZWI5YmUzMGFjMjNhZWM0MmNkYTZhMzY3N2ZlNmY3MTcwOTRiMjc3MGVlZWZlMzU3MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tm68Mb1Uuqiv4P2IcsLsYb4Ss88eZMpxdq9Ys0pwnaU">

![스크린샷 2024-03-07 오후 1 56 21](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/43de0905-f47a-4804-b7b2-894f569ae45b)
저는 이렇게 보이는데 다른가요?

2024-03-07 07:30 UTC, khkh0109 commented
> > 그리고 방금 발견했는데 바텀시트 내부 버튼의 상하좌우 여백이 디자인 시안과 다릅니다! 실제 구현된 바텀시트에 여백이 더 들어가있네요
> > 디자인 시안 <img alt="스크린샷 2024-03-06 오후 11 15 45" width="300" src="https://private-user-images.githubusercontent.com/77181642/310530262-66d3370c-4722-469d-a4d9-c3f08989d70b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODY4ODUsIm5iZiI6MTcwOTc4NjU4NSwicGF0aCI6Ii83NzE4MTY0Mi8zMTA1MzAyNjItNjZkMzM3MGMtNDcyMi00NjlkLWE0ZDktYzNmMDg5ODlkNzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA0NDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNzMxZmY1YzA5OGUyMzJiNTllOGM3NWQyNDM2ODM2NDJhZDQ5YmQzNTU0ZDYyMzZjN2U3NmJhMmNmMjc0MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CUsP8brsM2EZgdX8ee1qMW2V1yliSOFyEX95nPJskFM">
> > 실제 <img alt="스크린샷 2024-03-06 오후 11 16 15" width="300" src="https://private-user-images.githubusercontent.com/77181642/310530400-b3861c25-9b02-4514-927b-60f882efb393.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODY4ODUsIm5iZiI6MTcwOTc4NjU4NSwicGF0aCI6Ii83NzE4MTY0Mi8zMTA1MzA0MDAtYjM4NjFjMjUtOWIwMi00NTE0LTkyN2ItNjBmODgyZWZiMzkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA0NDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MGZjYTc3YTNkY2U1ZWI5YmUzMGFjMjNhZWM0MmNkYTZhMzY3N2ZlNmY3MTcwOTRiMjc3MGVlZWZlMzU3MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tm68Mb1Uuqiv4P2IcsLsYb4Ss88eZMpxdq9Ys0pwnaU">
> 
> ![스크린샷 2024-03-07 오후 1 56 21](https://private-user-images.githubusercontent.com/116322645/310751054-43de0905-f47a-4804-b7b2-894f569ae45b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTY3NjIsIm5iZiI6MTcwOTc5NjQ2MiwicGF0aCI6Ii8xMTYzMjI2NDUvMzEwNzUxMDU0LTQzZGUwOTA1LWY0N2EtNDgwNC1iN2IyLTg5NGY1NjlhZTQ1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QwNzI3NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NGMwNjJlYTIwNGZiZmU1OWZiZjMzYWQzODk3YWVjMjQ2MmJjYTkyN2U5NzFlZTY2YWJmNTViZDlhMTRmOTY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TV6GgCge1q58mCr_zldi8pPc3LBpwE0rJ8tiKK74gdA) 저는 이렇게 보이는데 다른가요?

혹시 FooterBtn.style 수정하셨나요? 만약 수정하셨다면 저는 PR에 올라와있는 코드로 보는거라 다르게 보이는것 같네요~

2024-03-07 09:19 UTC, pizzaYami commented
> > > 그리고 방금 발견했는데 바텀시트 내부 버튼의 상하좌우 여백이 디자인 시안과 다릅니다! 실제 구현된 바텀시트에 여백이 더 들어가있네요
> > > 디자인 시안 <img alt="스크린샷 2024-03-06 오후 11 15 45" width="300" src="https://private-user-images.githubusercontent.com/77181642/310530262-66d3370c-4722-469d-a4d9-c3f08989d70b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODY4ODUsIm5iZiI6MTcwOTc4NjU4NSwicGF0aCI6Ii83NzE4MTY0Mi8zMTA1MzAyNjItNjZkMzM3MGMtNDcyMi00NjlkLWE0ZDktYzNmMDg5ODlkNzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA0NDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNzMxZmY1YzA5OGUyMzJiNTllOGM3NWQyNDM2ODM2NDJhZDQ5YmQzNTU0ZDYyMzZjN2U3NmJhMmNmMjc0MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CUsP8brsM2EZgdX8ee1qMW2V1yliSOFyEX95nPJskFM">
> > > 실제 <img alt="스크린샷 2024-03-06 오후 11 16 15" width="300" src="https://private-user-images.githubusercontent.com/77181642/310530400-b3861c25-9b02-4514-927b-60f882efb393.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODY4ODUsIm5iZiI6MTcwOTc4NjU4NSwicGF0aCI6Ii83NzE4MTY0Mi8zMTA1MzA0MDAtYjM4NjFjMjUtOWIwMi00NTE0LTkyN2ItNjBmODgyZWZiMzkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA0NDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MGZjYTc3YTNkY2U1ZWI5YmUzMGFjMjNhZWM0MmNkYTZhMzY3N2ZlNmY3MTcwOTRiMjc3MGVlZWZlMzU3MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tm68Mb1Uuqiv4P2IcsLsYb4Ss88eZMpxdq9Ys0pwnaU">
> > 
> > 
> > ![스크린샷 2024-03-07 오후 1 56 21](https://private-user-images.githubusercontent.com/116322645/310751054-43de0905-f47a-4804-b7b2-894f569ae45b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTY3NjIsIm5iZiI6MTcwOTc5NjQ2MiwicGF0aCI6Ii8xMTYzMjI2NDUvMzEwNzUxMDU0LTQzZGUwOTA1LWY0N2EtNDgwNC1iN2IyLTg5NGY1NjlhZTQ1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QwNzI3NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NGMwNjJlYTIwNGZiZmU1OWZiZjMzYWQzODk3YWVjMjQ2MmJjYTkyN2U5NzFlZTY2YWJmNTViZDlhMTRmOTY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TV6GgCge1q58mCr_zldi8pPc3LBpwE0rJ8tiKK74gdA) 저는 이렇게 보이는데 다른가요?
> 
> 혹시 FooterBtn.style 수정하셨나요? 만약 수정하셨다면 저는 PR에 올라와있는 코드로 보는거라 다르게 보이는것 같네요~

아 Footer.Btn 수정했습니다. 그럼 문제 없겠네요 감사합니다.

2024-03-07 09:20 UTC, pizzaYami commented
> 입력 완료했을때 글자 색이 원래 회색인건가요? 다른 페이지에서는 input에 입력 하고 나서도 검정색이던데 여기는 회색으로 처리하는건지 궁금해서 여쭤봐요!
> 
> <img alt="스크린샷 2024-03-06 오후 9 37 18" width="300" src="https://private-user-images.githubusercontent.com/77181642/310500717-d0c30724-f5f1-4cff-a8d1-8e9e3342629d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MDMzNzQsIm5iZiI6MTcwOTgwMzA3NCwicGF0aCI6Ii83NzE4MTY0Mi8zMTA1MDA3MTctZDBjMzA3MjQtZjVmMS00Y2ZmLWE4ZDEtOGU5ZTMzNDI2MjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA5MTc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1OTFkZThhYmUyODc5NDQ4NTYzZTA5ODE0Y2QzZmQ3NWMzNmQ4NGFkMjQyZDkyNjViMGIzMzhjMjU3NjhjMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g4f48WzdmgLfGddMKo5e2sFC_-KNEadqvFULxtvSU8k">

값 입력될 시 color: black되도록 변경했습니다.

닉네임 입력할때 유효하지 않은 값(ex. 이모티콘)이 들어오면 빨간 에러 뜨는 부분은 다른 브랜치에서 작업 예정인가요?
-> 이것도 수정완료했습니다.

2024-03-10 10:00 UTC, sikkzz requested changes

2024-03-10 10:00 UTC, sikkzz commented on src/App.tsx
> +				<Route path="/discoveryRoute" element={<DiscoveryRoutePage />} />
미사용

2024-03-10 10:00 UTC, sikkzz commented on src/App.tsx
> +import DiscoveryRoutePage from "@/pages/VisitTrackPage";
미사용

2024-03-10 10:00 UTC, sikkzz commented on src/pages/CreateAccountPage.tsx
> +				<Header.PrevButton></Header.PrevButton>
<Header.PrevButton />

2024-03-10 10:00 UTC, sikkzz commented on src/hooks/isValidateNickName.ts
리뷰드린대로면 불필요할겁니다

2024-03-10 10:00 UTC, sikkzz commented on src/components/common/Modal/CommonModal/ChangeNicknameModal.tsx
간소화 시켜본 코드에요 문제 있으면 말씀해주세요

```jsx
import { ChangeEvent, Dispatch, SetStateAction, useState } from "react";

import { css } from "@emotion/react";

import InfoIcon from "@/assets/icon/infomation.svg?react";

import FooterBtn from "@/components/common/FooterBtn/FooterBtn";
import Modal from "@/components/common/Modal/Modal";

import { useAppDispatch } from "@/api/hooks";
import { closeModal } from "@/api/modal/modalSlice";

import { theme } from "@/styles/theme";

// 이모지 판별을 위한 정규식
const emojiRegex = /\p{Extended_Pictographic}/u;

const ChangeNicknameModal = ({
	changeNickname,
}: {
	changeNickname: Dispatch<SetStateAction<string>>;
}) => {
	const dispatch = useAppDispatch();

	const [nickname, setNickname] = useState("");
	const [isError, setIsError] = useState(false);

	const handleNicknameChange = (e: ChangeEvent<HTMLInputElement>) => {
		let input = e.target.value;

		// 띄어쓰기 작성 막기
		input = input.replace(/\s+/g, "");

		if (emojiRegex.test(input)) {
			setIsError(true);
		} else {
			setIsError(false);
		}

		// 8자이상 입력 막기
		setNickname(input);
	};

	const handleChangeInput = () => {
		changeNickname(nickname);
		dispatch(closeModal());
	};

	return (
		<Modal isBottomSheet>
			<div css={layoutStyle(isError)}>
				<h1>닉네임을 입력해 주세요</h1>
				<input
					placeholder="닉네임을 입력해 주세요"
					value={nickname}
					onChange={(e) => handleNicknameChange(e)}
					maxLength={8}
				/>
				<div css={infoStyle(isError)}>
					{!isError && <InfoIcon />}
					<p>
						{isError ? "이모티콘은 사용할 수 없어요!" : "8자 제한, 띄어쓰기 불가, 이모티콘 불가"}
					</p>
				</div>
			</div>

			<FooterBtn
				text="확인"
				leftText="취소"
				handleBtnClick={handleChangeInput}
				handleLeftBtnClick={() => dispatch(closeModal())}
				isSquare
				disabled={isError || nickname.trim().length === 0}
			/>
		</Modal>
	);
};

export default ChangeNicknameModal;

const layoutStyle = (isError: boolean) => css`
	border-radius: 15px 15px 0 0;
	padding: 1.125rem 1.5rem 4.4375rem;
	color: ${theme.color.font_black};
	background-color: #fff;

	& > h1 {
		color: ${theme.color.font_black};
		${theme.font.header};
	}

	& > input {
		all: unset;
		border: 1px solid ${isError ? "red" : "none"};
		box-sizing: border-box;
		width: 100%;
		height: 3.4375rem;
		border-radius: 15px;
		padding: 1rem;
		margin-top: 1.6875rem;
		background-color: ${theme.color.bg};
		color: ${theme.color.font_black};
	}
`;
const infoStyle = (isError: boolean) => css`
	display: flex;
	align-items: center;
	${theme.font.body_c}
	margin-top: 8px;
	color: ${isError ? "red" : `${theme.color.font_gray}`};
	gap: 0.25rem;
`;
```

2024-03-10 10:03 UTC, sikkzz commented on src/components/common/Modal/CommonModal/ChangeNicknameModal.tsx
이전에 말씀드린대로 custom hook으로 빼려다가 코드 구성해놓으신거 보니까 input 입력 받는 과정에서 처리하고 계시길래 그냥 간소화만 시켰습니다.

이후에 validator들이 늘어나서 구성할 일이 있으면 말씀드릴게요

이건 별개로 리뷰드리는건데 custom hook은 util처럼 쓰는게 아니라 use붙여서 제작합니다. 커스텀훅은 리액트 state action이나 effect들하고 rule을 공유해서 작동하기 때문에 custom hook으로 쓰는겁니다. 그게 아니라면 util로 쓰는게 좋아요

그리고 현재는 리팩토링 안해드렸는데 인풋창 에러는 보통 ref잡아서 focus시킵니다. 저렇게 border를 바꿔주는 방식은 사용하지 않습니다

2024-03-11 11:00 UTC, pizzaYami commented on src/components/common/Modal/CommonModal/ChangeNicknameModal.tsx
8자 제한, 띄어쓰기 불가, 이모티콘 불가
에서 이모티콘이 들어가면 문구가 바뀌고 
8자 제한이 걸리면 빨간색으로 변하게 해야됩니다.

2024-03-12 11:19 UTC, sikkzz requested changes

2024-03-12 11:19 UTC, sikkzz commented on src/components/common/Modal/CommonModal/ChangeNicknameModal.tsx
> +	const [isError, setIsError] = useState(false);
불필요

2024-03-12 11:19 UTC, sikkzz commented on src/components/common/Modal/CommonModal/ChangeNicknameModal.tsx
> +		}
불필요

2024-03-12 11:19 UTC, sikkzz commented on src/components/common/Modal/CommonModal/ChangeNicknameModal.tsx
> +				disabled={isError || nickname.trim().length === 0}
isError 조건 불필요

2024-03-12 11:19 UTC, sikkzz commented
논의 결과 현재 디자인이 최종이면 제가 리뷰 달아드린 코드들 불필요인거 같은데 확인부탁드려요

2024-03-12 11:21 UTC, sikkzz commented
그리고 용주님 현재 코드 보시면 루트에 .yarnrc.yml 파일이 없습니다.
yarn set version 4.0.2 하시고 yarn install 한번 해보시면 생길겁니다. dev 브랜치 rebase해도 생기겠지만 알아두시라고 말씀드려요

2024-03-12 12:34 UTC, pizzaYami commented
> 그리고 용주님 현재 코드 보시면 루트에 .yarnrc.yml 파일이 없습니다. yarn set version 4.0.2 하시고 yarn install 한번 해보시면 생길겁니다. dev 브랜치 rebase해도 생기겠지만 알아두시라고 말씀드려요

저는 yarn set version 4.0.2하면 package.json이 변경되는데 이유를 모르겠네요

2024-03-12 12:35 UTC, sikkzz commented
> > 그리고 용주님 현재 코드 보시면 루트에 .yarnrc.yml 파일이 없습니다. yarn set version 4.0.2 하시고 yarn install 한번 해보시면 생길겁니다. dev 브랜치 rebase해도 생기겠지만 알아두시라고 말씀드려요
> 
> 저는 yarn set version 4.0.2하면 package.json이 변경되는데 이유를 모르겠네요

package.json 변경되는거도 맞습니다. yml 파일 생성 되셨을까요?

2024-03-12 12:38 UTC, pizzaYami commented
> > > 그리고 용주님 현재 코드 보시면 루트에 .yarnrc.yml 파일이 없습니다. yarn set version 4.0.2 하시고 yarn install 한번 해보시면 생길겁니다. dev 브랜치 rebase해도 생기겠지만 알아두시라고 말씀드려요
> > 
> > 
> > 저는 yarn set version 4.0.2하면 package.json이 변경되는데 이유를 모르겠네요
> 
> package.json 변경되는거도 맞습니다. yml 파일 생성 되셨을까요?

생성이 안되네요

2024-03-12 12:40 UTC, sikkzz commented
> > > > 그리고 용주님 현재 코드 보시면 루트에 .yarnrc.yml 파일이 없습니다. yarn set version 4.0.2 하시고 yarn install 한번 해보시면 생길겁니다. dev 브랜치 rebase해도 생기겠지만 알아두시라고 말씀드려요
> > > 
> > > 
> > > 저는 yarn set version 4.0.2하면 package.json이 변경되는데 이유를 모르겠네요
> > 
> > 
> > package.json 변경되는거도 맞습니다. yml 파일 생성 되셨을까요?
> 
> 생성이 안되네요

코드 수정 다 하시고 최종 버전에서 저한테 한번만 말씀해주실래요? 저는 방금도 용주님 브랜치에서 설정하면 파일 생성 정상인데 뭐가 문제인지 모르겠네요 같이 한번 확인해봐요

2024-03-12 13:12 UTC, khkh0109 commented
이모지가 막히긴 하는데 일부는 빈 칸처럼 입력이 되네요..! 영상도 함께 첨부합니다

https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/f7e17725-4146-41ab-b48c-a6ce66674a87

또 이 경우는 괜찮은걸까요? 텍스트 별도 막으신 것 같은데 어떤 텍스트 별(⭐︎ -> 얘)은 입력이 됩니다
또 데스크탑에서는 별 이모지로 보이네요,,

<img width="283" alt="스크린샷 2024-03-12 오후 10 00 48" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/b73ef580-677a-4e46-9d90-a799703aa4d9">

이런 경우들도 괜찮으면 그냥 넘어가도 될 것 같네요~

2024-03-12 13:30 UTC, khkh0109 commented on src/assets/icon/infomation.svg
information 오타났네요..!

2024-03-13 09:53 UTC, pizzaYami commented
> 이모지가 막히긴 하는데 일부는 빈 칸처럼 입력이 되네요..! 영상도 함께 첨부합니다
> 
>  RPReplay_Final1710248015.mov 
> 또 이 경우는 괜찮은걸까요? 텍스트 별도 막으신 것 같은데 어떤 텍스트 별(⭐︎ -> 얘)은 입력이 됩니다 또 데스크탑에서는 별 이모지로 보이네요,,
> 
> <img alt="스크린샷 2024-03-12 오후 10 00 48" width="283" src="https://private-user-images.githubusercontent.com/77181642/312084649-b73ef580-677a-4e46-9d90-a799703aa4d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjM4NjEsIm5iZiI6MTcxMDMyMzU2MSwicGF0aCI6Ii83NzE4MTY0Mi8zMTIwODQ2NDktYjczZWY1ODAtNjc3YS00ZTQ2LTlkOTAtYTc5OTcwM2FhNGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA5NTI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZmM3YTU4NzA5NmVlMWVlNzU4ZDU1MzJiYTlkNjQwMTcyOWE3NDlmNDIzNTIyN2JlMDQ0NjFiZGFmNWUzMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TIU1QuLDn53o-rvhWQ9XADLgry1rm9EwkODwqOD0KbY">
> 이런 경우들도 괜찮으면 그냥 넘어가도 될 것 같네요~

해결했는데 한번 더 확인부탁드립니다.

2024-03-13 10:20 UTC, khkh0109 commented
> > 이모지가 막히긴 하는데 일부는 빈 칸처럼 입력이 되네요..! 영상도 함께 첨부합니다
> > RPReplay_Final1710248015.mov
> > 또 이 경우는 괜찮은걸까요? 텍스트 별도 막으신 것 같은데 어떤 텍스트 별(⭐︎ -> 얘)은 입력이 됩니다 또 데스크탑에서는 별 이모지로 보이네요,,
> > <img alt="스크린샷 2024-03-12 오후 10 00 48" width="283" src="https://private-user-images.githubusercontent.com/77181642/312084649-b73ef580-677a-4e46-9d90-a799703aa4d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjM4NjEsIm5iZiI6MTcxMDMyMzU2MSwicGF0aCI6Ii83NzE4MTY0Mi8zMTIwODQ2NDktYjczZWY1ODAtNjc3YS00ZTQ2LTlkOTAtYTc5OTcwM2FhNGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA5NTI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZmM3YTU4NzA5NmVlMWVlNzU4ZDU1MzJiYTlkNjQwMTcyOWE3NDlmNDIzNTIyN2JlMDQ0NjFiZGFmNWUzMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TIU1QuLDn53o-rvhWQ9XADLgry1rm9EwkODwqOD0KbY">
> > 이런 경우들도 괜찮으면 그냥 넘어가도 될 것 같네요~
> 
> 해결했는데 한번 더 확인부탁드립니다.

이모지 잘 막히는거 확인했습니다! 리뷰 마무리 지으려고 하는데 최종 버전이면 말씀해주세요~

2024-03-13 11:07 UTC, khkh0109 commented on src/components/common/Modal/CommonModal/ChangeNicknameModal.tsx
> +function isValidStringIncludingHangulJamo(s) {
s 파라미터에 타입 지정 안해서 any 타입이 지정된다는 문구가 뜹니다~

2024-03-13 11:08 UTC, khkh0109 commented on src/components/common/Modal/CommonModal/ChangeNicknameModal.tsx
> +			a;
여기 a가 잘못 들어간 것 같네요😅

2024-03-13 13:46 UTC, sikkzz requested changes

2024-03-13 13:46 UTC, sikkzz commented on src/pages/CreateAccountPage.tsx
> +								style={{ color: item.state && "black" }}
인라인 스타일링 말고 조건부 스타일로 스타일 파일에서 변경할 수 있지 않을까요?
현재 스타일링 방식처럼 createAccountStyle하나에 묶어서 사용할 시 이런 동적 스타일링을 하려면 최상단으로 빼야한다는 단점이 존재합니다. 상황마다 효율적인 방식으로 골라쓰는게 좋을 거 같네요

2024-03-13 13:48 UTC, sikkzz commented
createAccount page랑 visit Track page 두개 다 폴더 하나 만들어서 컴포넌트, 스타일 파일 넣어서 관리해주세요

CreateAccountPage 디렉토리 안에 컴포넌트 파일, 스타일 파일 존재할 수 있게요 visit track도 동일하구요

2024-03-14 08:13 UTC, pizzaYami commented
> createAccount page랑 visit Track page 두개 다 폴더 하나 만들어서 컴포넌트, 스타일 파일 넣어서 관리해주세요
> 
> CreateAccountPage 디렉토리 안에 컴포넌트 파일, 스타일 파일 존재할 수 있게요 visit track도 동일하구요

네네 준식님 말대로 이건 나중에 onboarding 관련 파일, 폴더 한꺼번에 묶어서 관리할 생각입니다.
지금하면 PR이 더 꼬일 것 같아서 미뤄두고 있습니다.

2024-03-14 10:50 UTC, youngTkim submitted a review, later dismissed

2024-03-14 11:24 UTC, youngTkim approved these changes, later dismissed

2024-03-14 11:49 UTC, khkh0109 approved these changes, later dismissed

2024-03-16 02:43 UTC, closed without merging