[TS-33] Design habit delete page
ConnectingStar/ConnectingStar-Front pull request #46
Opened 2024-03-05 10:47 UTC by sikkzz

[TS-33](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?assignee=712020%3Add928be4-89fa-4c60-9aa8-e0ad8f6b5a7b&selectedIssue=TS-33)

## 💡 변경사항 & 이슈
습관 그만두기 페이지 제작
회원 탈퇴랑 습관 그만두기 컴포넌트 공통화

## ✍️ 관련 설명
습관 그만두기 페이지 제작 후 로직이 회원 탈퇴랑 동일해서 두개 공통화 시켜서 컴포넌트로 제작했습니다.
footer 버튼 onClick 부분만 이후에 api 연결 후 제작하면 될 거 같습니다. (제가 할테니 그때 말씀 드릴게요)
습관 그만두기는 /habit-delete
회원 탈퇴는 동일하게 /withdrawal로 접근시 확인 가능합니다.

## ⭐️ Review point
컴포넌트 이름이 애매해서 현재는 CommonDelete인데 의견 좀 부탁드립니다.
회원 탈퇴, 습관 그만두기 공통 로직인걸 고려해서 고민해봐주세요 (기존: Withdrawal, HabitDelete)

## 📷 Demo
<img width="435" alt="스크린샷 2024-03-05 오후 7 46 21" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/a720d404-984e-44a5-9e57-680ccfabd09a">

2024-03-07 04:03 UTC, khkh0109 commented
공통 컴포넌트 이름은 두 가지 정도 생각났습니다. 

- SelectReason(또는 SelectOption): 두 컴포넌트의 공통점은 사용자의 행동에 대한 이유를 받는 것 같아요(탈퇴하는 이유, 습관을 그만두는 이유). 그래서 이유를 선택한다는 의미인 SelectReason 이라는 이름이 생각났습니다. 
SelectOption은 여러 옵션 중 하나를 선택한다는 의미인데 SelectReason 보다 좀 더 넓은 의미입니다. 

- SubmitReason(또는 SubmitOption): 다른 공통점으로는 어떤 이유나 항목을 선택하고 버튼을 눌러 제출하는것 입니다. 그래서 이유/옵션을 제출한다는 의미에서 Submit~이라는 단어를 붙일 수 있을 것 같아요.

2024-03-07 09:30 UTC, pizzaYami commented
컴포넌트 이름이 애매해서 현재는 CommonDelete인데 의견 좀 부탁드립니다.
 -> CommonQuit 어떠신가여

2024-03-07 09:46 UTC, pizzaYami commented
![스크린샷 2024-03-07 오후 6 46 05](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/1dc0bce7-bec1-4d28-b2a3-8d55a1ffb452)

textarea가 focus될 때 FooterBtn 변경이 되어야 하네요

2024-03-07 10:08 UTC, pizzaYami requested changes

2024-03-07 10:08 UTC, pizzaYami commented on src/components/Home/DeleteReasonModal/DeleteReasonModal.style.ts
> +	height: 25.4375rem;
height: 25.4375rem; 삭제해야겠네요
![스크린샷 2024-03-07 오후 7 04 36](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/bdae5a11-0912-48b5-b85a-5431ab85da90)
![스크린샷 2024-03-07 오후 7 04 29](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/06b67199-0fc8-40aa-bed3-fcc715871ca7)

width: 100%; 도 삭제

2024-03-07 10:08 UTC, pizzaYami commented
LeaveReasonModal이랑 DeleteReasonModal 공통으로 만들어도 될 것 같네요

2024-03-10 10:35 UTC, sikkzz commented
컴포넌트 네임은 SelectReason으로 바꾸고 모달도 공통화 진행했습니다

2024-03-12 09:34 UTC, pizzaYami approved these changes

2024-03-12 13:46 UTC, khkh0109 approved these changes

2024-03-14 10:51 UTC, youngTkim approved these changes

2024-03-14 18:33 UTC, merged