[TS-285] Design chart page
ConnectingStar/ConnectingStar-Front pull request #47
Opened 2024-03-06 10:48 UTC by sikkzz

[TS-285](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?assignee=712020%3Add928be4-89fa-4c60-9aa8-e0ad8f6b5a7b&selectedIssue=TS-285)

## 💡 변경사항 & 이슈
통계 페이지 제작

## ✍️ 관련 설명
브랜치 이름은 week chart인데 chart쪽 작업하다보니 월간 차트도 같이 작업할 수 밖에 없었고 코드량이 좀 길어졌습니다. 이해 부탁드립니다
시안 나안대로 최종 사항이며 api 연결 전까지는 변동 없을 예정입니다. 그러므로 통계 페이지 최종이라 보시면 됩니다

## ⭐️ Review point
기능 구현까지 다 들어가 있는거라 혹시 작동 안하거나 이상한거 있으면 말씀해주세요.
주간 차트쪽 그래프 스와이프 기능 넣을 수 있냐고 요청해주셔서 이건 하게되면 따로 말씀드릴게요 현재는 보류입니다.

## 📷 Demo
<img width="453" alt="스크린샷 2024-03-06 오후 7 36 56" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/f097a714-b1f6-4394-8993-b6fb5cb6dc79">
<img width="446" alt="스크린샷 2024-03-06 오후 7 37 01" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/64e3270c-b4b7-49f3-b232-008c991f716f">
<img width="569" alt="스크린샷 2024-03-06 오후 7 37 05" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/3c6dc2f8-d0d3-46cd-bb7a-52718fb8472f">

2024-03-07 10:52 UTC, pizzaYami commented
![스크린샷 2024-03-07 오후 7 36 29](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/7b914b99-f7bf-41ad-a9c7-a27be9d1598a)

n일 해냈어요 <- 요거 나중에 데이터 들어가면 변경되는거죠?
달력에서 해당 월이 아닌 날짜에 색이 안 들어가야 되지 않나요?

2024-03-10 05:23 UTC, pizzaYami requested changes

2024-03-10 05:23 UTC, pizzaYami commented on src/components/ChartPage/Tab/Tab.style.ts
> +		padding: 0.625rem 0;
padding: 0.9rem 0; 정도로 변경

2024-03-10 05:23 UTC, pizzaYami commented on src/components/ChartPage/WeekChart/WeekChart.style.ts
> +	width: 100%;
여기에
width: 22.5rem;
margin: 0 auto;
넣기 어떤가요?

기존 
![스크린샷 2024-03-07 오후 7 36 29](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/0ec8ae92-dc22-49a7-94e2-5fde49830b59)
변경
![스크린샷 2024-03-07 오후 7 37 12](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/cdc997bf-459d-4331-9a50-015e9a5f7c25)

2024-03-10 05:23 UTC, pizzaYami commented on src/components/ChartPage/WeekChart/WeekChart.style.ts
> +	background-color: ${theme.color.bg};
아아아주 살짝 선이 있는 것 같아요
border-top: 1px solid ${theme.color.line};

2024-03-10 10:37 UTC, sikkzz commented
> ![스크린샷 2024-03-07 오후 7 50 00](https://private-user-images.githubusercontent.com/116322645/310855575-6b8ce87a-51fe-44bf-8f1a-8dbbc3824867.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNjcyNTUsIm5iZiI6MTcxMDA2Njk1NSwicGF0aCI6Ii8xMTYzMjI2NDUvMzEwODU1NTc1LTZiOGNlODdhLTUxZmUtNDRiZi04ZjFhLThkYmJjMzgyNDg2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQxMDM1NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjRhODQ3MmI3MzU2MWYzNmNmMzExZTkzZDQyYjhlNWYxNWUwMTM2N2NiM2RmMzJkYTVmMjkyZTQ3OGRhMWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eFTNSlPTmmRDzeUXx9uD7QfCCq0Ckt4Quw1GrXeXnEA)
> 
> n일 해냈어요 <- 요거 나중에 데이터 들어가면 변경되는지? 달력에서 해당 월이 아닌 날짜에 색이 안 들어가야 할 것 같네요 하단에 이모티콘 별로 숫자도 나중에 변경되는건지?

모든 내용 api 연결하면 변동됩니다. 현재상태에서는 변경시켜봤자 데이터가 연동 안되는 변동 로직밖에 추가가 불가능해요

2024-03-10 10:40 UTC, sikkzz commented on src/components/ChartPage/WeekChart/WeekChart.style.ts
> +	width: 100%;
일부로 width 100%로 잡아놨습니다. 말씀하신대로 변경하면 360이상 디스플레이에서 해당 영역 회색 배경이 아닌 흰색 배경이랑 구분이 생겨버려요 아래 사진처럼요 그럼 매우 어색합니다

<img width="520" alt="스크린샷 2024-03-10 오후 7 40 26" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/0795db37-e299-4e1b-85d3-58c5b91110ee">

2024-03-12 10:45 UTC, pizzaYami commented on src/components/ChartPage/WeekChart/WeekChart.style.ts
> +	width: 100%;
기존코드가 500px이상되면 이상해서 그럴바엔 360px에 맞추는게 낫을 것 같다고 생각되서 권유드렸습니다.
그대로 가셔도 되면 Resolve누르셔도 상관없을 것 같습니다.

2024-03-12 11:23 UTC, sikkzz commented on src/components/ChartPage/WeekChart/WeekChart.style.ts
> +	width: 100%;
모바일 디스플레이 기준 max를 넘어갈 일이 없기에 100%가 맞는거 같습니다. 웹 기준에서는 브레이크가 현재 아무 조건이 없으므로 고려 안하니까요. 이대로 가겠습니당

2024-03-12 12:39 UTC, pizzaYami approved these changes, later dismissed

2024-03-13 00:14 UTC, khkh0109 submitted a review, later dismissed

2024-03-17 06:41 UTC, pizzaYami approved these changes, later dismissed

2024-03-17 08:20 UTC, khkh0109 approved these changes, later dismissed

2024-03-19 10:40 UTC, pizzaYami approved these changes

2024-03-19 10:53 UTC, youngTkim approved these changes

2024-03-19 10:58 UTC, khkh0109 approved these changes

2024-03-19 13:31 UTC, merged