[TS-28] habitRecordPage branch 재생성
ConnectingStar/ConnectingStar-Front pull request #48
Opened 2024-03-06 13:13 UTC by youngTkim

[TS-28](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109/timeline?assignee=712020%3A02c7931e-c3d0-4c29-a401-2c9116a5f760&selectedIssue=TS-28)

## 💡 변경사항 & 이슈
home / habitRecordPage 생성
습관 조건들을 적지 않으면 아래에 있는 항목들과 등록 버튼이 비활성화됩니다.
// habitRecordConstants는 homeConstants와 이후 합치겠습니다.
<br>
// 커밋 히스토리가 꼬여서 다시 PR 보냅니다.

## ✍️ 관련 설명
<br>

## ⭐️ Review point
<br>

## 📷 Demo
<br>

2024-03-10 10:53 UTC, sikkzz requested changes

2024-03-10 10:53 UTC, sikkzz commented on src/components/Home/HabitRecord/HabitRecord.style.ts
> +	& > .identity {
& .classname 이여도 작동해요

2024-03-10 10:53 UTC, sikkzz commented on src/components/Home/HabitRecord/HabitRecord.tsx
> +			</div>
여기 싹다 div로 묶여야할 필요가 없을 거 같은데요 각자 맞는 시멘틱 태그들 쓰는게 맞는 거 같습니다. 그에 따라 css도 수정하시고요

그리고 위에 실천기록 타이틀이 h1인데 그 아래 정체성이 h1태그인건 이상하지 않나요? 태그별로 역할이 나뉘어져 있는 이유가 있으니까요

2024-03-10 10:53 UTC, sikkzz commented on src/components/Home/HabitRecord/HabitRecord.tsx
> +			<section css={conditionStyle}>
section의 영역도 애매해 보입니다. 이부분을 section으로 두신다면 div들도 section을 나눠서 넣어주던가 합치던가 해야하지 않나요?

2024-03-10 10:53 UTC, sikkzz commented on src/components/Home/HabitRecord/StarPrizeModal/StarPrizeModal.style.ts
> +	}
태그 사이에 > 전체 삭제하셔도 됩니다

2024-03-10 10:53 UTC, sikkzz commented on src/components/Home/HabitRecord/HabitRecord.tsx
> +				{habitConditions.map(({ condition, placeholder }: HabitCondition) => (
여기 habitcondition 타입 지정 안해도 돌아갑니다.

그렇다면 저 타입도 types에서 빼서 현재 사용되는 contants에서만 선언해서 사용하면 되겠죠?

2024-03-10 10:54 UTC, sikkzz commented
공백도 컨벤션이라고 말씀드렸었습니다. 코드간 공백 유지 계속 신경써주세요

그리고 태그 사용이 아직 어색한거 같으신데 상황 맞춰가면서 사용해주세요

2024-03-12 12:12 UTC, pizzaYami commented
placeholder에 아무내용 기입하지 않으면 placeholder의 내용 그대로 전달되어야합니다.
현재는 placeholder textarea박스에 내용을 입력해야만 habitIcon을 선택할 수 있는데 unit만 입력해도 선택되게 바뀌어하네요.
Jira에 자세한 내용이 적혀있습니다.

2024-03-12 12:30 UTC, pizzaYami approved these changes

2024-03-12 12:30 UTC, pizzaYami commented on src/components/Home/HabitRecord/HabitRecord.style.ts
> +		padding: 15px;
px

2024-03-12 12:30 UTC, pizzaYami commented on src/components/Home/HabitRecord/HabitRecord.style.ts
> +	gap: 6px;
"나는" 밑과 "했다." 위는 12px간격인데 현재는 6px간격이네요

2024-03-12 12:30 UTC, pizzaYami commented on src/components/Home/HabitRecord/HabitRecord.tsx
> +				{habitConditions.map(({ condition, placeholder }: HabitCondition) => (
이 부분 textarea 한줄로 고정되어야하지 않을까요?
현재는 엔터가 누르면 2줄이되는데 엔터를 누르면 다음 condition으로 넘어가는 기능은 어떠신지

2024-03-12 12:30 UTC, pizzaYami commented on src/components/Home/HabitRecord/HabitRecord.tsx
> +							className={`${habitIcon.id === selectedIcon && "selected"}`}
className={habitIcon.id === selectedIcon ? "selected" : ""}  
	이게 더 깔끔하지 않을까요?

2024-03-12 12:30 UTC, pizzaYami commented on src/pages/HabitRecordPage.tsx
> +			</Header>
헤더 상단 고정입니다.

2024-03-12 12:30 UTC, pizzaYami commented on src/components/Home/Landing/Modal/StarPrizeModal.tsx
> +	}
& > :first-of-type {
		${theme.font.head_a}
		color: ${theme.color.main_blue};
		& .yellow {
			color: ${theme.color.main_yellow};
		}
	}
	blue를 전역으로 넣는 방법도 있습니다.

2024-03-12 12:30 UTC, pizzaYami commented on src/components/Home/Landing/Modal/StarPrizeModal.tsx
> +						<span className="blue">{target.HABIT_RECORD_BLUE_TEXT}</span>
blue를 전역으로 넣으면 className="blue" 지워도됩니다.

2024-03-12 12:30 UTC, pizzaYami commented on src/components/Home/Landing/Modal/StarPrizeModal.tsx
> +
margin-bottom: 8px; 추가

2024-03-12 13:10 UTC, pizzaYami submitted a review, later dismissed

2024-03-12 13:10 UTC, pizzaYami commented on src/components/Home/HabitRecord/HabitRecord.tsx
> +					/>
한줄로 들어가면 textarea보다는 input이 올바른 태그같네요

2024-03-13 01:55 UTC, khkh0109 commented on src/components/Home/HabitRecord/HabitRecord.style.ts
> +			}
`페이지 *` 여기서 `*` 부분을 p 태그로 사용하신 이유가 있을까요? 
'페이지'와 '*'을 가로로 정렬하려고 하신 것 같은데 p 태그 대신 span을 사용하면 `display: inline`을 작성하지 않아도 될 것 같네요

다른 방법으로는 가상요소를 사용하면 동일하게 스타일링을 할 수 있습니다

2024-03-13 01:55 UTC, khkh0109 commented on src/components/Home/HabitRecord/HabitRecord.style.ts
> +	}
여기도 마찬가지로 p 대신 span이나 가상요소를 사용하면 display: inline 코드를 작성하지 않아도 됩니다

2024-03-13 01:55 UTC, khkh0109 commented on src/components/Home/HabitRecord/HabitRecord.tsx
> +						maxLength={4}
혹시 최대 길이를 4로 제한하신 이유가 있을까요? 정책에는 4글자로 제한하라는 내용이 안보여서요!

2024-03-13 01:55 UTC, khkh0109 commented on src/components/Home/HabitRecord/HabitRecord.tsx
> +					/>
이 부분을 터치했을때 숫자 키패드가 보여야 합니다. (정책에도 숫자 키패드가 열려야 한다고 설정되어 있습니다.)
모바일에서 보면 숫자 키패드가 아닌 일반 키패드가 열리네요~
input 태그에서 type과 inputMode를 추가해줘야 할 것 같아요

2024-03-13 01:55 UTC, khkh0109 commented on src/components/Home/HabitRecord/HabitRecord.tsx
> +		unit: 0,
혹시 이 부분 정책이 바뀐건가요? 기본값이 0으로 되어있는데 디자인 시안 및 정책에는 빈 칸으로 되어있습니다~

2024-03-13 02:00 UTC, khkh0109 commented on src/pages/HabitRecordPage.tsx
> +			</Header>
이 부분은 header 컴포넌트에서 전부 변경하겠습니다!

2024-03-13 02:01 UTC, khkh0109 commented on src/components/Home/HabitRecord/HabitRecord.tsx
> +							className={`${habitIcon.id === selectedIcon && "selected"}`}
저도 이 방식이 나은 것 같습니다. 확인해보면 아시겠지만 className을 && 연산자로 부여하면 조건에 맞지 않았을때 "false"라는 이름의 className이 들어가요. 나중에 헷갈릴 여지가 있으니 불필요한 className은 제거하는게 나을 것 같아요

2024-03-17 06:41 UTC, pizzaYami approved these changes, later dismissed

2024-03-18 12:19 UTC, khkh0109 submitted a review, later dismissed

2024-03-19 08:13 UTC, sikkzz requested changes

2024-03-19 08:13 UTC, sikkzz commented on src/components/Home/HabitRecord/HabitRecord.style.ts
> +	}
불필요 코드 아닌가요? gap 6px로 다 지정되어 있으니까요

2024-03-19 08:13 UTC, sikkzz commented on src/components/Home/Landing/Modal/StarPrizeModal.tsx
> +		color: ${theme.color.main_blue};
다른 모달들 스타일링 파일을 내부에 배치한건 스타일링이 간단해서입니다. 스타일링이 여러개 있다면 파일을 분리해서 배치하는게 확인하기 더 용이합니다

2024-03-19 10:39 UTC, youngTkim commented on src/components/Home/HabitRecord/HabitRecord.style.ts
> +	}
아 나는 이랑 했다 부분멘트는 12px로 설정되어있어서 margin을 맞춰서 좀 더 넣었습니다.

2024-03-19 10:58 UTC, youngTkim commented on src/components/Home/Landing/Modal/StarPrizeModal.tsx
> +		color: ${theme.color.main_blue};
넵 분리하겠슴다

2024-03-19 13:28 UTC, sikkzz commented on src/components/Home/Landing/Modal/StarPrizeModal.tsx
> +		color: ${theme.color.main_blue};
StarPirizeModal 디렉토리 만들어서 해주세요

2024-03-19 13:30 UTC, sikkzz commented on src/components/Home/HabitRecord/HabitRecord.style.ts
> +	}
구조가 그럼 나는 + 아이콘, 중간 input들, 했다 이렇게 3개로 나뉘는게 맞는 거 같습니다.

위에 input 3개만 간소화 시키고 아래 input만 남기면 간소화 시키는 이유가 없지 않을까요? 조건이 다르더라도 조건부로 충분히 처리할 수 있는데 지금처럼 빼서 사용할 이유가 없어보여서요 그럼 스타일 코드도 분명 줄어드는 코드가 존재할 거 같네요

참고로 first-of-type, last-of-type 쓰는게 맞습니다. 콘솔 보면 오류도 뜨고요 물론 수정하면 사라질 코드지만요

2024-03-21 07:55 UTC, sikkzz requested changes

2024-03-21 07:55 UTC, sikkzz commented on src/components/Home/HabitRecord/HabitRecord.tsx
> +						<li>
key 값 여기로 옮겨주세요 오류나네요

2024-03-21 07:55 UTC, sikkzz commented on src/components/Home/HabitRecord/HabitRecord.tsx
> +				</span>
h3안에 span이면 몰라도 span안에 h3는 좀 어색하지 않나요?

2024-03-21 10:28 UTC, sikkzz approved these changes

2024-03-22 07:03 UTC, pizzaYami approved these changes

2024-03-23 11:33 UTC, khkh0109 approved these changes

2024-03-23 13:12 UTC, sikkzz commented
rebase 해보시고 머지 하셔야합니다

2024-03-27 11:03 UTC, merged