[TS-64] LocationModal
ConnectingStar/ConnectingStar-Front pull request #52
Opened 2024-03-15 06:26 UTC by pizzaYami

[Ts-64](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?assignee=712020%3A2697805c-34c2-4de5-99cb-4aab5f6d607a&selectedIssue=TS-64)

## 💡 변경사항 & 이슈
/chat 에서 확인가능
장소선택을 위한 모달
데이터는 api연결 후에 FooterBtn을 통해서 전달예정
<br>

## ✍️ 관련 설명
input에 장소를 입력하고 데이터를 전송한다.
selectTagModal가 비슷합니다.
padding: 15px; -> 이거는 px로 하는게 맞습니다. 
<br>

## ⭐️ Review point
input이 width가 100%가 아니고 19.5rem으로 고정해놨는데 둘 중 어느것이 더 낫은지 궁금합니다.
-> selectTagModal은 19.5rem으로 고정해놨습니다.
나중에 components/commmon/Modal의 컴포넌트들과 같은 형식으로 바꿔야할까요?
<br>

## 📷 Demo
![스크린샷 2024-03-15 오후 3 23 36](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/6aba59cc-939c-45c8-a483-031435f3f6e8)

2024-03-16 10:31 UTC, sikkzz requested changes

2024-03-16 10:31 UTC, sikkzz commented on src/components/Chatting/LocationModal.tsx
> +				<Header.CloseButton></Header.CloseButton>
<Header.CloseButton />

2024-03-16 10:31 UTC, sikkzz commented on src/components/Chatting/LocationModalStyle.ts
> +	top: 0;
얘네 넣으신 이유가 따로 있으신가요? 지금 저 설정때문에 일반 웹에서 보이면 구조가 깨지거든요 아래 사진처럼요

<img width="1716" alt="스크린샷 2024-03-16 오후 7 27 24" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/dbb0fda8-f402-4a52-8927-8deaa4258e57">

2024-03-16 10:31 UTC, sikkzz commented on src/components/Chatting/LocationModalStyle.ts
> +	background-color: white;
기본값 transparent여도 상관 없지 않을까 싶네요

2024-03-16 10:31 UTC, sikkzz commented on src/constants/locationModalConstants.tsx
> +	},
id 지우고 key값은 text로 사용하면 될 거 같고 객체가 아니라 배열 형식에 string들만 넣으면 될 거 같아요

2024-03-16 15:01 UTC, pizzaYami commented on src/components/Chatting/LocationModalStyle.ts
> +	top: 0;
position: fixed;
	top: 0;
	left: 0;
	으로 변경했습니다.
	chattingPage위에 올라가는 모달이라 이렇게 설정했습니다.

2024-03-16 15:01 UTC, pizzaYami commented on src/components/Chatting/LocationModalStyle.ts
> +	background-color: white;
동일하게 chattingPage위에 올라가는 모달이라 이렇게 설정했습니다.

2024-03-17 08:14 UTC, sikkzz approved these changes

2024-03-17 09:00 UTC, khkh0109 approved these changes

2024-03-17 12:51 UTC, youngTkim approved these changes

2024-03-18 02:49 UTC, merged