Ts 53/feat/create account page2
ConnectingStar/ConnectingStar-Front pull request #54
Opened 2024-03-16 02:28 UTC by pizzaYami

[TS-53](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?assignee=712020%3A2697805c-34c2-4de5-99cb-4aab5f6d607a&selectedIssue=TS-53)

## 💡 변경사항 & 이슈
/onboarding
기존의 PR이 꼬여서 다시 PR올립니다.
파일,폴더 구조가 조금 변경되었습니다.
OnBoardingPage -> CreateAccount ->ChangeNicknameModal
CreateAccount의 FooterBtn의 disable 조건이 추가되었습니다.
<br>

## ✍️ 관련 설명
onBoardingPage에 CreateAccount파일 포함 채팅가기전에 모든 페이지를 넣을 예정입니다.
<br>

## ⭐️ Review point
😄<br>

## 📷 Demo

![스크린샷 2024-03-16 오전 11 26 53](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/0d748f4c-e7bd-475d-8872-4bbd60d52221)

![스크린샷 2024-03-16 오전 11 27 00](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/4f986ddb-28ac-4dd4-ac4e-9502c9e03f25)

2024-03-16 10:20 UTC, sikkzz requested changes

2024-03-16 10:20 UTC, sikkzz commented on src/components/common/Modal/CommonModal/ChangeNicknameModal.tsx
> +
이렇게 두지말고 util로 하나 빼는게 낫지 않을까요? 여기서만 사용되긴 하더라도 컴포넌트에는 컴포넌트 선언만 있는게 좋은거 같아서요

2024-03-16 10:20 UTC, sikkzz commented on src/pages/OnBoardingPage.tsx
> +		<div>
연결하면서 바꾸시겠지만 빈 태그여도 될 거 같네요

2024-03-17 08:16 UTC, sikkzz approved these changes

2024-03-17 09:12 UTC, khkh0109 approved these changes

2024-03-17 13:05 UTC, youngTkim approved these changes

2024-03-18 03:12 UTC, merged