[TS-25] ChattingPage
ConnectingStar/ConnectingStar-Front pull request #57
Opened 2024-03-20 09:32 UTC by pizzaYami

[JIRA-25](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?assignee=712020%3A2697805c-34c2-4de5-99cb-4aab5f6d607a&selectedIssue=TS-25)

## 💡 변경사항 & 이슈
/chatting에서 확인가능

- userData를 reduxToolkit에 담음 
- ChattingPage 제작
- ChattingMessage 컴포넌트제작
- Progressbar 제작

- 채팅페이지 모달은 다음 PR에 연결예정
- 채팅답변 "미정"으로 된건 모달이랑 연결안해서 넣어둠
- 채팅속도는 조절예정
- **바텀버튼 색이 다르고 배경이 투명한** 것은  bottomBtn컴포넌트의 배경값을 넣도록 수정할 예정이라 변경하지 않았습니다.

## ✍️ 관련 설명

reduxToolkit -> ChattingPage -> Progressbar -> createChatData -> ChattingMessage 순으로 보는게 편합니다.

### reduxToolkit
- 데이터 구성
데이터는 nickName, gender, age, findRoute, habit, identity, time, location, behavior, alert1, alert2 이렇게 들어갑니다.
추가, 수정될 데이터가 있다면 알려주세요.

- userDataSlice의 reducers가 다른 이유
updataBasicUserData, updataHabitUserData 양식이 다른건 전자는 한꺼번에 데이터를 변경해야되고 후자는 데이터를 하나씩 변경할 수 있기 때문입니다.

### ChattingPage
- Header와 Progressbar 같이 있는 이유
둘 다 같이 상단에 붙어야하기 때문에 하나의 태그로 묶었습니다.

- ChattingMessage 무한생성
데이터를 받아서 ChattingMessage컴포넌트를 생성하면서 채팅처럼 보이도록 만들었습니다.
다른 유용한 방식이 있다면 알려주세요

### Progressbar
- 만드는 방식
클릭 필요 수와 현재 클릭 수를 비교해서 %를 알려주는 함수를 통해서 width: n%로 하여서 제작했습니다.

### createChatData
- redux의 userData를 가져와 적용하기 위해 함수로 만들었습니다.

- 마크업형식의 데이터
```
{
			id: "organize",
			message: [`지금까지 나눈 이야기를 정리해 보여드릴게요.`],
			replyBtnMessage: [
				"이 내용이 맞아",
				"정체성 변경",
				"시간 변경",
				"장소 변경",
				"습관 변경",
				"행동 변경",
				"1차 알림 변경",
				"2차 알림 변경",
			],
			reply: `
			<div>
			<div class="allUserData">
				<h2 class="bold">정체성</h2>
				<div>
					<ul>
						<li>정체성</li>
					</ul>
...
```
81번째 줄을 보면 마크업형식의 데이터를 보내는데 아래와 그림과 같이 만들기 위해서 이렇게 제작했습니다.
React에서는 JSX를 사용해서 저런식의 HTML코드는 못 읽지만 
ChattingMessage 88번째 줄 dangerouslySetInnerHTML={{ __html: reply }}를 통해서 읽을 수 있도록 하였습니다.
![스크린샷 2024-03-20 오후 6 19 57](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/09b9448d-67a5-4439-9fa2-e2d975efcb3c)

### ChattingMessage
- 채팅처럼 생성되는 방법
메시지 관련 데이터를 받으면 한꺼번에 보여주지 않고 79번째 줄 message.slice를 통해서 하나씩 잘라붙이면서 보이도록 하였습니다.

- 스크롤다운
77번줄 
```
<div css={chattingStyle.chatWrap} ref={endOfMessagesRef}>
```
endOfMessagesRef는 이 엘리먼트가 변할 때마다 스크롤 다운이 되도록 함수를 만들었습니다.

- 특정 메시지 단어가 색 변하도록 하는 방법
특정 메시지의 단어를 replace와 정규표현식을 통해서 엘리먼트를 붙여서 다시 출력되도록 변경하였습니다.
```
 message.replace(
				/(명확|매력|쉽게|만족)/g,
				(match) => `<span style="color: ${theme.color.main_blue};">${match}</span>`,
			);
```

- 버튼이 1개, 3개, 3개보다 높을 때
각 버튼마다 다른 스타일이 다르게 붙도록 하여서 표현했습니다. 
```	// 하단 버튼이 3개일 때 3개보다 높을 때 디자인을 달리해주는 함수
	const sideBtnStyle = () => {
		if (replyBtnMessage.length === 3) return chattingStyle.sideButton;
		if (replyBtnMessage.length > 3) return chattingStyle.scrollButton;
		return null;
	};
```

## ⭐️ Review point
코드가 좀 복잡해서 관련 설명에 전체적인 코드를 적어놓았습니다.
읽어가면서 코드를 보면 코드의 이해가 조금 쉬울꺼라 생각됩니다.
<br>

## 📷 Demo
![스크린샷 2024-03-10 오후 9 35 10](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/90ab4d16-d204-4e4c-81b4-4a8e1e57ffb7)
<br>

2024-03-20 10:29 UTC, sikkzz requested changes

2024-03-20 10:29 UTC, sikkzz commented on src/api/userDataSlice.ts
user 폴더 만들고 userSlice로 파일명 변경해주세요
RTK는 보통 폴더에 slice와 thunk로 구분해서 관리합니다. 추후에 api 연결하면 userThunk.ts도 생길거니까요

2024-03-20 10:29 UTC, sikkzz commented on src/api/userDataSlice.ts
> +const userDataSlice = createSlice({
const userSlice

2024-03-20 10:29 UTC, sikkzz commented on src/api/userDataSlice.ts
> +	name: "userDate",
name: "user"

2024-03-20 10:29 UTC, sikkzz commented on src/api/userDataSlice.ts
> +	},
여기 로직은 나중에 api 연결하고 리뷰할게요 수정될 여지도 있을꺼고 돌아가는거 확인은 api가지고 하는게 좋으니까요

2024-03-20 10:29 UTC, sikkzz commented on src/api/userDataSlice.ts
> +export default userDataSlice.reducer;
userSlice.actions, userSlice,reducer

2024-03-20 10:29 UTC, sikkzz commented on src/api/store.ts
> +		userData: userDataReducer,
user: userReducer

2024-03-20 10:29 UTC, sikkzz commented on src/api/store.ts
> +import userDataReducer from "@/api/userDataSlice";
얘도 userReducer로 넘어와야겠죠?

2024-03-20 10:29 UTC, sikkzz commented on src/api/userDataSlice.ts
> +	alert2: "오후 10:10",
이게 꼭 전역으로 관리되어야 할 이유가 있을지 아직 의문이네요.

api가 나오고 연결해봐야 알겠지만 온보딩 채팅 과정에서 유저가 입력한 데이터는 마지막에 나도 잘 부탁해 과정에서 api 요청을 통해 서버에 전달될 예정이고 그렇다면 chatting에서만 쓰일 데이터들이라 생각해요.

다른 컴포넌트들에서는 서버에 있는 user data들을 불러와서 사용할꺼니까요. 지금은 내부 페이지에서 그냥 state로 사용해도 되는 상태 같아보이는데 특별히 전역으로 관리해야하는 이유가 있다면 말씀해주세요!

2024-03-20 10:29 UTC, sikkzz commented on src/pages/ChattingPage.tsx
> +				<div css={chattingPageStyle.chattingWrap(isbuttonHeiger)}>
isButtonHeiger가 어떤 명칭일까요? 오타인걸까요?

2024-03-20 10:29 UTC, sikkzz commented on src/pages/ChattingPage.tsx
> +						<Header.PrevButton></Header.PrevButton>
<Header.PrevButton />

2024-03-20 10:29 UTC, sikkzz commented on src/pages/ChattingPage.tsx
> +						></ChattingMessage>
"<ChattingMessage key~... />"

2024-03-20 10:29 UTC, sikkzz commented on src/components/Chatting/Progressbar.tsx
> +			<div></div>
<div />

2024-03-20 10:29 UTC, sikkzz commented on src/components/Chatting/ChattingMessage.tsx
> +						></li>
"<li key~.../>"

2024-03-20 10:29 UTC, sikkzz commented on src/components/Chatting/ChattingMessage.tsx
> +	};
default 스타일을 하나 잡고 인라인에서 조건부 처리하면 될 거 같네요 굳이 이렇게 상단에 함수로 뺄 필요 없어 보입니다.

2024-03-20 10:29 UTC, sikkzz commented on src/components/Chatting/ChattingMessage.tsx
> +					<div css={sideBtnStyle}>
여기서 replyBtnMesaage.length 비교해서 스타일 다른거로 주면 되겠죠?

2024-03-20 10:29 UTC, sikkzz commented on src/components/Chatting/ChattingMessage.tsx
> +	const [isreply, setIsReply] = useState(false);
isReply

2024-03-20 10:29 UTC, sikkzz commented on src/components/Chatting/ChattingMessage.tsx
> +	}, [messageIndex]);
<img width="518" alt="스크린샷 2024-03-20 오후 7 25 47" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/cc7797bc-935d-4134-a49f-0b027a9e9d8c">

통합 가능합니다. 문제 있으면 얘기해주세요

2024-03-20 10:29 UTC, sikkzz commented on src/components/Chatting/ChattingMessage.tsx
> +						<div css={replyStyle} dangerouslySetInnerHTML={{ __html: reply }}></div>
둘다 내부가 빈태그면 닫는 태그로 통일해주세요 너무 많네요 이런 부분들이

2024-03-20 10:29 UTC, sikkzz commented on src/components/Chatting/ChattingMessage.tsx
> +			</div>
이 조건문에 양쪽 결과 차이점이 뭔가요? 조건만 다르고 내부 결과물은 같아보이는데

2024-03-20 10:30 UTC, sikkzz commented
chatting폴더에 각 파일들 컴포넌트랑 스타일파일 폴더 만들어서 관리해주세요

2024-03-20 10:30 UTC, sikkzz commented
<img width="255" alt="스크린샷 2024-03-20 오후 7 18 00" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/a5ea4704-8e71-4346-81a7-0e6f9b621f33">
<img width="380" alt="스크린샷 2024-03-20 오후 7 19 26" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/b90c0389-3458-4d46-8beb-8379283745fb">

사진 둘다 파란 글씨 부분 시안은 굵은 글씨 같은데 디자인이 수정된걸까요? 아니면 안넣으신걸까요 확인 부탁드려요

2024-03-21 09:26 UTC, pizzaYami commented on src/api/userDataSlice.ts
> +	alert2: "오후 10:10",
props가 많아지고 ChattingMessage에서 데이터가 변경되는게 아니라 모달에서 데이터를 변경해야되서 복잡해서 사용했습니다.

ChttingMessage에서 버튼을 누르면 모달이 나타나고 이 모달에서 변경된 데이터를 Modal -> ChattingPage -> ChattingMessage로 다시 왔다갔다하는게 복잡해보여서 사용했습니다.

2024-03-21 09:28 UTC, pizzaYami commented on src/pages/ChattingPage.tsx
> +				<div css={chattingPageStyle.chattingWrap(isbuttonHeiger)}>
higher 로 표현하려고 했는데 오타네요

버튼의 개수가 많아지면 height를 더 높게하는 건데 다른 좋은 이름 없을까요?

2024-03-21 09:30 UTC, pizzaYami commented on src/components/Chatting/Progressbar.tsx
> +			<div></div>
안에 div 태그가 있어야 progressbar가 작동합니다.

2024-03-21 09:31 UTC, pizzaYami commented on src/components/Chatting/ChattingMessage.tsx
> +	};
기본 스타일이랑 더 두가지 스타일해서 총 3가지 스타일이 있어서 함수로 표현했습니다.

2024-03-21 09:37 UTC, pizzaYami commented on src/components/Chatting/ChattingMessage.tsx
> +	};
sideBtn이 아예 없어야하는 경우
sideBtn이 2개인 경우
sideBtn이 3개이상일 경우
3가지 스타일이 들어가서 이렇게 처리했습니다.

2024-03-21 09:37 UTC, pizzaYami commented on src/components/Chatting/ChattingMessage.tsx
> +					<div css={sideBtnStyle}>
동일합니다.

2024-03-21 09:40 UTC, pizzaYami commented on src/components/Chatting/ChattingMessage.tsx
> +	}, [messageIndex]);
```	
useEffect(() => {
  endOfMessagesRef.current?.scrollIntoView({ behavior: "smooth" });
}, [messageIndex]);
```
이렇게 해도 동일한 것 같은데 괜찮아요?

2024-03-21 09:51 UTC, pizzaYami commented on src/components/Chatting/ChattingMessage.tsx
> +			</div>
```
{isReply ? (
					<div css={replyStyle}>{reply}</div>
				) : (
					(id === "alert" || id === "organize") && (
						<div css={replyStyle} dangerouslySetInnerHTML={{ __html: reply }} />
					)
				)}
```
dangerouslySetInnerHTML쓰면 보안에 안 좋다고해서 이렇게 하려고했는데 둘다 넣어버렸네요

2024-03-21 10:17 UTC, sikkzz commented on src/api/userDataSlice.ts
> +	alert2: "오후 10:10",
우선은 확인했습니다. 제가보기에는 추후 백엔드에서 넘어오는 userData들과 비교해서 공통점 확인해보고 많이 다르면 따로 빼는게 나을 거 같아요 현재는 현상태 유지하시면 됩니다

2024-03-21 10:19 UTC, sikkzz commented on src/pages/ChattingPage.tsx
> +				<div css={chattingPageStyle.chattingWrap(isbuttonHeiger)}>
extraMessage는 어떠신가요 message가 많냐 적냐를 구분하는거 같은데 manyMessage나 isManyMessage는 어색한거 같아서

2024-03-21 10:20 UTC, sikkzz commented on src/components/Chatting/Progressbar.tsx
> +			<div></div>
아 텍스트가 십혔네요 div 닫는 태그로 하면 될 거 같아서요 
```
<div />
```

2024-03-21 10:22 UTC, sikkzz commented on src/components/Chatting/ChattingMessage.tsx
> +	}, [messageIndex]);
옵셔널 연산자는 안쓰는게 좋습니다. 그래서 일부로 코드가 늘어나도 없을 시 return문 코드가 들어가는겁니다

옵셔널 연산자를 막쓰면 디버깅 할 때나 렌더링 과정에서 어디서 어떻게 오류가 생겼는지 모르는 경우가 많아지기 때문에 확실하게 걸러주는게 좋습니다

2024-03-21 10:24 UTC, sikkzz commented on src/components/Chatting/ChattingMessage.tsx
> +	};
sideButton, scrollButton 두개의 스타일링만 boolean 값으로 비교해서 넣어주고,
sideBtn이 아예 없어야 하는 경우는따로 처리해줘야 하는게 맞는 거 같네요.

그렇게 수정하면 함수 따로 필요 없이 스타일링 조건으로만 처리 가능할 거 같은데 맞을까요?

2024-03-21 12:45 UTC, pizzaYami commented on src/pages/ChattingPage.tsx
> +				<div css={chattingPageStyle.chattingWrap(isbuttonHeiger)}>
extraBtnHeight로 변경했습니다.

2024-03-21 12:49 UTC, pizzaYami commented on src/components/Chatting/ChattingMessage.tsx
> +	};
```
<div
						css={
							replyBtnMessage.length === 3
								? chattingStyle.sideButton
								: replyBtnMessage.length > 3
									? chattingStyle.scrollButton
									: null
						}
					>
```
요렇게 변경하겠습니다.

2024-03-21 15:06 UTC, youngTkim approved these changes, later dismissed

2024-03-21 16:09 UTC, sikkzz commented on src/components/Chatting/ChattingMessage.tsx
> +	};
이렇게 하면 함수로 뺀거랑 다를게 없습니다. 제가 말씀드리는 방식은 뭐냐면

우선 제가 이해하는게 맞다면 length === 3인 경우는 1차 알림 변경, 2차 알림 변경 버튼이 렌더링 될떄고 length > 3 인 경우는 정체성 변경, 시간 선택 등 여러 버튼들이 뜨는 케이스라고 봤는데 맞을까요?

이 두케이스 이외에는 저 div 코드가 렌더링 될 필요가 없는거 아닌가요? 그렇다면 렌더링 시키는 조건과 안시키는 조건 이렇게 한번 분리하고 렌더링 시킬때는 내부에서 length 값에 따라 boolean으로 구분해주면 될 거 같아서 말씀 드리는 겁니다.

그럼 인라인은 저 코드 상단에 렌더링 조건 코드랑 해당 코드에서 인라인 스타일링은 1줄로 정리되는거 같아서요

2024-03-22 04:03 UTC, pizzaYami commented on src/components/Chatting/ChattingMessage.tsx
> +	};
우선 제가 이해하는게 맞다면 length === 3인 경우는 1차 알림 변경, 2차 알림 변경 버튼이 렌더링 될떄고 length > 3 인 경우는 정체성 변경, 시간 선택 등 여러 버튼들이 뜨는 케이스라고 봤는데 맞을까요?
-> 맞습니다.

```
<div>
					{replyBtnMessage.length > 1 && (
						<div
							css={
								replyBtnMessage.length === 3 ? chattingStyle.sideButton : chattingStyle.scrollButton
							}
						>
							{replyBtnMessage.slice(1).map((item) => (
								<button key={item}>{item}</button>
							))}
						</div>
					)}
					<FooterBtn text={replyBtnMessage[0]} handleBtnClick={handleReplyBtn} isTransparent />
				</div>
```
이런식의 코드를 원하시는게 맞은신가요?

```
{replyBtnMessage.slice(1).map((item) => (
    <button key={item}>{item}</button>
))}
```
이 부분때문에 답글버튼이 1개일때 div부분이 렌더링이 안되길래 기존의 코드처럼 짰던건데 뭐가 더 좋은건지는 잘 모르겠네요

2024-03-22 07:33 UTC, sikkzz commented on src/components/Chatting/ChattingMessage.tsx
> +	};
코드 동작상 문제가 없는거로 보면 될까요? 혹시 문제가 있다면 알려주세요 해결 방법 같이 찾아드릴게요 문제 없으면 resolve 해주세요

2024-03-24 05:11 UTC, khkh0109 commented
모바일에서 이미지 가로 사이즈가 줄어드네요..!
<img width="300px" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/d4f3ffd0-ad54-42d8-b19d-845cf72ab407" />

2024-03-24 05:17 UTC, khkh0109 commented on src/components/Chatting/Progressbar.tsx
> +		</div>
혹시 html progress 요소 아시나요? 이 요소 사용하면 프로그레스 바를 좀 더 쉽게 만들 수 있을것 같아요 퍼센트 계산하는 함수도 필요없을것 같구요
근데 저도 문서에서만 본거라 그냥 단순 제안입니다,, 😊

2024-03-24 07:07 UTC, pizzaYami commented on src/components/Chatting/Progressbar.tsx
> +		</div>
처음들어봤는데 찾아보고 적용해볼게요

2024-03-25 07:22 UTC, pizzaYami commented
> 모바일에서 이미지 가로 사이즈가 줄어드네요..! <img alt="" width="300px" src="https://private-user-images.githubusercontent.com/77181642/316284651-d4f3ffd0-ad54-42d8-b19d-845cf72ab407.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTE2MzksIm5iZiI6MTcxMTM1MTMzOSwicGF0aCI6Ii83NzE4MTY0Mi8zMTYyODQ2NTEtZDRmM2ZmZDAtYWQ1NC00MmQ4LWIxOWQtODQ1Y2Y3MmFiNDA3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3MjIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMmEwMWMwOGI4YzNjZjkyNjI4YjNkZmMxMjU0YzNjMDQ0OTI3MTNhYTVmMjRhYjM3YjQxNmJmNWNlZjQ0NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CN26fr0bLbJoM0jhKupqmRWqYNeNPXU1vQtsmFjkpTY">

제가 확인했을때는 괜찮은데 혹시 애플 쓰시나요?

2024-03-25 07:27 UTC, khkh0109 commented
> > 모바일에서 이미지 가로 사이즈가 줄어드네요..! <img alt="" width="300px" src="https://private-user-images.githubusercontent.com/77181642/316284651-d4f3ffd0-ad54-42d8-b19d-845cf72ab407.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTE2MzksIm5iZiI6MTcxMTM1MTMzOSwicGF0aCI6Ii83NzE4MTY0Mi8zMTYyODQ2NTEtZDRmM2ZmZDAtYWQ1NC00MmQ4LWIxOWQtODQ1Y2Y3MmFiNDA3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3MjIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMmEwMWMwOGI4YzNjZjkyNjI4YjNkZmMxMjU0YzNjMDQ0OTI3MTNhYTVmMjRhYjM3YjQxNmJmNWNlZjQ0NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CN26fr0bLbJoM0jhKupqmRWqYNeNPXU1vQtsmFjkpTY">
> 
> 제가 확인했을때는 괜찮은데 혹시 애플 쓰시나요?

네 애플사용합니다

2024-03-25 11:48 UTC, sikkzz approved these changes

2024-03-25 12:30 UTC, khkh0109 approved these changes

2024-03-25 13:05 UTC, youngTkim approved these changes

2024-03-25 20:28 UTC, merged