[TS-276] 별자리 메인 페이지 UI (별자리 캐릭터 제외)
ConnectingStar/ConnectingStar-Front pull request #58
Opened 2024-03-21 07:30 UTC by khkh0109

[TS-276](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?selectedIssue=TS-276)

## 💡 변경사항 & 이슈
별자리 메인 페이지 UI 작업

<br>

## ✍️ 관련 설명
별자리 메인 페이지 UI 작업을 했습니다. 중앙에 있는 별자리는 다른 브랜치에 올릴 예정입니다. 
/star 경로에서 확인할 수 있습니다.

### ESLint import order 규칙 추가 
- framer motion을 사용했는데 관련 룰이 없길래 추가했습니다. 이렇게 추가 하는게 맞는지 확인 부탁드려요 

### 스타일 관련
- 텍스트 외곽선 스타일은 data-*와 가상 요소를 사용해서 스타일링 하고 있습니다. 더 괜찮은 방법 있다면 말씀해 주세요. 
- 참고: 디자인 시안 상 텍스트 아웃라인은 2px 입니다. 하지만 2px로 적용하면 얇아보여서 조금 더 두껍게 적용했습니다. 디자인 시안과 달라보인다면 말씀해 주세요.
  <details>
    <summary>시도한 방법</summary>
    <ul>
        <li>
            <strong>-webkit-text-stroke</strong>
            <br />
           <code>-webkit-text-stroke: 2px ${theme.color.main_deep_blue};</code>
            <br />
           <img width="200" alt="스크린샷 2024-03-21 오후 4 00 06" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/323facfb-e4ca-42af-a179-e84dcdbe8747">
        </li>
        <li>
            <strong>text-shadow</strong>
            <br />
           <code>text-shadow: 2px 0 0 ${theme.color.main_deep_blue}, 0 2px 0 ${theme.color
			.main_deep_blue}, -2px 0 0 ${theme.color.main_deep_blue}, 0 -2px 0 ${theme.color
			.main_deep_blue};</code>
            <br />
           <img width="200" alt="스크린샷 2024-03-21 오후 4 02 49" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/181bd255-dd0c-4afa-b2e7-4513dbc51c30">
        </li>
    </ul>
  </details>

### 별 배경 관련
- 별 배경은 svg를 생성해서 만들었습니다. 
  - 별 위치, 크기, 지속시간 랜덤
  - 화면 아래로 갈수록 별이 투명해짐
  - 리렌더링 될때마다 별 배경이 바뀌는데 추후 useMemo나 memo를 추가해서 고정시킬 예정 (다른 브랜치에서 적용 예정)
- generateStars와 Star prop의 cr(원 중심 x 좌표), cy(원 중심 y 좌표), r(원 반지름)은 svg circle의 어트리뷰트 이름을 그대로 따왔습니다. 고민하다가 그냥 원래 어트리뷰트 이름과 동일하게 작명했는데 알아보기 힘들다면 다른 이름을 생각해 보겠습니다.  
- svg 별 배경 및 그라데이션 배경의 width는 글로벌 스타일 max-width와 동일하게 500px로 고정했습니다. 
- svg 별 배경 및 그라데이션 배경의 height의 단위는 100dvh 입니다. vh로 했더니 모바일에서 아래처럼 보이는게 이상해서 dvh로 변경했습니다. 
  <img src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/2ac71534-91de-4f9d-9276-250485bf964e" width="200px"/>

<br>

## ⭐️ Review point
- [ ] ESLint import order 규칙 추가하는 방법 맞는지
- [ ] cx, cy, r 이름 통일했는데 알아보기 어렵지 않은지 
- [ ] 디자인과 다른 부분 없는지
- [ ] 기타 더 괜찮은 방법 있는지

확인 부탁드립니다~

<br>

## 📷 Demo
<img width="367" alt="스크린샷 2024-03-21 오후 4 23 58" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/4c7f6d34-f754-42ae-98f2-c0f12467000b">

<br>

2024-03-21 08:04 UTC, sikkzz requested changes

2024-03-21 08:04 UTC, sikkzz commented on src/components/StarPage/StarMain/StarButton.tsx
> +				<img src={starButton} alt="" />
alt값이 비어있는 이유가 있나요?

2024-03-21 10:32 UTC, khkh0109 commented on src/components/StarPage/StarMain/StarButton.tsx
> +				<img src={starButton} alt="" />
적당한 alt 값이 생각나지 않아서 비워두었습니다. 혹시 괜찮은 값 있을까요? 
지금은 별 채우기 버튼, 중앙에 별이 있는 원형 버튼..? 이정도가 생각나네요,,

2024-03-21 10:44 UTC, sikkzz commented on src/components/StarPage/StarMain/StarButton.tsx
> +				<img src={starButton} alt="" />
영어로 하실꺼면 그대로 starButton 한글로 하실꺼면 별모양버튼 정도 하시면 될 거 같아요

2024-03-21 10:48 UTC, sikkzz commented
대부분 컴포넌트 간단해서 현재는 스타일링 파일 같은 파일에 배치해도 괜찮지만 추후에 api 연결하고 파일 내용 길어주면 스타일 파일 따로 빼주세요.

그리고 getOutlineTextStyle파일은 어떻게보면 저희 파일 컨벤션이랑 안맞기도 해서 Star.style.ts 정도로 빼는게 좋을 거 같아요. 그럼 어차피 스타일 파일이 만들어지니 뺼 수 있는 애들은 빼서 써도 될 거 같아서요

2024-03-21 10:52 UTC, sikkzz commented
그리고 이후에 좀 걱정인게 저 많은 별모양들이 렌더링되고 있는거랑 계속 값이 변동하면서 작동하고 있는데 성능적으로 문제 없을지 좀 걱정이네요

https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/8256baf8-d6b9-4af3-a894-c70473d0c2e8

2024-03-21 11:27 UTC, khkh0109 commented
> 그리고 이후에 좀 걱정인게 저 많은 별모양들이 렌더링되고 있는거랑 계속 값이 변동하면서 작동하고 있는데 성능적으로 문제 없을지 좀 걱정이네요
> 
>  2024-03-21.7.52.06.mov

나중에 이것저것 더 추가되면 그럴 수 있겠네요 
문제 없을지 테스트 하고 더 알아보겠습니다

2024-03-22 07:18 UTC, pizzaYami requested changes

2024-03-22 07:18 UTC, pizzaYami commented on src/components/StarPage/StarMain/StarBackground.tsx
> +	width: 500px;
rem

2024-03-22 07:18 UTC, pizzaYami commented on src/components/StarPage/StarMain/StarButton.tsx
> +				<img src={starButton} alt="" />
star-Button-Icon?

2024-03-23 10:53 UTC, khkh0109 commented on src/components/StarPage/StarMain/StarButton.tsx
> +				<img src={starButton} alt="" />
한글로 하겠습니다~

2024-03-23 11:01 UTC, khkh0109 commented on src/components/StarPage/StarMain/StarBackground.tsx
> +	width: 500px;
여기도 rem으로 해야할까요? 글로벌 스타일의 max-width 500px과 통일시킨다고 px단위를 적용했습니다. 
rem으로 하면 가장 바깥의 가로는 고정되어 있는데 별 배경 부분만 고정값이 아니라 좀 어색해지더라구요

2024-03-23 11:32 UTC, khkh0109 commented
> 대부분 컴포넌트 간단해서 현재는 스타일링 파일 같은 파일에 배치해도 괜찮지만 추후에 api 연결하고 파일 내용 길어주면 스타일 파일 따로 빼주세요.
> 
> 그리고 getOutlineTextStyle파일은 어떻게보면 저희 파일 컨벤션이랑 안맞기도 해서 Star.style.ts 정도로 빼는게 좋을 거 같아요. 그럼 어차피 스타일 파일이 만들어지니 뺼 수 있는 애들은 빼서 써도 될 거 같아서요

이 부분도 반영했습니다

2024-03-23 13:11 UTC, sikkzz approved these changes

2024-03-24 07:08 UTC, pizzaYami commented on src/components/StarPage/StarMain/StarBackground.tsx
> +	width: 500px;
음 생각해보니깐 rem으로 하면 화면이 커지니깐.
px로 고정되는게 맞겠네요

2024-03-24 07:08 UTC, pizzaYami approved these changes

2024-03-28 14:00 UTC, youngTkim approved these changes

2024-03-29 11:44 UTC, merged