[TS-190] habitShelfPage
ConnectingStar/ConnectingStar-Front pull request #59
Opened 2024-03-21 10:09 UTC by youngTkim

[TS-190](https://m2jun.atlassian.net/browse/TS-190)

## 💡 변경사항 & 이슈
휴식 기록과 실천 기록 조회하는 것을 mode에 따라서 확인할 수 있도록 만들었습니다.
패스는 home/:id 로 임시로 만들었는데 해당 날짜의 해당 기록을 확인하는 거라 나중에 바뀔 수도 있을 것 같습니다.

휴식일 때는 별자취 남기기만 뜨고, 실천일 때는 정체성 / 시간, 위치, 행동, 단위 / 아이콘 부분이 나옵니다.
<br>

## ✍️ 관련 설명
<br>

## ⭐️ Review point
<img width="325" alt="스크린샷 2024-03-21 오후 6 52 40" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/117588223/2c22f685-1fd2-43ed-b8b8-e225a904b49e">
<br>

## 📷 Demo
<br>

2024-03-21 10:41 UTC, sikkzz requested changes

2024-03-21 10:41 UTC, sikkzz commented on src/App.tsx
> +				<Route path="/home/:id" element={<HabitShelfPage />} />
변경 했다고 말씀 드렸습니다

2024-03-21 10:41 UTC, sikkzz commented on src/components/Home/HabitShelf/HabitShelf.tsx
> +		<>
삭제

2024-03-21 10:41 UTC, sikkzz commented on src/components/Home/HabitShelf/HabitShelf.style.ts
> +	padding: 1.25rem 1.5rem 5.438rem 1.5rem;
padding: 1.25rem 1.5rem 5.438rem;

2024-03-21 10:41 UTC, sikkzz commented on src/components/Home/HabitShelf/HabitShelf.style.ts
> +`;
미사용 아닌가요?

2024-03-21 10:41 UTC, sikkzz commented on src/components/Home/HabitShelf/HabitShelf.tsx
> +					<>
div로 묶고 각 단위별 gap 40px로 동일하게 구성하면 될 거 같아 보입니다. 

항상 말씀드리지만 tag를 상황에 맞게 쓰셔야 하고 보통 디자인할 때 일부로 단위별로 디자인 하는 이유가 개발할 때 편하라고 하는겁니다. 같은 묶음으로 가져가야하는 요소들을 디자인 보시면서 생각하는 연습이 좀 필요하실 거 같네요

2024-03-21 10:41 UTC, sikkzz commented on src/components/Home/HabitShelf/HabitShelf.tsx
> +						</label>
label tag쓸 이유가 없죠?

2024-03-21 10:41 UTC, sikkzz commented on src/components/Home/HabitShelf/HabitShelf.tsx
> +						</section>
여기가 section일 이유도 없습니다

2024-03-21 10:41 UTC, sikkzz commented on src/components/Home/HabitShelf/HabitShelf.tsx
> +							</ul>
여기도 리스트로 묶여있어야할 이유가 없구요

2024-03-22 07:46 UTC, pizzaYami requested changes

2024-03-22 07:46 UTC, pizzaYami commented on src/components/Home/HabitShelf/HabitShelf.tsx
> +							<h2>{`정체성\n\n`}</h2>
\n\n로 height를 맞춘 이유가 있을까요?

2024-03-22 07:46 UTC, pizzaYami commented on src/components/Home/HabitShelf/HabitShelf.style.ts
> +	}
h2, h3를 분리해서 사용하지 말고 h2로 통일을 하는 방법 또는 이 부분만 class로 표현하는 방법 둘 중 하나를 사용하면 좋겠네요

2024-03-22 07:46 UTC, pizzaYami commented on src/components/Home/HabitShelf/HabitShelf.tsx
> +					<>
css 구분을 위해서 태그를 다르게 하시는 것 같은데 태그마다 쓰임새가 다릅니다.

https://tcpschool.com/html-tags/intro

2024-03-22 07:46 UTC, pizzaYami commented on src/components/Home/HabitShelf/HabitShelf.tsx
> +					<>
저도 코드를 읽다보니 css를 위해서 태그를 다르게 하시는 것 같습니다.

https://tcpschool.com/html-tags/intro

2024-03-28 06:31 UTC, sikkzz requested changes

2024-03-28 06:31 UTC, sikkzz commented on src/components/Home/HabitShelf/HabitShelf.tsx
> +						{`매일 성장하는 사람`}
얘는 p나 span으로 묶는게 맞지 않을까요? 안빼셔도 될 거 같았는데

2024-03-28 06:31 UTC, sikkzz commented on src/components/Home/HabitShelf/HabitShelf.tsx
> +							<div>5페이지</div>
얘네도 p나 span이 알맞습니다

2024-03-28 06:31 UTC, sikkzz commented on src/components/Home/HabitShelf/HabitShelf.tsx
> +				<div>오늘은 목표량을 잘 달성하여 뿌듯하다! 앞으로도 열심히 해야겠다.</div>
얘도 p태그

2024-03-28 16:47 UTC, pizzaYami submitted a review, later dismissed

2024-03-29 07:36 UTC, sikkzz requested changes

2024-03-29 07:36 UTC, sikkzz commented on src/components/Home/HabitShelf/Condition.tsx
습관 실천했을때 컴포넌트인데 그에 맞는 이름으로 써야하지 않을까요?

2024-03-31 02:35 UTC, pizzaYami approved these changes, later dismissed

2024-04-02 10:56 UTC, khkh0109 commented on src/App.tsx
> +import HabitDetailPage from "@/pages/HabitDetailPage";
여기 ESLint import order룰 에러 발생하지 않으셨나요? 코드 실행하니까 룰 에러가 발생하네요!

2024-04-03 09:45 UTC, youngTkim commented on src/App.tsx
> +import HabitDetailPage from "@/pages/HabitDetailPage";
아 fix하니까 바로 정렬되었네여

2024-04-03 11:49 UTC, pizzaYami submitted a review, later dismissed

2024-04-03 12:27 UTC, sikkzz requested changes

2024-04-03 12:27 UTC, sikkzz commented on src/components/Home/HabitDetail/Action.tsx
HabitActionRecord가 좋을 거 같아요

2024-04-04 08:04 UTC, sikkzz approved these changes

2024-04-04 09:28 UTC, pizzaYami approved these changes

2024-04-04 11:24 UTC, khkh0109 approved these changes

2024-04-06 13:04 UTC, merged