[TS-206] Style: ThemeProvider 업데이트
ConnectingStar/ConnectingStar-Front pull request #6
Opened 2024-01-26 06:33 UTC by youngTkim

[TS-206](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109/backlog?selectedIssue=TS-206)

## 💡 변경사항 & 이슈
 theme.ts의 공통 font-weight, font-size, color, background-color 설정
// 추가적으로 와이어프레임 Home.ts

## ✍️ 관련 설명
figma의 디자인 시스템 안에 정해둔 폰트와 배경을 각각 rem, rgba로 설정 
// 1rem = 16px

## ⭐️ Review point
<br>

## 📷 Demo
<br>

2024-01-27 11:01 UTC, sikkzz requested changes

2024-01-27 11:01 UTC, sikkzz commented on src/styles/theme.ts
영택님이 설정하신 방식대로면 font 테마는 적용시 prop으로 따로 넘겨줘서 적용시켜야 합니다. 보편적으로 사용하는 아래 사진 방식으로는 적용이 불가능합니다. color 또한 저렇게 적용시키시려는 이유가 따로 있을까요? 제가 보여드리는 예시대로 작성하시는게 낫지 않을까요?
<img width="376" alt="KakaoTalk_20240127_194931338_01" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/94a1f695-f92f-4f35-94be-d2d71112f1a2">
<img width="512" alt="KakaoTalk_20240127_194931338" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/647c1809-3a3d-45b1-a3a9-c9adfec0a61e">

2024-01-27 11:01 UTC, sikkzz commented on src/components/Home/Home.tsx
해당 브랜치 테마 적용 브랜치이므로 home 코드는 브랜치 새로 파서 작성하시는게 좋을 거 같아요. 해당 코드들 제거 부탁드려요.

이후 pr에 올라와도 리뷰 드리겠지만 미리 몇가지 리뷰 드릴게요

1. 클래스네임 전체 제거 -> emotion css로 스타일링시 자동으로 동적 클래스 네임이 생성됩니다. 불필요할 거 같네요
2. 스타일 파일 따로 작성 -> 저번 회의때 간단히 말씀드렸듯 인라인으로 스타일 작성시 코드가 길어져서 코드 확인이 어려움이 있습니다.
3. 해당 코드 실행시켜보면 max-width가 현재 500으로 설정했으므로 width 100% 작성시 500px 기준 100%로 적용됩니다. 확인해보시고 수정하셔야 할 거 같네요
4. flex를 너무 남발하는거도 좋지 않습니다. 분명 flex없이 작성 가능한 코드들이 많은데 굳이 코드를 여러줄 추가시키는건 불필요할 거 같아요
5. li태그쪽 코드 보시면 다 통일한 스타일인데 위에서 말씀드렸듯 파일로 작성해서 import해서 사용하면 한번의 스타일 코드로 전체 적용시킬 수 있습니다.

상세 코드별 리뷰는 추후에 PR올라오면 다시 해드릴게요 해당 내용 인지만 해주시고 나중에 수정할때 참고 해주세요

2024-01-27 11:01 UTC, sikkzz commented on src/components/Home/Home.tsx
해당 코드 제거하고 커밋 넣어주세요

2024-01-27 11:01 UTC, sikkzz commented on src/App.tsx
여기 코드도 제거하고 커밋 부탁드려요. 브랜치와 불필요한 코드 같네요. 추가적으로 APP코드에는 라우팅 관련 정보들이 들어가야해서 저렇게 작성하시면 안될 거 같고 page 따로 작성해서 넣어주어야 합니다. 

코드 제거 부탁드려요

2024-01-28 14:23 UTC, khkh0109 commented on src/styles/globalStyle.ts
> +	@font-face {
폰트 설정이 제대로 안된것 같은데 다시 확인부탁드립니다!

2024-01-29 12:28 UTC, pizzaYami commented
왜 안되냐

2024-01-30 09:35 UTC, closed without merging