[TS-65]BehaviorModal
ConnectingStar/ConnectingStar-Front pull request #61
Opened 2024-03-25 09:24 UTC by pizzaYami

[TS-65](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?assignee=712020%3A2697805c-34c2-4de5-99cb-4aab5f6d607a&selectedIssue=TS-65)

## 💡 변경사항 & 이슈
/chattting 에서 확인가능
- behavior 데이터 redux에 보내는 건 chattingPage merge후 진행예정

<br>

## ✍️ 관련 설명
- modal열리면 숫자input에 focus -> autoFocus 사용
- 숫자input에서 "다음"버튼누르면 단위입력에 포커스 -> useRef사용

### button disable 세팅
1. 숫자 또는 단위 하나만 입력했을 때 다음버튼이 활성화
2. 다음 버튼 누르면 확인 버튼으로 변경
3. 숫자와 단위 둘 다 입력되면 확인버튼 활성화

<br>

## ⭐️ Review point
입력 시 어색한 부분
피그마와 다른 부분
사용되지 않아 삭제되어야 할 코드

<br>

## 📷 Demo
![스크린샷 2024-03-25 오후 6 24 02](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/7c9c1519-72dc-49aa-8e1d-9ae6f92c282c)

2024-03-28 06:27 UTC, sikkzz requested changes

2024-03-28 06:27 UTC, sikkzz commented on src/components/Chatting/BehaviorModal.tsx
> +import React, { useRef, useState } from "react";
React 삭제

2024-03-28 06:27 UTC, sikkzz commented on src/components/Chatting/BehaviorModal.tsx
> +import Modal from "../common/Modal/Modal";
절대경로

2024-03-28 06:27 UTC, sikkzz commented on src/components/Chatting/BehaviorModal.tsx
> +	);
이게 기획 부분에서 다음 버튼이 꼭 필요한가요? 양쪽 인풋 값이 다 채워지면 그냥 확인 버튼 enable 시키는거로 통일하는게 안되는 이유가 있는지 궁금합니다. 

현재 상태에서 인풋 두개를 다 채우고 다음 버튼을 누르고 확인 버튼까지 눌러야 하다보니 의미 없는 비효율적인 작업이 한번 들어가는 느낌이라서요

2024-03-28 09:45 UTC, pizzaYami commented on src/components/Chatting/BehaviorModal.tsx
> +	);
이거 기획단에 물어볼게요

2024-03-29 07:37 UTC, sikkzz approved these changes

2024-03-29 11:53 UTC, khkh0109 approved these changes

2024-04-01 09:06 UTC, youngTkim approved these changes

2024-04-01 10:14 UTC, merged