[TS-30] habitGeneratePage
ConnectingStar/ConnectingStar-Front pull request #62
Opened 2024-03-28 08:26 UTC by youngTkim

[TS-30](https://m2jun.atlassian.net/browse/TS-30)

## 💡 변경사항 & 이슈
/habit-generate
연결된 모달들은 임시로 settimeout으로 화면에 뜨고 꺼지게 만들어뒀습니다.
주석 처리된 부분들은 이후 selectTimeModal에 사용될 부분입니다.

useState로 관리되는 모달들은 함수를 따로 props를 받지 않고 있기때문에 setTimeout을 통해 임시로 꺼지게 만들어 뒀습니다.
이후 redux modal로 바뀌면 그거에 맞춰서 수정하겠습니다.

바로 merge하지 않고 중간에 올린 것이니 디자인을 봐주시면 될 거 같습니다.
<br>

## ✍️ 관련 설명
 부가적으로 주어지는 설명이나 주석에 따라서 스타일이 바뀌게끔 만들었습니다.
handleClick을 통해서는 modal의 변경, 또 modal에 들어갈 props를 변경하는 기능으로 만들었습니다.
<br>

## ⭐️ Review point
디자인이 피그마와 다른 부분, 코드를 줄일 수 있는 부분
<br>

## 📷 Demo
<br>

2024-03-28 17:28 UTC, pizzaYami requested changes

2024-03-28 17:28 UTC, pizzaYami commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +} from "@/components/Home/HabitGenerate/HabitGenerate.style";
style이 에러생기는데 HabitGenerate.Style을 -> style로 변경해야합니다.

2024-03-28 17:28 UTC, pizzaYami commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +import StarImage from "@/assets/image/img-card-detail-star-button.png";
피그마에 프로필 이미지 나왔는데 그걸로 변경해야겠네요

2024-03-28 17:28 UTC, pizzaYami commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +					<img src={StarImage} alt="임시" />
- 피그마 새로운 이미지 넣기
- alt="임시" 
-> 이미지 안 나왔을 때 나오는 텍스트 또는 시각장애인이 이미지 선택했을 때 읽어주는 텍스트라서 "임시"보단 profile이 올바르네요

2024-03-28 17:28 UTC, pizzaYami commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +						<span>{`반가워요 {닉네임}님!\n`}</span>
<span> 넣어서 \n 넣는 것보다는 div나 h관련된 태그 넣는게 좋아보이네요

2024-03-28 17:28 UTC, pizzaYami commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +								<span>{`1. 일단 쉬워야 해요.\n`}</span>
span 변경
\n 제거

2024-03-28 17:28 UTC, pizzaYami commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +								<span>{`2. 만족스럽기까지 하면 최고!\n`}</span>
span 변경
\n 제거

2024-03-28 17:28 UTC, pizzaYami commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +				{habitGenerateConditions.map((condition) => {
여기 값들 대문자 넣으신 이유가 있을까요?
단순히 궁금해서 그렇습니다.

2024-03-28 17:28 UTC, pizzaYami commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +						<li key={SUBTITLE_TEXT} onClick={() => handleClick(MODAL_NAME, PLACE_TEXT)}>
SUBTITLE_TEXT 눌러도 모달뜨고 있는데
handleClick 부분이 li 전체보단 PLACE_TEXT부분만 적용해야합니다.

2024-03-28 17:28 UTC, pizzaYami commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +			<FooterBtn text="좋아, 이대로 만들게" isPositionStatic />
disable 넣고 나중에 값이 다 들어갔을 때만 disable이 풀리도록 하는 로직을 짜야겠네요

2024-03-28 17:28 UTC, pizzaYami commented on src/components/Home/HabitGenerate/HabitGenerate.Style.ts
> +	padding: 0.46875rem;
img가 좌측에 너무 붙어있네요.
피그마상12px인데 현재는 7.5px입니다.

2024-03-29 12:40 UTC, khkh0109 commented on src/components/Home/HabitGenerate/HabitGenerate.Style.ts
> +	height: 5.9375rem;
여기 세로 길이를 지정하신 이유가 있을까요? 
특별한 이유가 없다면 height를 삭제하고 padding만 사용하는건 어떠신가요? 

padding으로 여백을 조정하면 내부 콘텐츠의 세로 길이가 늘어났을때 height 조정을 하지 않아도 자동으로 늘어나고, 나중에 profileBox의 상하 여백 수정 요청이 들어왔을때 쉽게 수정할 수 있다는 장점이 있어요.

2024-03-29 12:54 UTC, khkh0109 commented on src/components/Home/HabitGenerate/HabitGenerate.Style.ts
> +		width: 6.875rem;
가로, 세로 사이즈가 디자인 시안과 다릅니다. 디자인은 111 x 36인데 화면에는 110 x 40으로 되어있어요. 

그리고 이 부분도 width가 있어야 할까요? 제 생각에는 width 없이 padding만 사용해도 충분한 것 같아요. padding 상하좌우 값을 지정해서 가로/세로 길이를 조정 할 수 있고, 또 가로 기준으로 콘텐츠에 따라 박스가 변하니까 좀 더 유연해서 좋은 것 같아요.

2024-03-29 12:57 UTC, khkh0109 commented on src/components/Home/HabitGenerate/HabitGenerate.Style.ts
> +		gap: 10px;
여기 gap이 10px인 이유가 있나요? 피그마에는 12px로 되어있어요

2024-03-29 13:04 UTC, khkh0109 commented on src/components/Home/HabitGenerate/HabitGenerate.Style.ts
> +				${theme.font.body_xs}
여기 상위 요소에 적용되어 있는 폰트 때문에 서체 두께가 700으로 적용되는 것 같아요. 이 부분만 font-weight를 피그마와 동일하게 지정해야 할 것 같습니다.

2024-03-29 13:08 UTC, khkh0109 commented on src/components/Home/HabitGenerate/HabitGenerate.Style.ts
> +		& > .combined {
input 부분도 피그마와 폰튼 사이즈가 다릅니다.

2024-03-29 13:47 UTC, sikkzz requested changes

2024-03-29 13:47 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +					<div onClick={() => setIsTip(!isTip)}>{`좋은 습관 Tip`}</div>
도움말이 떠잇을때 x버튼으로도 꺼지지만 다른 영역을 클릭했을 때 창이 닫혀야 자연스러울 거 같네요

이와 관련해서 useOutsideClick이란 커스텀 훅을 많이 사용합니다. 제작은 제가 따로 해서 PR 올려드리겠습니다. 한번 서칭해보시고 어떤 hook인지 확인해보셔요

2024-03-29 13:47 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +	const [isTip, setIsTip] = useState<boolean>(false);
isOpenTip 같은 네이밍이 낫겠죠?

2024-03-29 13:47 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +	});
모달 임시용이라곤 하셨지만 해당 브랜치에서 이거 수정이 불가능한 이유가 있나요? 수정 가능할 거 같은데요 충분히

2024-03-29 13:47 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +	};
각 모달들 기능 및 디자인은 용주님 PR에서 이미 리뷰가 다 된 사항들입니다. 

해당 브랜치에서 기능 연결이 불가능하다면 차라리 코드 빼주세요 나중에 연결하는 코드만 새로 구현해서 PR 올리시는게 맞습니다

2024-03-29 13:47 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +				})}
여기 로직 싹 한번 새로 리팩토링 봐주세요

각 시멘틱 태그들도 사용에 적절하지 않은 부분이 있고 className이나 데이터, 변수명들 더 명확히 이해할 수 있게 변경 부탁드려요

그리고 타이틀과 Box를 한 묶음으로 해서 컴포넌트로 하나로 잡고 새로 구성해주세요

![스크린샷 2024-03-29 오후 10 44 34](https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/7c0f0594-fcd8-4517-b91a-5f74d4d88215)

2024-03-29 13:47 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +			{modals.location && <LocationModal />}
여기도 임시 코드 말고 수정 제대로 해주세요

2024-03-29 13:47 UTC, sikkzz commented on src/utils/TimeMapper.ts
여기서 불필요 코드 같네요 selectTImeModal에도 들어가 있는거 같고요 지우고 커밋 넣어주세요

2024-03-29 13:50 UTC, sikkzz commented
미완성인 상태로는 원래 PR을 올리는게 아닙니다

제가 따로 봐드릴려고 PR 올려달라한건 time modal 코드만 따로 빼서 올려달라 했던거 같은데 이해를 잘못하셨나봐요. 앞으로는 미완성인 상태로 PR은 지양해주세요. 

참고로 미완성이랑 현재 기능 구현 불가는 다른 영역이니까 만약 어떤 부분에 지장이 있어 추후 구현해야 한다면 그렇게 명시하고 PR 올리시는건 상관없습니다. 다만 관련 코드는 싹 빠지고 PR이 올라와야 합니다. 아니면 분명 여러번 같은 코드를 리뷰하는 일이 생기니까요. 그래버리면 열심히 브랜치 나누고 기능별로 나눠서 작업하는 장점이 싹 사라져버립니다

2024-03-30 05:10 UTC, khkh0109 commented on src/components/Home/HabitGenerate/HabitGenerate.Style.ts
> +		height: 9.25rem;
여기도 세로 길이 지정 없이 padding만으로 충분히 세로 길이와 여백을 함께 스타일링 할 수 있어요

2024-03-30 11:36 UTC, youngTkim commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +			<FooterBtn text="좋아, 이대로 만들게" isPositionStatic />
이거는 모달 완성된 이후에 추가하도록 하겠습니당

2024-03-30 11:37 UTC, youngTkim commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +				{habitGenerateConditions.map((condition) => {
단순 텍스트들로만 이루어져 있어서 대문자로 썼습니다

2024-04-01 10:48 UTC, sikkzz requested changes

2024-04-01 10:48 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +						<div>{`그래서 어떤 사람이 되고 싶으신가요?`}</div>
p

2024-04-01 10:48 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +					<div onClick={() => setIsOpenTip(!isOpenTip)}>
button

2024-04-01 10:48 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +						<div>{`좋은 습관 Tip`}</div>
p

2024-04-01 10:48 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +								<div>{`쉬워야 반복할 수 있기 때문이에요.`}</div>
p

2024-04-01 10:48 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +								<div>{`매력적이고 만족스러워야 계속하고 싶으니까요.`}</div>
p

2024-04-01 10:48 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +				<div css={tipBoxStyle}>
HabitTip으로 컴포넌트 하나 새로 빼주세요

그리고 ref 여기 달아주세요

2024-04-01 10:48 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +								<div>{`쉬워야 반복할 수 있기 때문이에요.`}</div>
그냥 텍스트만 넣어주세요 싹다 해당되는 얘기입니다

2024-04-01 10:48 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +						/>
컴포넌트 네이밍 직관적으로 부탁드려요

2024-04-01 10:48 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +			<ul css={selectBoxStyle}>
박스 크기 시안과 다릅니다 확인해주세요

2024-04-03 11:53 UTC, pizzaYami commented
github 대소문자 구분으로 배포가 안되네요

2024-04-03 12:30 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +								<div>{`쉬워야 반복할 수 있기 때문이에요.`}</div>
이거 수정 안된거 같습니다

2024-04-04 08:07 UTC, sikkzz commented
<img width="404" alt="스크린샷 2024-04-04 오후 5 07 06" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/dd7fc438-699a-4a86-84af-dd889d539c55">
<img width="453" alt="스크린샷 2024-04-04 오후 5 07 31" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/df2df765-2e9d-4f87-ac8d-7029c113eced">

이거 수정 해주세요 안된거라고 말씀드리는데도 계속 resolve 하시네요

2024-04-04 09:32 UTC, youngTkim commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +								<div>{`쉬워야 반복할 수 있기 때문이에요.`}</div>
텍스트만 적으라고 하시는게 {``}를 제거하라는 말씀이신가여?

2024-04-04 09:37 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +								<div>{`쉬워야 반복할 수 있기 때문이에요.`}</div>
네 제가 올려드신 예시 사진처럼요

2024-04-04 11:13 UTC, sikkzz requested changes

2024-04-04 11:13 UTC, sikkzz commented on src/hooks/useOutsideClick.ts
useOutSideClick으로 수정해주세요 네이밍

2024-04-07 08:29 UTC, sikkzz requested changes

2024-04-07 08:29 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +				</div>
이 코드는 왜 Tip 코드에 안들어가 있나요? props 넘길 필요 없이 HabitTIp안에서 로직 다 이루어져도 될텐데요

2024-04-07 08:29 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +	useOutSideClick(tipRef, () => setIsOpenTip(false));
얘네가 이쪽으로 나와있을 이유가 없으니까요

2024-04-08 10:07 UTC, sikkzz commented
<img width="441" alt="스크린샷 2024-04-08 오후 7 06 56" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/d03b2b93-dfe4-41bd-b956-84002f20cb3f">

habit tip 부분 보면 오른쪽 여백은 클릭해도 OutsideClick이 적용이 안됩니다. Tip 버튼이 영역 만큼만 공간을 가지고 있는게 좋겠죠?

2024-04-08 10:09 UTC, sikkzz requested changes

2024-04-08 10:09 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.style.ts
> +		gap: 20px;
얘가 이렇게 absolute로 붙어있을 필요가 없지 않을까요? 아래로 붙이면 될텐데요

2024-04-08 10:09 UTC, sikkzz commented
헤더 수정된만큼 여백도 추가 해주세요

2024-04-08 10:19 UTC, youngTkim commented on src/components/Home/HabitGenerate/HabitGenerate.style.ts
> +		gap: 20px;
그 조건들 위로 덮여져야한다고 하셔서 absolute로 두긴했습니다. 그래서 habitTip도 button 여백도 정확한 거리를 두고 만들려고 한 태그안에 묶어놔서 ref를 위로 났을때 오른쪽여백이 생기긴하는데 혹시 더 좋은 방법이 있을까요?

2024-04-08 10:54 UTC, youngTkim commented on src/components/Home/HabitGenerate/HabitGenerate.style.ts
> +		gap: 20px;
ref를 tipBox에 두고 button에 set함수를 넣어도 따로 적용이 안되가지고..

2024-04-08 11:02 UTC, sikkzz commented
커밋 넣어 드렸어요

2024-04-08 11:34 UTC, youngTkim commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +	useOutSideClick(tipRef, () => setIsOpenTip(false));
식님 아 깜빡거리네요 tip이 오픈됬을때 버튼눌러서 끌려고 하니까 깜빡거리면서 다시켜지네요

2024-04-08 12:06 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +	useOutSideClick(tipRef, () => setIsOpenTip(false));
수정했어요

2024-04-09 02:12 UTC, pizzaYami submitted a review, later dismissed

2024-04-09 10:59 UTC, sikkzz submitted a review, later dismissed

2024-04-09 23:05 UTC, khkh0109 approved these changes, later dismissed

2024-04-11 09:43 UTC, sikkzz requested changes

2024-04-11 09:43 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitTip/HabitTip.tsx
> +				}}
중괄호 왜 넣으신걸까요? 필요 없을텐데요

2024-04-11 09:59 UTC, youngTkim commented on src/components/Home/HabitGenerate/HabitTip/HabitTip.tsx
> +				}}
삭제했습니다. 그리고 혹시 그 버튼 눌렀을때 누를때만 꺼지고 다시 켜지는 현상이 있는데 어떻게 해결하는게 좋을까여?

2024-04-11 10:03 UTC, sikkzz requested changes

2024-04-11 10:03 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitTip/HabitTip.tsx
> +				<div ref={tipRef}>
이거 ref 지워주세요 제가 적용시킨 코드 확인 안하고 영택님 코드로 합치니까 제가 수정한게 자꾸 사라집니다 코드 확인 잘 좀 해주세요

2024-04-11 10:03 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitTip/HabitTip.tsx
> +				}}
아래 내용 확인해보세요

2024-04-11 11:29 UTC, sikkzz approved these changes

2024-04-11 11:29 UTC, khkh0109 approved these changes

2024-04-11 11:29 UTC, pizzaYami approved these changes

2024-04-11 11:30 UTC, merged