[TS-294] SelectTimeModal
ConnectingStar/ConnectingStar-Front pull request #63
Opened 2024-03-28 09:27 UTC by youngTkim

[TS-294](https://m2jun.atlassian.net/browse/TS-294)

## 💡 변경사항 & 이슈
 SelectTimeModal 초안입니다. 
 이후 props로 useState로 값을 받을 수 있도록 할 예정입니다.
<br>

## ✍️ 관련 설명
스크롤이 일정 높이에 다다르면 그 아이템 개수만큼 줄이고 붙여서 항상 일정한 갯수의 list로 유지하고 있습니다.
setTimeout기능을 통해 해당 높이에 해당하는 list의 인덱스의 가운데 높이로 자동으로 스크롤됩니다.
(이 부분이 가끔 제대로 작동되지 않는데 원인을 잘 모르겠습니다.)
<br>

## ⭐️ Review point
 오전 / 오후 로 스크롤될 때 변경되는 부분이 있어야하는데 그 부분 조언부탁드립니다.ㅠ
디자인 수정될 부분, 추가될 기능 부분 알려주시면 감사하겠습니다.
<br>

## 📷 Demo
<br>

2024-03-28 17:44 UTC, pizzaYami commented
url 어디가야 볼 수 있나요?

2024-04-12 07:32 UTC, pizzaYami requested changes

2024-04-12 07:32 UTC, pizzaYami commented on src/components/common/Modal/CommonModal/SelectTimeModal/SelectTimeModal.tsx
> +	const [selectedClock, setSelectedClock] = useState({ noon: "오전", time: "01", minute: "00" });
selectedClock 요거 기능은 한번에 데이터 보내기 위한 것 맞나요?
selectedClock 쓰이는 곳이 없어서 질문합니다.

2024-04-12 07:32 UTC, pizzaYami commented on src/components/common/Modal/CommonModal/SelectTimeModal/TimePicker/TimePicker.tsx
> +		clearTimeout(timerRef.current);
time과 관련된 건 일정시간동안 불필요한 함수의 호출을 막기 위한 작업이 맞나요?

2024-04-12 07:32 UTC, pizzaYami commented on src/components/common/Modal/CommonModal/SelectTimeModal/TimePicker/TimePicker.tsx
> +				});
중앙으로 오게 하는 함수 같은데 제대로 영역이 작아서 제대로 작동하지 않는 것 같네요

2024-04-12 07:32 UTC, pizzaYami commented on src/components/common/Modal/CommonModal/SelectTimeModal/TimePicker/TimePicker.tsx
> +				});
```
    timerRef.current = setTimeout(() => {
      const index = Math.floor((scrollRef.current!.scrollTop + PICKER_HEIGHT / 2) / PICKER_HEIGHT);
      if (list[index] !== "") {
        setSelected(index);
        const selectedItem = itemRef.current[index];
        if (selectedItem && scrollRef.current) {
          const scrollContainer = scrollRef.current;
          const scrollMiddle = (scrollContainer.clientHeight / 2) - (selectedItem.offsetHeight / 2);
          const topPosition = selectedItem.offsetTop - scrollMiddle;
          scrollContainer.scrollTop = topPosition;
          onSelectedChange(list[index]);
        }
      }
    }, SCROLL_DEBOUNCE_TIME);
```

이런식으로 만들면 제대로 작동하네요.

2024-04-12 07:32 UTC, pizzaYami commented on src/components/common/Modal/CommonModal/SelectTimeModal/TimePicker/TimePicker.tsx
> +					key={index}
key={item}을 넣는게 낫겠네요
map의 key에 index를 넣는 것을 지양하고 있습니다.
[map의 key를 넣으면 안되는 이유 블로그](https://medium.com/sjk5766/react-%EB%B0%B0%EC%97%B4%EC%9D%98-index%EB%A5%BC-key%EB%A1%9C-%EC%93%B0%EB%A9%B4-%EC%95%88%EB%90%98%EB%8A%94-%EC%9D%B4%EC%9C%A0-3ce48b3a18fb)

2024-04-12 12:36 UTC, sikkzz commented on src/components/common/Modal/CommonModal/SelectTimeModal/SelectTimeModal.tsx
> +	const [selectedClock, setSelectedClock] = useState({ noon: "오전", time: "01", minute: "00" });
네 시간 가져다 쓰실때 사용하시면 됩니다. 시간 선택 후 선택 버튼 누르면 콘솔에서 데이터 값 확인 가능해요

2024-04-12 12:41 UTC, sikkzz commented on src/components/common/Modal/CommonModal/SelectTimeModal/TimePicker/TimePicker.tsx
> +		clearTimeout(timerRef.current);
스크롤시 이전 타이머 상태들을 초기화시키는 작업입니다

2024-04-12 12:43 UTC, sikkzz commented on src/components/common/Modal/CommonModal/SelectTimeModal/TimePicker/TimePicker.tsx
> +				});
수정해주신 코드로 사용하면 버벅거림이 눈에띌정도로 존재합니다. 

스크롤하다가 값에 도달하지 않고 스크롤을 멈추면 해당 값 중앙에 오게 만들어주는거고 용주님 코드처럼 임의로 값을 딱 바꿔서 정해주면 부드러운 모션 없이 해당 박스로 이동해버립니다

2024-04-13 04:31 UTC, pizzaYami commented on src/components/common/Modal/CommonModal/SelectTimeModal/TimePicker/TimePicker.tsx
> +				});
![스크린샷 2024-04-13 오전 8 00 33](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/b304a189-0f65-411f-9fab-bec7bbfe43fc)

요런식으로 중앙에 잘 오지 않아서 수정해보았는데 어렵네요ㅠ

2024-04-13 16:24 UTC, sikkzz commented on src/components/common/Modal/CommonModal/SelectTimeModal/TimePicker/TimePicker.tsx
> +				});
모바일에서 심지어 제대로 작동을 안하네요 좀 고쳐보겠습니다

2024-04-14 05:24 UTC, pizzaYami commented on src/components/common/Modal/CommonModal/SelectTimeModal/TimePicker/TimePicker.tsx
> +				});
네 저도 고쳐볼게요

2024-04-14 22:31 UTC, sikkzz commented
리팩토링 진행했습니다 확인 부탁드려요

2024-04-15 03:17 UTC, khkh0109 approved these changes, later dismissed

2024-04-15 10:53 UTC, pizzaYami approved these changes, later dismissed

2024-04-15 11:25 UTC, closed without merging