[TS-297] onboardingPage
ConnectingStar/ConnectingStar-Front pull request #66
Opened 2024-04-01 10:13 UTC by pizzaYami

[TS-297](https://m2jun.atlassian.net/browse/TS-297)

## 💡 변경사항 & 이슈
/onboarding

- onboarding부분을 OnboardingPage와 ChattingPage로 통합
- <Splash /> 캐릭터와 로고 이미지 넣음
- <SignUp /> 이미지 넣고 파란색 글씨 넣음
- redux와 연결
<br>

## ✍️ 관련 설명
[토스-쏟아지는 페이지 한방에 관리하기](https://www.youtube.com/watch?v=NwLWX2RNVcw&t=861s)를 참고하여 만들었습니다.
```
(onboardingPage.tsx)
const user = useSelector((state) => state.user);
console.log(user);
```
이 부분은 테스트를 용이하도록 넣었으며 머지후에 다음 PR에서 제거하겠습니다.

<br>

## ⭐️ Review point
CreateAccount의 confirmBasicUserData함수
VisitorRoute의 confirmVisitorRouteData함수
- 두 개의 함수의 네이밍이 맘에 안드는데 추천해주세요.
- UI문제
- 잘못된 네이밍

<br>

## 📷 Demo
<br>

|splash|signup1|signup2|
|:---:|:---:|:---:|
|<img width="320" alt="스크린샷 2024-02-07 오후 8 43 14" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/de218469-51ba-42ea-bd31-7b15be6f34c2">|<img width="320" alt="스크린샷 2024-02-07 오후 8 46 39" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/3b6acb6e-7d38-4d4c-b671-ed2bd43d9efc">|<img width="320" alt="스크린샷 2024-02-07 오후 8 47 12" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/bd084763-0ae1-4875-8b51-cc990a432eca">|

|signup3|OauthSignUp|CreateAccount|
|:---:|:---:|:---:|
|<img width="320" alt="스크린샷 2024-02-07 오후 8 43 14" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/93808824-ca75-4206-a7c8-99af81204612">|<img width="320" alt="스크린샷 2024-02-07 오후 8 46 39" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/10e1a088-1f20-4e8d-8599-d147f87d8a4b">|<img width="320" alt="스크린샷 2024-02-07 오후 8 47 12" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/6ee3a25c-5e05-43f4-9c0c-e7da66d125ee">|

|VisitorRoute|
|:---:|
|<img width="33%" alt="스크린샷 2024-02-07 오후 8 43 14" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/d398b2ed-4894-4a5b-9da5-be6b94c39350" />|

2024-04-02 11:40 UTC, khkh0109 commented
궁금한게 있는데 스플래시 스크린이 온보딩 페이지에 포함되는건가요? 

제가 알기로 스플래시는 앱이 실행되는 동안 보이는 화면으로 알고 있습니다. 그래서 PWA쪽에서 설정해야 하지 않을까 싶어서 말씀드려요

([안드로이드는 매니페스트 정보로 설정](https://web.dev/learn/pwa/enhancements?hl=ko#splash_screens)된다고 하고, iOS는 자동으로 안되고 따로 설정을 해줘야 하는걸로 알고있습니다,, vite pwa plugin 문서 보니까 플러그인으로 [설정할 수 있는것 같기도](https://vite-pwa-org.netlify.app/assets-generator/cli.html#ios-ipad-splash-screens) 하네요..? 이 부분은 저도 안해봐서 모르겠습니다)

참고로 현재 스플래시 화면도 남겨둡니다! 휴대폰에 다운받아서 실행해보시면 현재 매니페스트로 설정된 아이콘을 사용해서 스플래시가 자동으로 생성되어 있어요(안드로이드 기기)

https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/c26a85c4-1916-42b1-bc5a-3601d9f10185

2024-04-03 11:30 UTC, pizzaYami commented
> 궁금한게 있는데 스플래시 스크린이 온보딩 페이지에 포함되는건가요?
> 
> 제가 알기로 스플래시는 앱이 실행되는 동안 보이는 화면으로 알고 있습니다. 그래서 PWA쪽에서 설정해야 하지 않을까 싶어서 말씀드려요
> 
> ([안드로이드는 매니페스트 정보로 설정](https://web.dev/learn/pwa/enhancements?hl=ko#splash_screens)된다고 하고, iOS는 자동으로 안되고 따로 설정을 해줘야 하는걸로 알고있습니다,, vite pwa plugin 문서 보니까 플러그인으로 [설정할 수 있는것 같기도](https://vite-pwa-org.netlify.app/assets-generator/cli.html#ios-ipad-splash-screens) 하네요..? 이 부분은 저도 안해봐서 모르겠습니다)
> 
> 참고로 현재 스플래시 화면도 남겨둡니다! 휴대폰에 다운받아서 실행해보시면 현재 매니페스트로 설정된 아이콘을 사용해서 스플래시가 자동으로 생성되어 있어요(안드로이드 기기)
> 
>  _talkv_wvfUSs5g2I_gIhjcugkGD16fCzCkXNz61_talkv_high.mov

승인이 나면 splash부분만 따로뺴서 PWA설정으로 넣어야겠네요

2024-04-03 16:31 UTC, sikkzz requested changes

2024-04-03 16:31 UTC, sikkzz commented on src/components/Onboarding/CreateAccount.tsx
각 파일들 폴더 만들어주세요 Onboarding 전체 부탁드려요

2024-04-03 16:31 UTC, sikkzz commented on src/components/Onboarding/CreateAccount.style.ts
파일은 삭제가 안된거 같네요 코드만 삭제 상태입니다

2024-04-03 16:31 UTC, sikkzz commented on src/components/Onboarding/OauthSignUp.style.ts
이친구도 빈파일로 남아있네요?

2024-04-03 16:31 UTC, sikkzz commented on src/components/Onboarding/OauthSignUp.tsx
얘도요

2024-04-03 16:31 UTC, sikkzz commented on src/components/Onboarding/OauthSignup/FooterPrivacyPolicyLink.tsx
> +				<a className="line">서비스 이용약관</a>
href 옵션 없으면 오류날텐데 안나나요?

2024-04-04 08:59 UTC, youngTkim submitted a review, later dismissed

2024-04-04 09:20 UTC, pizzaYami commented on src/components/Onboarding/OauthSignup/FooterPrivacyPolicyLink.tsx
> +				<a className="line">서비스 이용약관</a>
오류는 안 나네요
나중에 약관들 추가되면 href 옵션 추가할 예정이긴합니다

2024-04-04 09:43 UTC, sikkzz commented on src/components/Onboarding/OauthSignup/FooterPrivacyPolicyLink.tsx
> +				<a className="line">서비스 이용약관</a>
href=# 만 추가 부탁드려요

2024-04-04 09:43 UTC, sikkzz commented
Sign up과 OauthSignUp 컴포넌트의 차이가 혹시 뭔가요? Sign up은 렌더링 확인이 안되는거 같아서요

2024-04-04 11:03 UTC, pizzaYami commented
> Sign up과 OauthSignUp 컴포넌트의 차이가 혹시 뭔가요? Sign up은 렌더링 확인이 안되는거 같아서요

Signup 
![스크린샷 2024-04-04 오후 8 01 34](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/200ee689-fd3e-45a9-b8a6-22fbe28fcb52)

OauthSignUp
![스크린샷 2024-04-04 오후 8 01 53](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/3c2978c5-2e6b-4da1-a2c0-45215e0eacd2)

피그마상 이름으로 했는데 직관성이 없긴하네요
signUp렌더링 어떤 문제가 있나요??

2024-04-07 08:32 UTC, sikkzz approved these changes

2024-04-07 12:01 UTC, khkh0109 submitted a review, later dismissed

2024-04-08 09:39 UTC, youngTkim submitted a review, later dismissed

2024-04-08 10:11 UTC, sikkzz requested changes
헤더 rebase 하고 여백 추가해야하지 않을까요?

2024-04-09 02:22 UTC, pizzaYami commented
> 헤더 rebase 하고 여백 추가해야하지 않을까요?

변경 완료했습니다.

2024-04-09 11:32 UTC, youngTkim approved these changes, later dismissed

2024-04-09 11:33 UTC, sikkzz commented
<img width="461" alt="스크린샷 2024-04-09 오후 8 31 54" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/ca37b561-eeb5-44a8-b3fc-41eec311c97f">

여기 수정 안된 거 같아요

그리고 뒤쪽 채팅 모달들은 다른 브랜치에서 하실 예정이신가요?

2024-04-09 23:14 UTC, khkh0109 approved these changes

2024-04-10 13:11 UTC, sikkzz approved these changes

2024-04-11 07:55 UTC, youngTkim approved these changes

2024-04-11 11:35 UTC, merged