[TS-287] Header 컴포넌트 수정(뒤로가기/닫기 버튼, 상단 고정)
ConnectingStar/ConnectingStar-Front pull request #67
Opened 2024-04-01 11:07 UTC by khkh0109

[TS-287](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?assignee=616ccf7525f31300702d29cb&selectedIssue=TS-287)

## 💡 변경사항 & 이슈
Header 컴포넌트 수정
- 뒤로가기/닫기 버튼
- 상단 고정
<br>

## ✍️ 관련 설명
### 기능 관련
- 뒤로가기에 onClick prop을 추가했습니다(옵션)
  - 기본: 뒤로가는 기능 / 옵션: onClick prop을 전달하면 전달한 onClick 함수 실행됨
- 닫기 버튼에 onClick prop을 추가했습니다(필수)
  - 닫기 버튼은 기본 기능이 없고 항상 액션이 있기 때문에 필수로 지정했습니다. 옵션으로 지정하는게 나을 것 같다면 말씀해주세요
  - onClick prop을 필수로 지정해서 CloseButton을 사용하는 곳에서 에러가 발생합니다. 그래서 임시로 onClick prop를 추가해두었습니다. 

### 스타일/그 외
- position fixed 추가했습니다.
  - 버튼과 같은 기능이 있는 Header는 항상 페이지 상단에 고정
  - 통계, 마이페이지와 같이 기능이 없는 Header는 고정 X
  - Header가 상단에 고정된 페이지는 Header 세로 길이만큼 페이지의 padding을 조정해 주셔야 합니다. 현재 제가 담당한 부분(StarCard, StarCardDetail)은 은 반영이 되어있는데, 이 브랜치에서 한번에 수정하는게 나을 것 같다면 말씀해 주세요. 한번에 수정해서 올리겠습니다.
  - 또 chatting 페이지는 Header 수정으로 인해 프로그레스 바가 보이지 않습니다. 이 부분도 수정해야 할 것 같아요. 
- 360px을 rem 단위로 수정했습니다. 
- 다른 아이콘 이름과 동일하게 이름 앞에 ic- 접두어를 붙였습니다.
- 기존 객체로 묶여있던 스타일을 분리했습니다(굳이 객체로 묶을 필요 없을 것 같아서)

<br>

## ⭐️ Review point
- 잘 동작하는지
- 아이콘 잘 보이는지
- 그 외 등등..더 괜찮은 방법 있으면..
<br>

## 📷 Demo
없음

<br>

2024-04-03 13:05 UTC, pizzaYami submitted a review, later dismissed

2024-04-03 13:05 UTC, pizzaYami commented on src/components/common/Header/Header.tsx
> +	onClick: React.MouseEventHandler<HTMLButtonElement>;
type만 따로 모아서 파일 만드시는건 어떠신가요?

2024-04-03 13:05 UTC, pizzaYami commented on src/components/common/Header/Header.tsx
> +export default function Header({ children, isFixed = true }: HeaderProps) {
StarCardPage.tsx
```
<Header isFixed={false}>
	<Header.PrevButton />
	<Header.Title>별자리 카드</Header.Title>
</Header>
```
![스크린샷 2024-04-03 오후 9 54 19](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/707e7ca1-87c2-494f-9d78-bb3a6eb8f4fa)

isFixed={false} 넣으니깐 뒤로가기 버튼이 이상한 위치로 가네요

getContainerStyle에 position: relative; 추가하면 해결됩니다.

2024-04-03 13:05 UTC, pizzaYami commented on src/components/common/Header/Header.style.ts
> +
position: relative

2024-04-03 13:05 UTC, pizzaYami commented on src/components/common/Header/Header.tsx
>  }: ComponentPropsWithoutRef<"button">) {
TextButton도 Header.CloseButton 처럼 반드시 onclick이 들어가야하지 않나요?

2024-04-03 13:07 UTC, pizzaYami commented
개인적으로 헤더 컴포넌트의 사용법을 주석으로 적어놓으면 좋을 것 같아요

2024-04-03 14:34 UTC, khkh0109 commented on src/components/common/Header/Header.tsx
> +export default function Header({ children, isFixed = true }: HeaderProps) {
반영했습니다! 
그리고 기존에는 fixedStyle을 따로 정의했는데 이 부분도 그냥 container style 내부로 합쳤습니다

2024-04-03 15:13 UTC, khkh0109 commented on src/components/common/Header/Header.tsx
>  }: ComponentPropsWithoutRef<"button">) {
onClick을 필수로 받게끔 설정해야 한다는 말씀이실까요? 사용하는 곳에서 onClick을 props로 전달하지 않으면 에러를 발생하게 해야한다는 말 맞나요? 

일단은 ComponentPropsWithoutRef<"button"> 이 타입에 onClick도 포함되어 있어서 따로 명시하지 않았습니다. CloseButton은 onClick 말고 다른 이벤트는 필요없을것 같아서 `ComponentPropsWithoutRef<"button">` 이런 타입을 지정하지 않았어요 

뒤로가기, 닫기 버튼은 기능 자체가 명확해서 타입도 비교적 명확하게 지정 가능한데 
TextButton은 기능 자체가 명확한게 아니라 타입도 넓게 열어두었습니다(onClick 이외에 다른 이벤트가 필요하다거나 버튼 속성이 필요할 수 있을것 같아서요)

아무튼 이런 의도로 타입을 지정한거긴 한데, onClick이 어떤 버튼은 필수고 어떤 버튼은 아니라 일관성있게 통일하는게 나을 것 같네요!

2024-04-03 16:37 UTC, sikkzz requested changes

2024-04-03 16:37 UTC, sikkzz commented on src/types/headerType.ts
> +}
<img width="563" alt="스크린샷 2024-04-04 오전 1 36 03" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/228057cd-31e3-4645-b376-f7c8d32b04da">

이거 쓰시면 될 거 같네용

2024-04-03 16:37 UTC, sikkzz commented on src/types/headerType.ts
> +}
이거 하나만 사용해도 작동에 문제 없지 않나요? 아래 type 없이요

2024-04-03 16:38 UTC, sikkzz commented
헤더 고정으로 깨지는 레이아웃들 있는 거 같네요 각자 파트 확인하시면서 수정하시라고 코멘트 달아드려요

2024-04-03 16:53 UTC, khkh0109 commented on src/components/common/Header/Header.tsx
> +	onClick: React.MouseEventHandler<HTMLButtonElement>;
반영했습니다! headerType.ts로 분리했어요

2024-04-03 17:06 UTC, khkh0109 commented on src/types/headerType.ts
> +}
이런 타입이 있었네요..! HeaderProps랑 TitleProps 타입 이걸로 반영했습니다~

2024-04-03 17:12 UTC, khkh0109 commented on src/types/headerType.ts
> +}
CloseButton은 onClick을 필수로 받으려고 따로 `?` 없이 작성했는데, 일관성 있게 전부 옵션으로 받는게 좋을 것 같아서 통일했습니다!

onClick을 옵션으로 받으면 코멘트 주신대로 PrevButtonProps와 타입이 똑같아져서 이름을 IconButtonProps로 변경하고 타입도 합쳤습니다

2024-04-04 08:35 UTC, youngTkim approved these changes, later dismissed

2024-04-04 09:17 UTC, sikkzz submitted a review, later dismissed

2024-04-05 03:28 UTC, pizzaYami approved these changes, later dismissed

2024-04-05 03:28 UTC, pizzaYami commented on src/components/common/Header/Header.tsx
>  }: ComponentPropsWithoutRef<"button">) {
onClick을 필수로 받게끔 설정해야 되지 않나 라는 뜻 이였습니다.

피그마를 보았을 때 <Header.CloseButton>와 동일하게 "관리", "완료"처럼 반드시 onClick이 필요하고 다른 기능은 없는 것 같아서 제안 드린겁니다.

"TextButton은 기능 자체가 명확한게 아니라 타입도 넓게 열어두었습니다."
->TextButton은 기능이 명확하지 않고 기능이 추가될 수 있으니 일관성있게 그대로 두면 되겠네요.

2024-04-05 10:17 UTC, khkh0109 commented
Header 컴포넌트 사용 방법이 적힌 노션 링크를 추가해 두었습니다.
아래 사진과 같이 Header 컴포넌트 위에 커서를 올리면 툴팁으로 링크가 보이고, 바로 클릭해서 해당 문서로 이동 가능합니다. 

문서 내용에 보완하거나 수정할 부분이 있다면 언제든지 말씀해 주세요.

<img width="676" alt="스크린샷 2024-04-05 오후 7 09 23" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/77bbdc02-65a6-489e-be0e-4bb7664b8bc0">



@pizzaYami @youngTkim @sikkzz

2024-04-05 15:38 UTC, pizzaYami approved these changes

2024-04-07 08:32 UTC, sikkzz approved these changes

2024-04-07 14:52 UTC, youngTkim approved these changes

2024-04-08 02:09 UTC, merged