[TS-288] habitManage
ConnectingStar/ConnectingStar-Front pull request #68
Opened 2024-04-04 06:57 UTC by youngTkim

[TS-288](https://m2jun.atlassian.net/browse/TS-288)

## 💡 변경사항 & 이슈
/habit-manage를 통해 확인

- 페이지 스타일과 자체 모달만 연결된 상태
- 알림이 켜져있을 때만 AlarmBoxModal이 뜨도록 함
- 습관 그만두기버튼은 FooterBtn isPositionStatic이 false일 때의 옵션을 가져다 씀, fixed 상태

<br>

## ✍️ 관련 설명
<br>

## ⭐️ Review point
페이지와 모달 관련 디자인에 이상이 없는지 확인
<br>

## 📷 Demo
<img width="288" alt="스크린샷 2024-04-04 오후 3 48 57" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/117588223/cd09067f-54ea-4844-8944-281f3c3097b9">
<img width="288" alt="스크린샷 2024-04-04 오후 3 49 07" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/117588223/598967af-9636-40d4-9d7a-7420b754269d">

<br>

2024-04-04 10:33 UTC, sikkzz requested changes

2024-04-04 10:33 UTC, sikkzz commented on src/components/Home/habitManage/AlarmCheckModal/AlarmCheckModal.tsx
> +					<h1>{`알림을 유지하시겠어요?`}</h1>
텍스트

2024-04-04 10:33 UTC, sikkzz commented on src/components/Home/habitManage/AlarmCheckModal/AlarmCheckModal.tsx
> +					<h1>{`알림을 유지하시겠어요?`}</h1>
시멘틱 태그도 안맞네요

2024-04-04 10:33 UTC, sikkzz commented on src/components/Home/habitManage/HabitManage.tsx
> +	});
api 작업 생각하면 이거 묶어서 쓰시면 안될거 같네요 각자 api 따로 돌아갈거 같은데

2024-04-04 10:33 UTC, sikkzz commented on src/components/Home/habitManage/HabitManage.tsx
> +						<p>{`오후 7:50`}</p>
텍스트

2024-04-04 10:33 UTC, sikkzz commented on src/components/Home/habitManage/HabitManage.tsx
> +					<div>{`곧 약속 시간이에요 :) 성장하는 세림님 화이팅!`}</div>
텍스트

2024-04-04 10:33 UTC, sikkzz commented on src/components/Home/habitManage/HabitManage.tsx
여기 코드 마이페이지 제 파트 보시면 비슷한 로직 있습니다. 그거 참고해서 수정해주세요

2024-04-04 10:55 UTC, youngTkim commented on src/components/Home/habitManage/HabitManage.tsx
> +					<div>{`곧 약속 시간이에요 :) 성장하는 세림님 화이팅!`}</div>
텍스트는 바로 수정할게영

2024-04-05 03:31 UTC, pizzaYami commented
habit와 관련된 페이지가 많은데 
/habit-history
/habit-delete
/habit-record
/habit-manage
이걸 /habit/history 이런식으로 바꾸시는건 어떠신가요?

2024-04-05 04:20 UTC, pizzaYami commented
이 컴포넌트에서는 className을 이용해서 css만드셨는데 이러면 emotion을 사용하는 이유가 없어진다고 생각됩니다.
어쩔 수 없는 경우에만 className사용하시고 대부분은 emotion사용해서 코드 작성해주셔야 통일감이 있고 코드보기 더 편할 것 같습니다.

2024-04-05 04:32 UTC, pizzaYami requested changes

2024-04-05 04:32 UTC, pizzaYami commented on src/components/Home/habitManage/HabitManage.style.ts
> +			left: ${isToggled ? "0" : "calc(100% - 1.3rem)"};
itToggled가 true일 때 "calc(100% - 1.3rem)" false일때 0이 되어야하지않나요?

2024-04-05 04:32 UTC, pizzaYami commented on src/components/Home/habitManage/HabitManage.tsx
> +	const [target, setTarget] = useState<string>("first");
const [target, setTarget] = useState<string>("");

처음부터 first넣을 이유는 없으니 ""빈값으로 넣는게 낫겠네요

2024-04-05 04:32 UTC, pizzaYami commented on src/components/Home/habitManage/HabitManage.tsx
> +				<span>알람</span>
알람 -> 알림

2024-04-05 04:32 UTC, pizzaYami commented on src/components/Home/habitManage/HabitManage.style.ts
> +		}
통일감이 없습니다
p:nth-of-type(1) / p:nth-of-type(2) 
p:first-of-type / p:last-of-type 둘 중 하나 선택해주세요

2024-04-05 04:32 UTC, pizzaYami commented on src/components/Home/habitManage/HabitManage.style.ts
> +		border-radius: 0.75rem;
border-radius는 px로하기로했어요

2024-04-07 15:21 UTC, youngTkim commented on src/components/Home/habitManage/HabitManage.tsx
수정했어요! 근데 mypage에서 쓴 거에서 좀 바꿔놔서 확인 부탁드릴게용

2024-04-08 02:38 UTC, khkh0109 commented
혹시 습관 그만두기 버튼이 항상 하단에 붙어야 한다고 세림님이 요청하셨을까요? 
아이폰 SE 기준으로 보면 세로 길이가 짧아졌을때 아래처럼 항상 하단에 고정된 상태로 보여요
<img width="413" alt="스크린샷 2024-04-08 오전 11 36 28" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/0fcc0af2-8956-4ef0-aa48-11aeeb473e60">

2024-04-08 08:23 UTC, youngTkim commented
> 혹시 습관 그만두기 버튼이 항상 하단에 붙어야 한다고 세림님이 요청하셨을까요? 아이폰 SE 기준으로 보면 세로 길이가 짧아졌을때 아래처럼 항상 하단에 고정된 상태로 보여요 <img alt="스크린샷 2024-04-08 오전 11 36 28" width="413" src="https://private-user-images.githubusercontent.com/77181642/320338507-0fcc0af2-8956-4ef0-aa48-11aeeb473e60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NjQ3NzAsIm5iZiI6MTcxMjU2NDQ3MCwicGF0aCI6Ii83NzE4MTY0Mi8zMjAzMzg1MDctMGZjYzBhZjItODk1Ni00ZWYwLWFhNDgtMTFhZWViNDczZTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA4MjExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNjA0Y2QxZGNhYzIwMDViODM0MzM2ZTA0ZDU0MGUxZWRlMzg2YmM5YjY4YTI2YzI4MTliNzMyMzcyMWI4MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y1jeoDt1BGj9s4yG3DguH1UH7oQbtTOSgS85JzwObt8">

스크롤될때는 footerBtn 하단 고정이라고 제가 알고 있어서요. 한번 확인해볼게요!

2024-04-09 07:12 UTC, pizzaYami commented
> > 혹시 습관 그만두기 버튼이 항상 하단에 붙어야 한다고 세림님이 요청하셨을까요? 아이폰 SE 기준으로 보면 세로 길이가 짧아졌을때 아래처럼 항상 하단에 고정된 상태로 보여요 <img alt="스크린샷 2024-04-08 오전 11 36 28" width="413" src="https://private-user-images.githubusercontent.com/77181642/320338507-0fcc0af2-8956-4ef0-aa48-11aeeb473e60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NjQ3NzAsIm5iZiI6MTcxMjU2NDQ3MCwicGF0aCI6Ii83NzE4MTY0Mi8zMjAzMzg1MDctMGZjYzBhZjItODk1Ni00ZWYwLWFhNDgtMTFhZWViNDczZTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA4MjExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNjA0Y2QxZGNhYzIwMDViODM0MzM2ZTA0ZDU0MGUxZWRlMzg2YmM5YjY4YTI2YzI4MTliNzMyMzcyMWI4MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y1jeoDt1BGj9s4yG3DguH1UH7oQbtTOSgS85JzwObt8">
> 
> 스크롤될때는 footerBtn 하단 고정이라고 제가 알고 있어서요. 한번 확인해볼게요!

기획에 물어보니 하단 고정아니랍니다.

2024-04-11 09:44 UTC, sikkzz commented
마이페이지쪽 버튼이랑 공통 컴포넌트로 사용하는게 좋아보입니다 구성 하실 수 있으신가요?

2024-04-11 10:53 UTC, youngTkim commented
> 마이페이지쪽 버튼이랑 공통 컴포넌트로 사용하는게 좋아보입니다 구성 하실 수 있으신가요?

아넵 그쪽버튼으로 수정하겠습니다

2024-04-12 07:45 UTC, pizzaYami requested changes

2024-04-12 07:45 UTC, pizzaYami commented on src/components/Home/habitManage/HabitManage.tsx
> +					<Button inputs={inputs} isToggle alarmCheck={alarmCheck} alarmQuestion={alarmQuestion} />
key값 넣기

2024-04-12 07:46 UTC, pizzaYami commented
데이터관련해서 필요한 건 모두 redux에 넣어놨는데 그걸 가져와서 보여주는 형식으로 바꿔야겠네요.

2024-04-13 09:55 UTC, sikkzz commented
> 데이터관련해서 필요한 건 모두 redux에 넣어놨는데 그걸 가져와서 보여주는 형식으로 바꿔야겠네요.

그렇게 생각하시는 이유가 있나요? 저는 아니라고 생각해서요

2024-04-14 14:51 UTC, pizzaYami commented
> > 데이터관련해서 필요한 건 모두 redux에 넣어놨는데 그걸 가져와서 보여주는 형식으로 바꿔야겠네요.
> 
> 그렇게 생각하시는 이유가 있나요? 저는 아니라고 생각해서요

api요청을 최대한 줄이는게 낫다고 생각했습니다.
추가로 요청해야 되는 데이터가 없다면 redux가 낫겠지만 이외에 추가로 요구되는 데이터가 있다면 api요청으로 받는게 낫겠네요.

2024-04-14 14:56 UTC, sikkzz commented
> > > 데이터관련해서 필요한 건 모두 redux에 넣어놨는데 그걸 가져와서 보여주는 형식으로 바꿔야겠네요.
> > 
> > 
> > 그렇게 생각하시는 이유가 있나요? 저는 아니라고 생각해서요
> 
> api요청을 최대한 줄이는게 낫다고 생각했습니다. 추가로 요청해야 되는 데이터가 없다면 redux가 낫겠지만 이외에 추가로 요구되는 데이터가 있다면 api요청으로 받는게 낫겠네요.

말씀하시는 데이터들이 alarm 데이터들이라면 api 요청으로 받아올 데이터들이 맞습니다. 다만 현재는 api 연결 안된 ui 렌더링 단계니까 저렇게 mock data로 넣어놓는게 맞지 않나 싶네요. 

추가적으로 모든 data를 redux로 관리하는건 아닙니다. redux는 전역 state로 사용되기 때문에 여러곳에서 자주 사용되는 데이터들을 담아서 사용할때만 redux를 이용합니다. 컴포넌트 부모 자식 관계에서 props로 해결이 가능하다면 redux가 아닌 내부 데이터로 관리하는게 좋습니다. 해당 데이터 접근이 모든 컴포넌트에서 가능하다는 점, 그 데이터들이 변하면 리렌더링된다는 점 등을 고려해야하니까요

2024-04-14 14:57 UTC, sikkzz commented
> > > > 데이터관련해서 필요한 건 모두 redux에 넣어놨는데 그걸 가져와서 보여주는 형식으로 바꿔야겠네요.
> > > 
> > > 
> > > 그렇게 생각하시는 이유가 있나요? 저는 아니라고 생각해서요
> > 
> > 
> > api요청을 최대한 줄이는게 낫다고 생각했습니다. 추가로 요청해야 되는 데이터가 없다면 redux가 낫겠지만 이외에 추가로 요구되는 데이터가 있다면 api요청으로 받는게 낫겠네요.
> 
> 말씀하시는 데이터들이 alarm 데이터들이라면 api 요청으로 받아올 데이터들이 맞습니다. 다만 현재는 api 연결 안된 ui 렌더링 단계니까 저렇게 mock data로 넣어놓는게 맞지 않나 싶네요.
> 
> 추가적으로 모든 data를 redux로 관리하는건 아닙니다. redux는 전역 state로 사용되기 때문에 여러곳에서 자주 사용되는 데이터들을 담아서 사용할때만 redux를 이용합니다. 컴포넌트 부모 자식 관계에서 props로 해결이 가능하다면 redux가 아닌 내부 데이터로 관리하는게 좋습니다. 해당 데이터 접근이 모든 컴포넌트에서 가능하다는 점, 그 데이터들이 변하면 리렌더링된다는 점 등을 고려해야하니까요

데이터들이 어떤 부분에서 어떻게 가공되고 사용할지 모르는 현재 상태에서는 당연히 현상태 유지가 좋겠죠?

2024-04-23 10:52 UTC, pizzaYami commented
> > > > > 데이터관련해서 필요한 건 모두 redux에 넣어놨는데 그걸 가져와서 보여주는 형식으로 바꿔야겠네요.
> > > > 
> > > > 
> > > > 그렇게 생각하시는 이유가 있나요? 저는 아니라고 생각해서요
> > > 
> > > 
> > > api요청을 최대한 줄이는게 낫다고 생각했습니다. 추가로 요청해야 되는 데이터가 없다면 redux가 낫겠지만 이외에 추가로 요구되는 데이터가 있다면 api요청으로 받는게 낫겠네요.
> > 
> > 
> > 말씀하시는 데이터들이 alarm 데이터들이라면 api 요청으로 받아올 데이터들이 맞습니다. 다만 현재는 api 연결 안된 ui 렌더링 단계니까 저렇게 mock data로 넣어놓는게 맞지 않나 싶네요.
> > 추가적으로 모든 data를 redux로 관리하는건 아닙니다. redux는 전역 state로 사용되기 때문에 여러곳에서 자주 사용되는 데이터들을 담아서 사용할때만 redux를 이용합니다. 컴포넌트 부모 자식 관계에서 props로 해결이 가능하다면 redux가 아닌 내부 데이터로 관리하는게 좋습니다. 해당 데이터 접근이 모든 컴포넌트에서 가능하다는 점, 그 데이터들이 변하면 리렌더링된다는 점 등을 고려해야하니까요
> 
> 데이터들이 어떤 부분에서 어떻게 가공되고 사용할지 모르는 현재 상태에서는 당연히 현상태 유지가 좋겠죠?

ㅇㅋㅇㅋ 이해했습니다. 현상태 유지로 가죠

2024-04-23 11:07 UTC, pizzaYami submitted a review, later dismissed

2024-04-26 18:06 UTC, sikkzz commented
rebase

2024-04-28 13:18 UTC, sikkzz submitted a review, later dismissed

2024-04-30 16:35 UTC, pizzaYami approved these changes, later dismissed

2024-05-01 11:15 UTC, khkh0109 approved these changes, later dismissed

2024-05-04 13:16 UTC, sikkzz submitted a review, later dismissed

2024-05-06 09:38 UTC, pizzaYami submitted a review, later dismissed

2024-05-06 10:53 UTC, khkh0109 submitted a review, later dismissed

2024-05-06 12:35 UTC, sikkzz approved these changes

2024-05-06 12:41 UTC, khkh0109 approved these changes

2024-05-06 13:06 UTC, pizzaYami approved these changes

2024-05-06 13:06 UTC, merged