[TS-302] StarPrizeModal 리팩토링, habitRecordConstants 위치 변경
ConnectingStar/ConnectingStar-Front pull request #69
Opened 2024-04-04 10:08 UTC by youngTkim

[TS-302](https://m2jun.atlassian.net/browse/TS-302)

## 💡 변경사항 & 이슈
/habit-record에서 확인 가능

- 디자인 작업방-습관 생성 옆에 마무리 모달이 있어서 응용하기 위해 수정했습니다.
- habitRecordConstants를 homeConstants로 통합했습니다.
- homeConstants에서 주석된 예시를 통해서 확인할 수 있습니다.

<br>

## ✍️ 관련 설명
<br>

## ⭐️ Review point
 주석으로 된 부분이 멘트로 들어갔을 때 디자인이 깨지는지, 버전을 나누는 더 나은 로직이 있는지
<br>

## 📷 Demo
<img width="723" alt="스크린샷 2024-04-04 오후 6 56 23" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/117588223/d5ce385d-dbae-4c3f-883e-ef5d274f3ac7">
<img width="288" alt="스크린샷 2024-04-04 오후 7 02 54" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/117588223/e48a717b-a813-4cb1-930b-432f9ee7cb16">
<br>

[TS-302]: https://m2jun.atlassian.net/browse/TS-302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-04-04 10:29 UTC, sikkzz requested changes

2024-04-04 10:29 UTC, sikkzz commented on src/components/Home/HabitRecord/HabitRecord.tsx
> +					version={"ver1"}
version이란 명칭과 구분은 안좋아보입니다. boolean값으로 차이를 둬서 판단하는게 좋아 보이네요

2024-04-04 10:29 UTC, sikkzz commented on src/constants/homeConstants.tsx
> +};
불필요합니다

2024-04-05 05:01 UTC, pizzaYami requested changes

2024-04-05 05:01 UTC, pizzaYami commented on src/components/Home/Landing/Modal/StarPrizeModal/StarPrizeModal.tsx
> +					text={`${version === "ver1" ? "별자리 채우기" : "별자리로 가기"}`}
```
<FooterBtn
  leftText={version === "ver1" ? "홈으로" : "홈 탐색하기"}
  text={version === "ver1" ? "별자리 채우기" : "별자리로 가기"}
  isTransparent
/>
```

2024-04-05 05:01 UTC, pizzaYami commented on src/components/Home/Landing/Modal/StarPrizeModal/StarPrizeModal.style.ts
>  	}
nth-of-type 과 first-of-type / last-of-type 둘 중 하나로 통일시키거나
위와같이 nth-of-type, last-fo-type이 아니라 갑자기 .yellow가 나와서 통일성이 없어보입니다.

2024-04-09 02:33 UTC, pizzaYami commented
머지 후에 header 조정

2024-04-12 08:04 UTC, pizzaYami commented on src/components/Home/Landing/Modal/StarPrizeModal/StarPrizeModal.tsx
> +					text={`${version === "ver1" ? "별자리 채우기" : "별자리로 가기"}`}
바꿔주세요

2024-04-12 08:07 UTC, pizzaYami requested changes

2024-04-12 08:07 UTC, pizzaYami commented on src/components/Home/HabitRecord/HabitRecord.tsx
> +					version={"ver1"}
변경 안 하셨는데  solove하신 것 같네요
version boolean으로 변경안하셔도 version="ver1"으로는 바꿔주세요

2024-04-13 00:55 UTC, youngTkim commented on src/components/Home/Landing/Modal/StarPrizeModal/StarPrizeModal.tsx
> +					text={`${version === "ver1" ? "별자리 채우기" : "별자리로 가기"}`}
넵 바꿨습니다 확인부탁드릴게영

2024-04-13 09:53 UTC, sikkzz requested changes

2024-04-13 09:53 UTC, sikkzz commented on src/components/Home/Landing/Modal/StarPrizeModal/StarPrizeModal.tsx
> +	isHabitStart: boolean;
옵션으로 넣고 isHabitstart일때만 필요한거 렌더링 시켜주면 됩니다. props true, false 둘다 받을 필요 없어요

2024-04-13 09:53 UTC, sikkzz commented on src/components/Home/HabitRecord/HabitRecord.tsx
> +					isHabitStart={false}
false prop은 필요 없습니다

2024-04-13 09:53 UTC, sikkzz commented on src/components/Home/Landing/Modal/StarPrizeModal/StarPrizeModal.tsx
> +					text={`${!isHabitStart ? "별자리 채우기" : "별자리로 가기"}`}
백틱

2024-04-15 10:51 UTC, sikkzz approved these changes

2024-04-15 10:55 UTC, pizzaYami approved these changes

2024-04-15 11:16 UTC, khkh0109 approved these changes

2024-04-15 11:32 UTC, merged