globalStyle 변경
ConnectingStar/ConnectingStar-Front pull request #7
Opened 2024-01-30 09:32 UTC by pizzaYami

[TS-206]

## 💡 변경사항 & 이슈
글로벌스타일 폰트 작동하도록 변경
theme 소문자로 변경
color 색상코드형식으로 변경(#)
폰트 size와 weight묶어서 사용

## ✍️ 관련 설명
피그마에 대부분 head_a, body_a 형식으로 다 만들어 놔서 폰트 size와 weight묶어서 사용하는게 훨씬 편할 것 같아서 저렇게 작성했습니다.

## ⭐️ Review point
size와 weight부분
theme와 글로벌스타일 제대로 적용되는지 확인

## 📷 Demo
없음

2024-01-30 10:54 UTC, sikkzz requested changes

2024-01-30 10:54 UTC, sikkzz commented on src/styles/theme.ts
> +	size: {
size보다는 font가 어울리지 않을까요? Theme.font.head_a 이렇게 사용하면 될 거 같아서요!

2024-01-30 10:54 UTC, sikkzz commented on src/styles/theme.ts
> +		BG: "#F7F7FB",
이친구만 대문자인 이유가 있을까요? 따로 없다면 통일하는게 좋을거 같네요

2024-01-30 10:55 UTC, sikkzz commented
추가적으로 기본 default font weight이 400 regular로 알고 있는데 해당 font weight들은 따로 설정안해줘도 괜찮을거 같아요

2024-01-31 02:06 UTC, khkh0109 commented on src/styles/globalStyle.ts
> +	@font-face {
폰트 적용이 제대로 안된것 같은데 확인 부탁드려요 
개발자 도구 열어서 텍스트 선택한 다음 Computed 탭 > 제일 아래쪽에 있는 Rendered Fonts 부분 보시면 실제로 렌더링 된 폰트
를 확인할 수 있습니다. 현재는 Noto Sans KR이 적용되어 있지 않고 기본 텍스트가 적용되고 있어요

<img width="322" alt="스크린샷 2024-01-31 오전 11 03 03" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/4b29f425-7ed2-4411-a99d-80f34f1ac5df">

2024-01-31 02:22 UTC, khkh0109 commented on src/styles/theme.ts
> +		body_c_bold: {
디자인 시스템 상 이름과 조금 다른데 헷갈릴 여지가 없을까요? 
디자인에는 `Tars_C Body_Mid`라는 이름으로 되어있고 실제 폰트도 Medium 사이즈로 설정되어 있습니다. 
나중에 실제 bold 사이즈가 추가될 수도 있고, 헷갈릴 수 있을것 같은데 이름을 blod 대신 mid 또는 medium으로 변경하는게 어떨까요?

2024-01-31 02:27 UTC, khkh0109 commented on src/styles/theme.ts
> +		button_large: {
이 부분은 굉장히 사소한 부분이라 그냥 넘어가도 될듯한데 혹시 몰라 의견을 덧붙입니다. 

나중에 세림님과 상의해서 big 또는 large 둘 중 하나로 정하는게 나을것 같네요! 지금 당장은 사용할때 문제가 없을것 같은데, 그래도 최대한 피그마에서 사용하는 이름과 통일하는게 헷갈릴 여지가 줄어들것 같아서요!

2024-01-31 02:46 UTC, khkh0109 commented on src/styles/theme.ts
> +		// 폰트 색상
혹시 색상 이름도 세림님이 정해주신건가요? 그게 아니라면 세림님과 상의해서 명확한 이름으로 정하는게 개발할때 편할것 같아요.

피그마에서는 폰트 색상 이름이 Font, Font 002, Font 003으로 되어있는데 코드 상 이름과 바로 매치하기 힘들것 같습니다. 뚜렷하게 구분되는 색이라면 모를까 그레이는 바로 구별이 힘들것 같아서요,, 

<img width="225" alt="스크린샷 2024-01-31 오전 11 32 59" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/8c58b522-b091-4772-83a3-54cc9cf94f12">

또 검정색도 어떤건 #000000이고 Font의 색은 #111111이라 블랙도 그레이처럼 두 가지 색으로 나뉘는건지 아니면 하나만 쓰는건지 명확하게 하고 넘어가면 좋을것 같네요!

2024-01-31 02:53 UTC, khkh0109 commented on src/styles/theme.ts
> +		button_deactivated: "#999999",
그리고 이 부분도 디자인 시스템에서는 Deactivated라고 적혀있지만 실제 시안에서는 그냥 Disabled로 사용되고 있습니다. 그래서 개발 하다보면 헷갈릴것 같은데 이 부분도 세림님과 상의 후에 통일하면 좋을것 같아요! 

<img width="363" alt="스크린샷 2024-01-31 오전 11 51 27" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/c7eaeea1-cbd3-4b4f-b840-e21d2591850c">

2024-01-31 02:55 UTC, khkh0109 commented on src/styles/theme.ts
> +	size: {
저도 size 보다는 font가 알아보기 쉬울것 같아요

2024-01-31 02:58 UTC, khkh0109 commented on src/styles/theme.ts
> +		BG: "#F7F7FB",
저도 특별한 이유가 있는게 아니라면 소문자로 통일하는게 보기 편할것 같습니다

2024-01-31 03:15 UTC, khkh0109 commented on src/styles/globalStyle.ts
> +	}
폰트 적용이 제대로 안된것 같은데 확인 부탁드려요 
개발자 도구 열어서 텍스트 선택한 다음 Computed 탭 > 제일 아래쪽에 있는 Rendered Fonts 부분 보시면 실제로 렌더링 된 폰트를 확인할 수 있습니다. 현재는 Noto Sans KR이 적용되어 있지 않고 기본 텍스트가 적용되고 있어요

<img width="322" alt="스크린샷 2024-01-31 오전 11 03 03" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/4b29f425-7ed2-4411-a99d-80f34f1ac5df">

2024-02-01 08:20 UTC, khkh0109 commented on src/styles/globalStyle.ts
> +	}
HTML로 폰트 가져온거면 `@font-face { ... }`이 부분은 이제 없어도 되겠네요! 테스트 해보니 없어도 폰트 적용 잘 됩니다

2024-02-01 08:36 UTC, sikkzz commented
font-weight 400 삭제 수정 안된거 같습니다.

추가적으로 수정한 리뷰들은 resolve눌러주시거나 수정했다고 답변 달아주셔야 할 거 같아요. 그래야 리뷰한 사람도 수정했다고 확인할 수 있을 거 같아서요

2024-02-01 09:34 UTC, pizzaYami commented
font-weight 400 삭제가 어떤 부분이죠?

2024-02-01 09:35 UTC, sikkzz commented
> font-weight 400 삭제가 어떤 부분이죠?

기본 font-weight가 400이기 때문에 400설정은 따로 안해줘도 됩니다! font-weight 400 코드들은 다 제거하시면 됩니다

2024-02-02 09:59 UTC, pizzaYami commented
font-weight 400 삭제 완료

2024-02-02 10:57 UTC, sikkzz approved these changes, later dismissed

2024-02-02 11:29 UTC, khkh0109 approved these changes, later dismissed

2024-02-05 05:34 UTC, youngTkim submitted a review, later dismissed
theme.ts에 색상 추가 확인했습니다.

2024-02-06 08:08 UTC, khkh0109 approved these changes

2024-02-06 08:31 UTC, merged