[TS-303] 별자리 캐릭터 해금 모달 추가
ConnectingStar/ConnectingStar-Front pull request #70
Opened 2024-04-04 11:46 UTC by khkh0109

[TS-303](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?assignee=616ccf7525f31300702d29cb&selectedIssue=TS-303)

## 💡 변경사항 & 이슈
별자리 캐릭터 해금 모달 추가
<br>

## ✍️ 관련 설명
별자리 메인 페이지에 있는 '별자리 캐릭터 해금 모달'을 추가했습니다. 
- /star 경로에서 확인 가능
- 별자리 캐릭터 이미지는 api 작업 후 추가 예정입니다. 지금은 임시로 회색 배경을 추가해두었습니다. 
- 별자리는 이 브랜치에 없어서 동그라미 별 버튼을 누르면 바로 모달이 등장합니다. 추후 별자리가 추가되면 모달 등장 흐름이 수정될 예정입니다. 
<br>

## ⭐️ Review point
- [ ] 모달 사용 방법 맞는지
- [ ] 디자인 시안과 일치하는지

확인 부탁드립니다~
<br>

## 📷 Demo
<img width="300" alt="스크린샷 2024-04-04 오후 8 44 11" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/55450249-b933-4e3b-ba30-dd2b23151953">

<br>

2024-04-05 05:09 UTC, pizzaYami requested changes

2024-04-05 05:09 UTC, pizzaYami commented on src/components/StarPage/Modal/CharacterUnlockModal.tsx
> +		background-color: #d9d9d9;
background-color: transparent;로 바꾸시면
공통 모달 컴포넌트에 기본적으로 background-color: rgba(0, 0, 0, 0.8);으로 설정되어 있는데 이거 어떻게 제거 하실건가요?

2024-04-05 08:59 UTC, khkh0109 commented on src/components/StarPage/Modal/CharacterUnlockModal.tsx
> +		background-color: #d9d9d9;
조금 더 자세히 설명해주시겠어요? 공통 모달 컴포넌트의 `background-color: rgba(0, 0, 0, 0.8);` 이 부분을 변경한다는게 어떤 의미인지 잘 모르겠습니다

코드에 체크해주신 `background-color: #d9d9d9;` 이 부분은 현재 이미지가 없어서 그냥 영역 확인 & border-radius가 디자인 시안과 동일한지 확인 용도로 넣어둔 배경색이고 추후 이미지가 들어가면 삭제할 예정입니다.

2024-04-05 10:11 UTC, pizzaYami commented on src/components/StarPage/Modal/CharacterUnlockModal.tsx
> +		background-color: #d9d9d9;
![스크린샷 2024-04-05 오후 7 01 54](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/0178bb5e-7a99-47c3-91d2-4aa013388242)

아 제가 좀 착각한게 있었네요. 이상하게 강희님한테만 이러는 듯 하네요ㅋㅋㅋ

캐릭터 뒷 배경이 starMainPage처럼 반짝이는 것처럼 보이길래 transparent으로 바뀌면 뒤에 배경보이면서 반짝이는 효과 보이도록 만드시나보다 생각했는데 starMainPage에 별자리가 위치하게 되니깐 그렇게 만들면 안되겠네요.

2024-04-05 10:22 UTC, khkh0109 commented on src/components/StarPage/Modal/CharacterUnlockModal.tsx
> +		background-color: #d9d9d9;
아 그런 의미였군요..! 모달 내부에 들어갈 이미지 자체가 저렇게 생긴거예요! 별자리 메인 페이지 배경이랑 똑같아서 헷갈릴만하네요

2024-04-05 15:39 UTC, pizzaYami approved these changes

2024-04-06 16:10 UTC, youngTkim approved these changes

2024-04-07 08:37 UTC, sikkzz approved these changes

2024-04-07 11:58 UTC, merged