[TS-293] 별자리 추가
ConnectingStar/ConnectingStar-Front pull request #72
Opened 2024-04-10 01:05 UTC by khkh0109

[TS-293](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?assignee=616ccf7525f31300702d29cb&selectedIssue=TS-293)

## 💡 변경사항 & 이슈
별자리 메인 페이지에 별자리를 추가했습니다. 
<br>

## ✍️ 관련 설명
- /star 경로에서 확인 가능 
- 별자리는 api로 받아올 예정
- 현재는 화면에 어떻게 보이는지 파악을 위한 테스트용 별자리가 들어가있는 상태

### 별자리
- 정적 svg 파일에 동적인 스타일링 효과를 주는게 힘들어서 StarCharacter 컴포넌트를 만들었습니다(내부에서 svg 데이터를 조합해 별자리 svg를 만드는 방식)
- 사용자 상호작용과 관련된 것들은 api 추가하면서 함께 작업할 예정입니다. (+관련 애니메이션도)
- 현재는 기본 상태 별자리, 별이 채워졌을때 별자리 UI만 확인할 수 있습니다. 
- StarMainPage 제일 하단에 있는 data 객체에서 circleList의 filled를 바꿔서 각 별자리 UI를 볼 수 있습니다. 
  - true는 별 채워졌을때 / false는 기본 상태의 별

### 필터 효과 (별 빛나는 부분)
- css filter로 시도했으나 사파리에서 제대로 동작하지 않았습니다. (+또 drop-shadow로는 디자인 시안과 비슷한 선명한 빛 생성이 어려움)
- css `filter: url(#id)` 이렇게 id를 지정하면 가능하긴 하지만 각 요소의 id를 선택해야 하는게 별로라 g 요소에 filter를 동적으로 삽입하는 방식을 사용했습니다.

### 화면 레이아웃 변경
- 기존: 페이지 전체에 패딩을 적용 / 변경: 페이지 top/middle/bottom으로 나눠 구성
- 변경 이유
  - 별 파란색 그림자가 패딩을 벗어날 경우 일부 잘림
  - 별자리, 별자리 캐릭터는 양 옆 패딩을 벗어나도 됨(벗어나는 디자인 일부 존재)
- 이런 이유로 레이아웃을 좀 더 쉽게 잡기 위해 페이지를 세 부분으로 나눴습니다. 

### 임시 데이터
테스트용으로 StarMainPage 하단에 임시 데이터(data 객체)를 넣어두었는데 추후 삭제될 예정입니다. (현재 api 구조와 동일)
<br>

## ⭐️ Review point
- [ ] 컴포넌트 이름 괜찮은지
- [ ] 디자인 시안과 다른 부분
- [ ] 더 괜찮은 방법..
<br>

## 📷 Demo
|기본|별 채워짐|
|---|---|
|<img width="300" alt="스크린샷 2024-04-10 오전 8 53 03" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/edbf8613-0275-4d56-b189-d12962a342b3">|<img width="300" alt="스크린샷 2024-04-10 오전 8 57 25" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/6d3b62d6-f8c7-423a-bad1-8ee10edd7a67">|

<br>

2024-04-10 03:28 UTC, pizzaYami approved these changes

2024-04-10 03:34 UTC, pizzaYami requested changes

2024-04-10 03:34 UTC, pizzaYami commented on src/pages/StarMainPage/StarMainPage.tsx
> +				<StarCharacter svgData={data} />
div로 감싸서 className준 부분을 StarInfo, StarCharacter 내부로 못 보내나요?

2024-04-10 06:03 UTC, khkh0109 commented on src/pages/StarMainPage/StarMainPage.tsx
> +				<StarCharacter svgData={data} />
그렇게 할 수 있긴 한데 컴포넌트 내부에서 레이아웃을 정하는게 나으신가요? 

페이지 컴포넌트에서 레이아웃(패딩이나 마진으로 페이지 여백 주는 부분) 관련 스타일링을 하는게 좀 더 관리하기 편하지 않을까 싶었습니다. 각 컴포넌트에는 최대한 그 컴포넌트랑 가까운 스타일 속성만 두게끔..?

2024-04-11 09:51 UTC, sikkzz requested changes

2024-04-11 09:51 UTC, sikkzz commented on src/pages/StarMainPage/StarMainPage.tsx
> +				<StarCharacter svgData={data} />
저는 컴포넌트 내부에서 하는게 나아보이긴 해요 각 컴포넌트의 속성은 컴포넌트 내부에서 관리하는게 용이해보여서요

배경이든 어떤 속성이든간에 컴포넌트에서의 코드는 그 컴포넌트에서만 관리하는게 좋지 않을까요?

2024-04-11 11:55 UTC, pizzaYami commented on src/pages/StarMainPage/StarMainPage.tsx
> +				<StarCharacter svgData={data} />
css관련된 건 최대한 숨기는게 낫은 것 같아서 동일한 의견입니다.

2024-04-12 08:48 UTC, khkh0109 commented on src/pages/StarMainPage/StarMainPage.tsx
> +				<StarCharacter svgData={data} />
그럼 내부로 옮겨보도록 하겠습니다!

2024-04-15 01:35 UTC, khkh0109 commented
## 변경사항 
- pathList -> path
  - path d를 문자열 하나로 합쳐도 동일하게 보여서 합침
  - api도 배열이 아닌 문자열로 올 예정, 이름도 path로 전달해 주신다고 함

2024-04-15 10:54 UTC, sikkzz approved these changes

2024-04-15 10:56 UTC, pizzaYami approved these changes

2024-04-16 11:02 UTC, youngTkim approved these changes

2024-04-18 09:43 UTC, merged