[TS-307] ChattingPage와 관련 모달 헤더변경으로 인한 padding변경
ConnectingStar/ConnectingStar-Front pull request #74
Opened 2024-04-10 05:25 UTC by pizzaYami

[TS-307](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109/backlog?selectedIssue=TS-307)

## 💡 변경사항 & 이슈
ChattingPage, SelectTagModal, LocationModal의 padding 및 z-index 변경
모달 연결 및 헤더 기능 추가는 다른 브랜치에서 변경예정 (timemodal 머지 후)
<br>

## ✍️ 관련 설명
<br>

## ⭐️ Review point
헤더 이상한 부분
<br>

## 📷 Demo
<br>
![스크린샷 2024-04-10 오후 2 24 04](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/4e48c251-fbc6-47ca-9d74-a046fa74a292)
![스크린샷 2024-04-10 오후 2 23 27](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/ee0cddbd-83d2-480e-8b4a-5dbe051fdc07)
![스크린샷 2024-04-10 오후 2 23 13](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/f8ccbace-42f9-48df-a057-d2f8a7fef72f)

2024-04-10 13:09 UTC, youngTkim approved these changes

2024-04-11 02:45 UTC, khkh0109 approved these changes

2024-04-11 07:21 UTC, youngTkim approved these changes

2024-04-11 09:51 UTC, sikkzz approved these changes

2024-04-11 09:52 UTC, sikkzz requested changes

2024-04-11 09:52 UTC, sikkzz commented on src/components/Chatting/LocationModal/LocationModalStyle.ts
> +	z-index: 50;
z-index 50의 사유가 있나요? 다른 z-index들이랑 고려해서 한단계씩만 높여서 사용하는게 좋을텐데요

2024-04-11 11:04 UTC, pizzaYami commented on src/components/Chatting/LocationModal/LocationModalStyle.ts
> +	z-index: 50;
헤더에 z-index 49가 되어있어서 모달띄울때 chattingPage헤더가 보이더라고요

2024-04-11 12:18 UTC, sikkzz approved these changes

2024-04-11 12:19 UTC, merged