[TS-308] home style 수정, habitCheckModal footerBtn 추가
ConnectingStar/ConnectingStar-Front pull request #76
Opened 2024-04-11 08:49 UTC by youngTkim

[TS-308](https://m2jun.atlassian.net/browse/TS-308)

## 💡 변경사항 & 이슈
/

-HabitCheckModal footerBtn 추가, 요소간 간격 marginBottom으로 조정
-gnb 크기 만큼 paddingBottom.3.5rem 추가
-home 및 home > Landing 이하 컴포넌트의 태그 수정

<br>

## ✍️ 관련 설명
모달 관련 디자인, footerBtn 관련 디자인, 다른 스타일이나 로직 이상한 점있으면 확인 부탁드립니다.
<br>

## ⭐️ Review point
<br>

## 📷 Demo
<img width="313" alt="스크린샷 2024-04-11 오후 5 47 33" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/117588223/057039e9-ce88-4e53-89a4-7e535e6f42c9">
<img width="777" alt="스크린샷 2024-04-11 오후 5 40 32" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/117588223/54e83dcd-d084-48af-ac29-026a4d67775a">
<img width="436" alt="스크린샷 2024-04-11 오후 5 43 41" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/117588223/18c54c57-9abd-4cb5-a3cc-c15cdb7dc695">

<br>

2024-04-11 19:20 UTC, sikkzz commented
전혀 연관되지 않은 기능들은 PR 따로 올려주세요.

지금 보시면 PR 각각의 내용들이 연관성이 전혀 없습니다. 코드량이 많지 않기에 이건 그냥 리뷰 해드리겠습니다

2024-04-11 19:40 UTC, sikkzz requested changes

2024-04-11 19:40 UTC, sikkzz commented on src/components/Home/Landing/Modal/HabitCheckModal.tsx
> +				<FooterBtn leftText="쉬는 날 🙂" text="실천 완료 😎" isPositionStatic isTransparent />
각 버튼들의 기능들은 안들어가나요?

2024-04-11 19:40 UTC, sikkzz commented on src/components/Home/Landing/Advices/Advices.tsx
>  			</ul>
하나의 컴포넌트로 묶고 adviceImages.map으로 다 렌더링 시키면 될 거 같네요 굳이 새로운 배열 쓸 필요 없어보여요 return문도요

2024-04-11 19:40 UTC, sikkzz commented on src/components/Home/Landing/Advices/Advices.tsx
> +	};
사실 좋지 않은 코드입니다.

scroll을 timeout을 통해 조절하기에 time modal때도 그렇고 지금도 정상적으로 작동 안할때가 많습니다. 또한 ref로 DOM 접근이 많이 일어나게 됩니다. IntersectionObserver 서칭 및 학습해보시고 적용시켜보시는걸 권장합니다.

timeout 없이 코드 수정 가능할거에요

2024-04-12 00:07 UTC, sikkzz commented on src/components/Home/Landing/Advices/Advices.tsx
> +	};
아니면 한번 스크롤에 하나씩만 넘어가게 수정하는 방법도 있긴 하겠네요

2024-04-12 08:21 UTC, pizzaYami commented
calender.tsx 파일이 두개 있어서 둘 중 하나는 이름을 변경해야합니다.

2024-04-12 08:26 UTC, pizzaYami approved these changes, later dismissed

2024-04-12 08:26 UTC, pizzaYami commented on src/components/Home/Landing/Advices/Advices.style.ts
>  		display: flex;
align-items: flex-end; 추가

2024-04-12 08:26 UTC, pizzaYami commented on src/components/Home/Landing/Advices/Advices.style.ts
> +	transform: translateY(${isCurrentIndex ? "-2px" : "0px"});
transform: translateY(${isCurrentIndex ? "-2px" : "0px"}); 요거 제거

피그마보면 하단선에 맞추어 정렬되어있는데 현재는 정렬되어있지않아요.
이렇게 하는게 미세하긴한데 더 정확하게 표현된 거 같네요

2024-04-12 12:46 UTC, sikkzz commented on src/components/Home/Landing/Advices/Advices.tsx
> +	};
고민해봤는데 해당 기능은 한번 스크롤에 하나씩만 넘어가는게 맞는 거 같습니다. 지금처럼이면 스와이프 한번 했을때 배너가 여러개 넘어가버리니까 하나씩이 맞는 거 같네요

해당 방향성으로 수정하는게 좋지 않을까요? 애매하면 기획단에 물어보셔도 됩니다

2024-04-13 00:37 UTC, youngTkim commented on src/components/Home/Landing/Advices/Advices.tsx
> +	};
아 넵넵 한번 여쭤보고 수정하겠습니다

2024-04-15 07:27 UTC, khkh0109 commented on src/components/Home/Landing/Advices/Advices.style.ts
> +	background-color: ${isCurrentIndex ? theme.color.main_deep_blue : "white"};
이 부분 피그마 보시면 현재 index 아닌건 'Line or BG 2' 색상(theme.color.line)입니다 확인부탁드려요!

2024-04-22 16:11 UTC, sikkzz commented on src/components/Home/Landing/Advices/Advices.tsx
> +	};
라이브러리 쓰신 이유가 있을까요? 현재 상태가 기획 최종 단계랑 동일하다면 한번 슬라이드할때마다 하나씩 넘어가게 충분히 구현할 수 있지 않나요

라이브러리 쓰면 안좋은 이유는 많이 존재합니다. 현재 경우에서는 다음과 같습니다

1. 라이브러리에서 필요한 코드만 끌어다 쓰는게 아니기 때문에 일부 기능을 위해 라이브러리를 설치해야한다는점, 슬라이드 기능은 라이브러리를 쓸만큼 어렵거나 고도의 기능이 아니기 때문에 더더욱 그렇습니다
2. 이로 인해 서비스 용량 증가 -> 메모리 많이 잡아먹음 + 로딩 느려짐

저희같은 소규모 프로젝트에 크게 영향이 가는 부분은 물론 아닙니다. 다만 현업 서비스 기준 필요한 기능들을 서비스에 맞춰서 개발하고 그걸 공통으로 쓰는 이유는 위와 같은 이유도 포함되어 있습니다.

추가적으로 영택님은 현재 라이브러리 사용으로 advice 코드는 짧아졌을지 몰라도 궁극적인 코드량이 줄어든건 아닙니다. 스타일링 코드에 코드량을 많이 잡아먹으셨기 때문이죠 이러면 라이브러리가 아니라 순수 기능 구현이 낫지 않나요?

2024-04-22 16:12 UTC, sikkzz requested changes

2024-04-22 16:12 UTC, sikkzz commented on src/components/Home/Landing/Advices/Advices.tsx
> +					</div>
key값 에러납니다. 물론 수정해야겠지만요

2024-04-23 11:57 UTC, youngTkim commented on src/components/Home/Landing/Advices/Advices.tsx
> +	};
swipe 기능이랑 무한 캐러셀 부분에서 좀 걸려가지고요... 한 번 확인해보겠습니당

2024-04-23 11:58 UTC, youngTkim commented on src/components/Home/Landing/Advices/Advices.tsx
> +					</div>
넵 수정하겠습니당

2024-04-23 12:35 UTC, sikkzz commented on src/components/Home/Landing/Advices/Advices.tsx
> +	};
우선 기능은 정상 작동 하니까 key값 오류만 수정하면 approve 해놓겠습니다. 다만 이후에 리팩토링 해주세요. 이거랑 제가 이전에 말씀드린 버튼 공통화도 해주시구요

2024-04-26 07:15 UTC, pizzaYami commented
라이브러리 도입은 승인된건가요?

2024-04-26 18:07 UTC, sikkzz commented
> 라이브러리 도입은 승인된건가요?

우선 구현하셨고 기능은 정상이니 얘는 머지하고 리팩토링 해서 다시 올리시는거로 말씀드렸습니다

2024-04-26 18:07 UTC, sikkzz commented
rebase

2024-04-28 13:19 UTC, sikkzz commented
혹시 TS-4번 커밋은 왜들어가있는걸까요?

2024-04-29 11:55 UTC, youngTkim commented
> 혹시 TS-4번 커밋은 왜들어가있는걸까요?  엇 한번 확인해보겠습니다

2024-05-04 13:16 UTC, sikkzz submitted a review, later dismissed

2024-05-06 09:45 UTC, pizzaYami commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +			{modal === modalType.SELECT_TIME && <SelectTimeModal title="시간을 선택해주세요." />}
<SelectTimeModal title="시간을 선택해주세요." />}
점(.)을 빼야지 제대로 작동할거에요
```
if (title === "시간을 선택해 주세요") dispatch(updateHabitUserData({ time: updatedTime }));
		if (title === "1차 알림시간을 선택해 주세요")
			dispatch(updateHabitUserData({ alert1: updatedTime }));
		if (title === "2차 알림시간을 선택해 주세요")
			dispatch(updateHabitUserData({ alert1: updatedTime }));
```
1,2차알림도 위의 코드의 규격에 맞게 수정해야됩니다.

2024-05-10 07:54 UTC, sikkzz requested changes

2024-05-10 07:54 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +			)}
모달 타입을 따로 쓸 필요가 있나요? 모달 타입은 Select time 하나로 쓰는게 맞을 거 같은데요

2024-05-10 07:54 UTC, sikkzz commented on src/components/Home/Landing/HabitList/HabitList.tsx
> +					key={idx}
idx말고 data값으로 키값 써주세요

2024-05-10 07:55 UTC, sikkzz commented
라이브러리 안쓰고 제작하는 작업은 하고 계신가요? 말씀드린 작업들이 몇개 있는데 진행이 안보여서요

2024-05-10 15:30 UTC, youngTkim commented
> 라이브러리 안쓰고 제작하는 작업은 하고 계신가요? 말씀드린 작업들이 몇개 있는데 진행이 안보여서요

api가 나와서 공통 토글 박스를 제작하던 걸 깜빡하고 있었네요. 그만두기 공통 버튼이랑 같이 만들겠습니다. 죄송합니다.
그리고 react-slick은 github을 보니까 생각보다 필요로 하는 코드량이 많아서 https://github.com/akiran/react-slick 보고 있긴한데 이 부분은 라이브러리로 사용하시는건 어떠신가요?

2024-05-10 15:36 UTC, youngTkim commented
> 라이브러리 안쓰고 제작하는 작업은 하고 계신가요? 말씀드린 작업들이 몇개 있는데 진행이 안보여서요

그리고 작업 범위를 토글 있는 박스들로만 설정하면 되는걸까요? 토글 없는 박스까지 다 공통화시키려면 인자들이 많아질꺼같아서요.

2024-05-10 15:40 UTC, sikkzz commented
api 연결 진행중이면 api 먼저 하셔도 됩니다. 추가적인 pr 올라오는게 없으신데 존재하는 브랜치들 rebase만 시키셔서 말씀드렸습니다. 

라이브러리 사용 자체가 미사용하는 코드들이 많아지기 때문에 라이브러리 없이 구현할 수 있는 기능이라 라이브러리 없이 구현하는게 좋다고 말씀드렸었던거입니다. 어떤 라이브러리를 사용하던 그부분은 중요하지 않을 거 같네요. 미사용이 초점이니까요

버튼 공통화는 그냥 제가 진행하겠습니다. 영택님은 1순위 api 연결, 2순위 캐러샐 라이브러리 미사용 코드로 변경 이렇게 진행해주세요

2024-05-14 21:50 UTC, pizzaYami commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +			{modal === modalType.SELECT_TIME && <SelectTimeModal title={modalTitle} />}
이 부분은 저랑 준식님이랑 대화해보고 동일하게 하는게 낫겠네요

2024-05-20 07:38 UTC, khkh0109 commented
적용된 배너 이미지가 조금 다릅니다
아래 사진 보시면 점이 세개인데 두개인 배너 이미지로 적용 되었습니다,,!

|현재 배너 이미지|Figma 배너 이미지|
|---|---|
|<img width="600" alt="스크린샷 2024-05-20 오후 4 34 48" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/6721f64b-7607-4541-b35d-236573690d48">|<img width="600" alt="스크린샷 2024-05-20 오후 4 34 27" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/80999a5d-900b-4d03-8edf-dd2c41d73cdc">|

2024-05-23 20:30 UTC, merged