[TS-228] Header 컴포넌트 1차 구현
ConnectingStar/ConnectingStar-Front pull request #8
Opened 2024-01-30 14:31 UTC by khkh0109

[TS-228](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?selectedIssue=TS-228)

## 💡 변경사항 & 이슈
공통 Header 컴포넌트 제작
<br>

## ✍️ 관련 설명
공통 Header 컴포넌트를 만들었습니다. (1차 구현) 

### 이전에 상의한 내용
페이지 전반에 걸쳐 UI와 기능이 조금씩 다른 Header 컴포넌트가 빈번하게 등장하고 있습니다. 이 컴포넌트를 각각 구현한다면 **1) 세심하게 신경쓰지 않으면 디자인이 미묘하게 달라질 수 있다, 2) 비슷한것을 하나로 묶으면 재사용이 편하지 않을까** 라는 이유 때문에 하나로 합치자는 제안을 했습니다. 

우려했던 지점은 **props가 늘어나서 지저분해지는것** 입니다. 그래서 제가 제안했던 방법은 Header 내부에서 사용되는 컴포넌트를 만들어두고 **사용하는 곳에서 조합하는 방식**이었습니다. 이 방법 또한 복잡해질 가능성이 있기 때문에 우선 1차로 구현해보고 결과물을 본 다음 여전히 복잡하다면 합치지 않기로 했습니다. 

<br>

### 구현 내용
<img width="239" alt="스크린샷 2024-01-30 오후 9 26 11" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/6a636edd-3182-4ac5-b8cb-df681a61373b">
 
- 공통 Header 컴포넌트를 만들었습니다. 
- Header 컴포넌트 내부에는 Header를 만들때 필요한 하위 컴포넌트들이 있습니다. (아이콘, 버튼, 타이틀 등)
- Header 컴포넌트는 아래와 같은 구조입니다. 
```
Header // 하위 컴포넌트를 감싸고 전체 Header 영역을 잡는 컨테이너 역할
ㄴ PrevButton // 뒤로가기 버튼
ㄴ CloseButton // 닫기 버튼
ㄴ Title // 제목. size prop을 통해 제목의 크기를 결정
ㄴ ActionButton // 오른쪽에 있는 '완료'나 '관리' 버튼 
```
<br>

### 사용 방법 & 예시
`<Header>` 내부에 필요한 컴포넌트를 조합해서 사용합니다. 

<img width="241" alt="스크린샷 2024-01-30 오후 9 28 00" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/18dfebca-784f-49a0-ba92-7b93434d4f9d">

```tsx
// ex. 뒤로가기 버튼만 있는 Header
<Header>
  <Header.PrevButton />
</Header>

// ex. 닫기 버튼만 있는 Header
<Header>
  <Header.CloseButton />
</Header>
```
<br>

<img width="228" alt="스크린샷 2024-01-30 오후 9 30 55" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/295c40f9-e171-4c2a-bbe0-0183a892c5b7">

```tsx
// ex. 닫기 버튼, 제목, 액션 버튼이 있는 Header
<Header>
  <Header.CloseButton />
  <Header.Title>습관 관리</Header.Title>
  <Header.ActionButton onClick={handleCompletionButton}>완료</Header.ActionButton>
</Header>
```

<br>

<img width="222" alt="스크린샷 2024-01-30 오후 9 33 51" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/d61c87cb-a351-4bb4-9be9-90e60e71d204">

```tsx
// ex. 큰 제목만 있는 Header
<Header>
  <Header.Title size="large">통계</Header.Title>
</Header>
```

<br>

### 참고
- 다음 논의를 위한 1차 구현 내용입니다. 
- 구현 중 고민이 되는 내용은 NOTE, TODO 주석을 달아두었습니다. 추후 삭제 예정입니다. 
- 폴더가 아직 dev에 머지되지 않아서 src 내부에 바로 저장했습니다. 추후 적합한 폴더로 이동 예정입니다. 
- 내부 console.log는 버튼의 동작 확인을 위해 넣어두었고 추후 삭제 예정입니다.

<br>

### 구현 중 고민했던 점 
> 현재 상황에서는 크게 논의할 내용은 아닌것 같지만, 리뷰 시 도움이 될까하여 고민했던 지점도 함께 작성합니다. 
> 아직도 계속 고민중인 부분입니다..😢

#### 뒤로가기 & 닫기 버튼
- 뒤로가기 버튼은 모든 페이지에서 동일한 기능입니다. 그래서 기능을 외부에서 주입받을 필요가 없다고 판단해 '뒤로 가기' 기능이 트리거 될 onClick 이벤트 핸들러 자체를 PrevButton 내부에 두었습니다. 
- 닫기 버튼의 기능 구현은 어떻게 해야할지 지금으로써는 감이 잡히지 않습니다. 그래서 우선 PrevButton과 동일한 형태로 만들었습니다. 
- 뒤로 가기 버튼과 닫기 버튼을 분리했습니다. 초반에는 IconButton이라는 이름으로 합치고 iconType prop을 통해 버튼을 구분했습니다. 하지만 추후 다른 형태의 아이콘이 올 수도 있고, 그럼 그때마다 내부의 if문 분기가 길어질 것 같아서 그냥 분리했습니다. 

#### 제목
- 현재 Header의 제목은 두 가지 타입입니다. 1) 중앙에 오는 보통 사이즈의 제목, 2) 왼쪽에 붙어있는 큰 제목
- 그래서 초반에는 Title(보통 제목), TitleOnly(큰 제목)로 나누었습니다. 하지만 동일하게 제목을 보여주기만 하는데 나눠두면 오히려 혼란스러울것 같아서 하나로 합치게 되었습니다. 
- 대신 size라는 prop을 받고 large라면 큰 제목을 보여주도록 했습니다. 기본값은 보통 사이즈의 제목을 보여줍니다. (default와 large 대신 불리언 값 사용도 고민했으나 적당한 이름이 떠오르지 않아서 우선은 이렇게 구현했습니다 😓)

#### Header를 전부 합치는것에 대해
- UI가 조금씩 다른 형태지만 큰 맥락에서는 비슷해서 하나로 합치는 것을 제안했는데 구현하다보니 오히려 일을 복잡하게 만드는것이 아닐까? 라는 생각이 들었습니다. 
- 제 생각에는 Header 컴포넌트가 자주 바뀌지 않을것 같지만, 이건 예상하기 힘들어서 섣불리 말하기가 어렵네요. 
- 한편으로는 하위 컴포넌트를 조립하는 방식이라 괜찮지 않을까...싶기도 하고...
- 어쨌든 다들 보시고 의견 남겨주세요!

<br>

## ⭐️ Review point
- [ ] 사용하는 곳에서 보기에 Header 컴포넌트가 복잡하지 않은지
- [ ] 이런 방식으로 사용했을때 추후 예상되는 문제점이 없는지
- [ ] 정상적으로 동작하는지

확인 부탁드립니다. 

<br>

## 📷 Demo
Header 종류별 데모 입니다.

<img width="393" alt="스크린샷 2024-01-30 오후 9 51 12" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/6abcc688-1a2c-4c4f-93e1-cf296b73911a">

<br>

2024-02-01 09:30 UTC, sikkzz requested changes

2024-02-01 09:30 UTC, sikkzz commented on src/Header.tsx
> +		<div css={headerStyle.container} {...props}>
헤더 자체에서 props로 속성을 받을 여부가 있나요? 예시상에서는 확인 못한거 같아서요. 없다면 제거해도 될 거 같아요

2024-02-01 09:30 UTC, sikkzz commented on src/Header.tsx
> +import { headerStyle } from "./Header.style";
import 항상 절대경로로 부탁드려요. import order 작동도 절대경로 기준이에요

2024-02-01 09:30 UTC, sikkzz commented on src/Header.tsx
> +}
Type 파일 최상단으로 빼거나 Types 폴더에 작성하거나 해주세요. 이렇게 중간에 있으면 컴포넌트 코드들과 섞여서 혼란이 있을거 같네요

2024-02-01 09:30 UTC, sikkzz commented on src/Header.tsx
> +	size?: "default" | "large";
size가 명확하지 않은 이유가 무엇일까요? 저는 괜찮을 거 같은데요!

2024-02-01 09:31 UTC, sikkzz commented
제가 따로 전달드린 스타일 코드 문제 없는지 확인해보시면 될 거 같아요

현재로써는 작동도 문제 없는거 같은데 추후 각자 구현하다 문제가 생길 수도 있으니 그때 다시 얘기해봐야 할 거 같아요. 지금은 좋습니다

2024-02-01 11:13 UTC, khkh0109 commented on src/Header.tsx
> +import { headerStyle } from "./Header.style";
넵 까먹고 상대경로로 했네요 주의하겠습니다~!

2024-02-01 13:22 UTC, khkh0109 commented on src/Header.tsx
> +	size?: "default" | "large";
제목 스타일이 사이즈만 달라지는게 아니라 위치까지 함께 변경되는데 'size' 라는 이름에서는 이 부분이 제대로 드러나지 않는것 같아서요! 

뭔가 `size="large"`라고 하면 크기만 달라질거라고 예상했는데 위치까지 왼쪽으로 붙으면 조금 혼동이 올 것 같아서 명확하지 않다는 느낌을 받았습니다 ..

2024-02-02 11:37 UTC, sikkzz commented on src/Header.tsx
> +	size?: "default" | "large";
Large title을 사용하는 경우가 항상 왼쪽 버튼이 없는 경우가 맞다면 버튼 유무의 경우로 구분하는건 어떠세요? isLeftButton같은 이름 등으로 boolean값으로 받아서요! 명칭은 생각해봐야겠네요. 이런 방식도 있는거 같아서 말씀 드려요

2024-02-02 11:53 UTC, khkh0109 commented on src/Header.tsx
> +	size?: "default" | "large";
이 방식도 좋네요 현재 디자인 상으로 큰 제목이 있으면 버튼은 항상 없으니 버튼 유무로 관리하는 방식으로 생각해보겠습니다 ~!

2024-02-04 13:40 UTC, khkh0109 commented
## Header 스타일 수정 

이전에 준식님이 주신 코드로 변경을 했습니다. flex로 정렬을 하는 방법이었는데 이전 코드에 비해 깔끔하고 버튼 위치 변경에도 유연해서 괜찮았습니다. 하지만 다른 케이스는 전부 괜찮았는데 '왼쪽 아이콘 버튼, 중앙 제목'인 경우만 아래 사진처럼 레이아웃이 디자인과 달라졌습니다. 

<img width="360" alt="스크린샷 2024-02-04 오후 9 56 45" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/11f642a5-30d7-41a3-accb-899dad02eab8">

<br>

이 문제 해결을 위해 여러 시도를 했는데, 최종적으로 **제목은 flex로 중앙 정렬을 하고 버튼에 position: absolute를 적용하는 방식**으로 변경했습니다. 

더 괜찮은 방법 있으시면 알려주세요 

<br>

### 시도한 방법

#### 시도 (1) 제목에 margin: 0 auto → 중앙 정렬 된 것 처럼 보이지만, 디자인 시안과 미세하게 다름

<img width="360" alt="스크린샷 2024-02-04 오후 10 19 55" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/38238af0-5651-4640-b88b-db3c665b3e6c">

구현 화면(버튼 영역까지 고려되어서 디자인 시안과 조금 달라짐)

<img width="360" alt="스크린샷 2024-02-04 오후 10 22 07" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/e71e4c6f-c1e4-4dfc-87e6-16d2d5e56c8f">

디자인 시안(전체 Header 영역을 기준으로 중앙 정렬, 버튼 영역 고려 X)

#### 시도(2): Header container 제일 뒤에 가상요소 추가 → 마찬가지로 디자인 시안과 미세하게 다름, 다른 정렬도 무너짐

<img width="360" alt="스크린샷 2024-02-04 오후 10 27 21" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/e90cfc84-93a3-4bd3-9c44-166ade3e9e82">

2024-02-05 08:36 UTC, khkh0109 commented on src/Header.tsx
> +	size?: "default" | "large";
우선은 hasButton으로 변경했습니다,, 
다들 더 괜찮은 방법 있으면 알려주세여

2024-02-05 15:01 UTC, sikkzz approved these changes

2024-02-06 06:49 UTC, youngTkim approved these changes
스타일이랑 헤더 컴포넌트 정리가 깔끔하네요. 저도 다른 컴포넌트 만들 때 참조하겠습니다.

2024-02-07 11:53 UTC, pizzaYami approved these changes

2024-02-07 11:53 UTC, pizzaYami commented on src/Header.tsx
> +import CloseIcon from "./close.svg?react";
아직 폴더구조 PR을 머지안해서 src안에 다 넣어두신건가요?

2024-02-07 11:53 UTC, pizzaYami commented on src/Header.tsx
> +// NOTE: 닫기 버튼 기능 구현은 어떻게 할지..
쓰는 사람이 닫기관련된 함수자체를 보내버리게 하는건 어떨까요

2024-02-07 11:53 UTC, pizzaYami commented on src/Header.tsx
> +	size?: "default" | "large";
어떤 것의 사이즈인지 명확하지 않아서 TitleSize는 어떠신가여 
아니면 TItle의 위치를 고려해서 TitlePosition해서
middle | left 로 설정하는것도 좋아보여요

2024-02-07 11:53 UTC, pizzaYami commented on src/components/common/Header.tsx
> +}: ComponentPropsWithoutRef<"button">) {
검색을 해봐도 ComponentPropsWithoutRef 요게 무슨 역할을 하는지 정확히 이해가 안 가는데 설명이 가능할까요?

2024-02-07 11:56 UTC, khkh0109 commented on src/Header.tsx
> +import CloseIcon from "./close.svg?react";
헉 새 코멘트 달린걸 못봤네요! 이 부분은 반영되었습니다!

2024-02-07 11:58 UTC, khkh0109 commented on src/Header.tsx
> +// NOTE: 닫기 버튼 기능 구현은 어떻게 할지..
이 부분은 새 브랜치 파서 반영하겠습니다~!

2024-02-07 12:34 UTC, khkh0109 commented on src/components/common/Header.tsx
> +}: ComponentPropsWithoutRef<"button">) {
이렇게 한 이유는 현재 이 버튼에 들어올 props가 명확하지 않아서 `...props`로 사용하는 곳에서 넘겨주는 것을 전부 다 받게 설정했습니다. 
보통은 onClick이 오지만, '뒤로 가기'처럼 기능이 명확한 버튼이 아니라서 제가 예상하지 못하는 다른 핸들러가 올 수 있을 것 같다고 판단했어요. 그런데 새로운 핸들러(또는 html attributes)가 추가될때마다 Header.TextButton을 수정하면 번거로우니 `...props`를 통해 사용자가 직접 설정할 수 있게 만들었습니다. 
 
하지만 어떤 props가 오는지 명확하지 않다면 타입도 명확하게 지정할 수 없습니다. 그래서 ref만 제외한 나머지 프로퍼티를 타입으로 갖는 ComponentPropsWithoutRef를 타입으로 지정했습니다. 

이렇게 하면 html button 요소에 올 수 있는 type, name attributes 부터 onClick과 같은 이벤트 핸들러를 사용하는 곳에서 전달할 수 있습니다. 이런식으로요
```tsx
<Header>
  <Header.TextButton 
    type="button"
    name="custom button" 
    value="button" 
    onClick={() => console.log("click")}>취소
  </Header.TextButton>
</Header>
```

2024-02-07 13:00 UTC, merged