ChattingPage 모달 연결 및 버그수정
ConnectingStar/ConnectingStar-Front pull request #84
Opened 2024-04-24 13:22 UTC by pizzaYami

[TS-300](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109/backlog?assignee=712020%3A2697805c-34c2-4de5-99cb-4aab5f6d607a&selectedIssue=TS-300)

## 💡 변경사항 & 이슈

- BehaviorModal, LocationModal, SelectTagModal, SelectTimeModal 모달 연결
- 각 모달 헤더의 닫기버튼 활성화
- footer버튼 클릭시 progress 진행 -> 모달의 footer버튼 클릭시 progress 진행으로 변경

- ⬇️ 답글(reply)가 먼저나오는 경우가 있어서 적용

| 알림설정 | 모든 값 변경 |
|--------|--------|
| ![스크린샷 2024-04-24 오후 10 11 33](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/c4dd7cd2-99d5-4ab1-a416-72589c510fa1) | ![스크린샷 2024-04-24 오후 10 11 43](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/31424abc-22d1-4b29-a425-60abcdc2e7c8)
 | 

- 파란색 글자가 나오는 함수 제거 -> createChatData에서 직접 태그를 넣음
- time 설정이 alert1(-10분), alert2(+30분) 자동으로 적용

<br>

## ✍️ 관련 설명
코드가 조금 지저분하지만 나중에 리팩토링 하겠습니다.
<br>

## ⭐️ Review point
당장 리팩토링해야되는 코드

<br>

## 📷 Demo

https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/c9429459-8bee-44c5-94a0-10bcc2af48f3

<br>

2024-04-25 08:33 UTC, pizzaYami commented
317번 git pull origin 317번 --rebase 후에 git push origin 300번 --force 했는데 커밋히스토리에 남더라고요. rebase하면 다른 브랜치 커밋이 히스토리에 남지 않는다고 알고있는데 제가 뭘 잘 못 했을까요?

2024-04-26 18:16 UTC, sikkzz commented
여기는 317번 히스토리 꼬인거 해결되면 리뷰할게요

2024-04-30 12:43 UTC, pizzaYami commented
> 여기는 317번 히스토리 꼬인거 해결되면 리뷰할게요

해결됐습니다. 코드리뷰 부탁드려요

2024-04-30 18:20 UTC, sikkzz requested changes

2024-04-30 18:20 UTC, sikkzz commented on src/components/Chatting/BehaviorModal.tsx
> +import { useDispatch, useSelector } from "react-redux";
useAppdispatch, selector 쓰시면 됩니다 일부로 state 안넣고 사용하실 수 있게 만들어놓은건데 혹시 무슨 문제가 있어서 쓰는건가요?

2024-04-30 18:20 UTC, sikkzz commented on src/components/Chatting/BehaviorModal.tsx
> +	addprogres?: () => void;
오타같네요 addprogress 아래 코드에도 전부요

2024-04-30 18:20 UTC, sikkzz commented on src/components/Chatting/BehaviorModal.tsx
> +	const { habit } = useSelector((state: RootState) => state.user);
useAppSelector 쓰시면 state 타입 지정이 필요 없어져요

2024-04-30 18:20 UTC, sikkzz commented on src/components/Chatting/ChattingMessage.tsx
>  	useEffect(() => {
48라인 useEffeect랑 합칠 수 있어보이네요

2024-04-30 18:20 UTC, sikkzz commented on src/components/Chatting/ChattingMessage.tsx
> +		if (chatData.modalType === undefined) return;
!chatData.modalType으로 쓰면 될 거 같네요

2024-04-30 18:20 UTC, sikkzz commented on src/components/Chatting/ChattingMessage.tsx
> +	};
이 함수만 비동기 처리되어있는 이유가 있나요? 용도가 없어 보이는데

2024-04-30 18:20 UTC, sikkzz commented on src/components/common/Modal/CommonModal/LocationModal/LocationModal.tsx
> +	const dispatch = useDispatch();
useAppDispatch

2024-04-30 18:20 UTC, sikkzz commented on src/components/common/Modal/CommonModal/SelectTagModal/SelectTagModal.tsx
> +	const dispatch = useDispatch();
useAPP

2024-04-30 18:20 UTC, sikkzz commented on src/pages/ChattingPage.tsx
>  	const userData = useSelector((state: RootState) => state.user);
appselector

2024-04-30 18:20 UTC, sikkzz commented on src/pages/ChattingPage.tsx
> +						}}
```jsx
addProgress={() => setProgress((prev) => prev + 1)}
```

중괄호 하나씩 빼셔도 됩니다 아래 다 마찬가지에요

2024-04-30 18:22 UTC, sikkzz commented
기능이 전체적으로 너무 조건부로 동작하는 함수들이 많습니다. 내부 조건들도 한두개가 아니구요

에러 발생시 디버깅의 효율성, 리액트 기본 원칙인 SRP 고려하면 좋은 코드들은 아닐 수 있습니다. 단일 책임 원칙 (Single Responsibility Principle) 서칭해보시고 한번 코드 리팩토링 고려해보시길 추천합니다

2024-05-01 07:34 UTC, pizzaYami commented on src/components/Chatting/BehaviorModal.tsx
> +import { useDispatch, useSelector } from "react-redux";
기존에 배운대로 하다보니 useDispatch, useSelector를 사용했는데
아 이게 어떤 차이점이 있는지 몰라서 질문하려고했는데 state 안 넣어도되는 차이점이 있군요.
수정하겠습니다.

2024-05-01 07:41 UTC, pizzaYami commented on src/components/Chatting/BehaviorModal.tsx
> +import { useDispatch, useSelector } from "react-redux";
const dispatch = useAppDispatch();
	const { habit } = useAppSelector((state) => state.user);
이렇게 수정하는게 맞을까요? 맞다면 resolve 눌러주세요

2024-05-04 11:42 UTC, sikkzz commented on src/components/Chatting/ChattingMessage.tsx
> +	};
확인 부탁드려요

2024-05-06 09:49 UTC, pizzaYami commented on src/components/Chatting/ChattingMessage.tsx
> +	};
비동기제거했습니다!

2024-05-11 12:38 UTC, youngTkim approved these changes, later dismissed

2024-05-12 14:52 UTC, sikkzz approved these changes, later dismissed

2024-05-13 10:43 UTC, khkh0109 submitted a review, later dismissed

2024-05-13 21:27 UTC, merged