[TS-324] habit-guide 습관 도움말
ConnectingStar/ConnectingStar-Front pull request #89
Opened 2024-04-28 14:03 UTC by youngTkim

[TS-324](https://m2jun.atlassian.net/browse/TS-324)

## 💡 변경사항 & 이슈
/habit-guide,
/ 에서 습관 도움말 클릭 시에 이동

- 아코디언 스타일 습관 도움말 표시
- 클릭 시 제목 하이라이트, 해당 li로 scroll됨
<br>

## ✍️ 관련 설명
<br>

## ⭐️ Review point
기능이나 내용에 대해서는 준형님은 이상없다 하셔서, 디자인부분에서 이상 있나 봐주시면 되겠습니다.
<br>

## 📷 Demo
<img width="337" alt="스크린샷 2024-04-28 오후 10 59 19" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/117588223/d57b9ba3-6db8-4b09-9765-3a83e723166f">

<br>

2024-04-30 06:12 UTC, khkh0109 commented on src/constants/habitGuideConstants.tsx
> +		title: "시각화&공유로 부스터 달기",
혹시 전달받은 가이드 문서에 & 앞뒤로 띄어쓰기가 없었나요?
디자인 시안에는 & 앞뒤로 띄어쓰기가 들어가있습니다
문서와 동일하다면 그대로 넘어가도 될 것 같아요
```suggestion
		title: "시각화 & 공유로 부스터 달기",
```

2024-04-30 06:12 UTC, khkh0109 commented on src/components/Home/HabitGuide/HabitGuide.tsx
> +import ArrowIcon from "@/assets/icon/ic-arrow-left.svg?react";
화살표 아이콘 컬러가 검정이 아니라 회색이네요 확인부탁드려요

2024-04-30 18:34 UTC, sikkzz requested changes

2024-04-30 18:34 UTC, sikkzz commented on src/components/Home/HabitGuide/HabitGuide.tsx
> +							<p dangerouslySetInnerHTML={{ __html: paragraph }}></p>
이렇게 넣은 이유가 있으신가요? 그냥 데이터값 받아와서 써도 될 거 같은데요

2024-04-30 18:34 UTC, sikkzz commented on src/components/Home/HabitGuide/HabitGuide.tsx
> +					<li key={idx} css={itemStyle(activatedIndex === idx)}>
key는 title로 쓰는게 낫겠네요

2024-04-30 18:34 UTC, sikkzz commented on src/components/Home/HabitGuide/HabitGuide.tsx
> +				{habitGuideList.map(({ index, title, paragraph }, idx) => (
idx 필요 없이 activeIndex랑 데이터값의 index랑 비교하면 되지 않나요?

2024-04-30 18:34 UTC, sikkzz commented on src/components/Home/HabitGuide/HabitGuide.style.ts
> +`;
이렇게 자식 선택자로 특히 제일 많이 쓰이는 div를 스타일링하면 디버깅, 해당 스타일 찾기가 매우 어려워집니다.

게다가 이렇게 사용할꺼면 차라리 css 쓰는게 낫죠. css-in-js를 쓰는 의미가 하나도 없어집니다. 개발자 도구 엘리먼트 코드상으로도 추적도 다 불가능하고 emotion의 장점을 그냥 다 날려버리시면서 개발하고 있다고 생각이 드네요

2024-05-02 07:06 UTC, youngTkim commented on src/constants/habitGuideConstants.tsx
> +		title: "시각화&공유로 부스터 달기",
이거는 문서그대로내용

2024-05-02 07:32 UTC, youngTkim commented on src/components/Home/HabitGuide/HabitGuide.tsx
> +							<p dangerouslySetInnerHTML={{ __html: paragraph }}></p>
파란색 bold체가 들어가야해서 일단 이렇게 넣었습니당 혹시 더 좋은 방법이 있을까요??

2024-05-06 09:58 UTC, pizzaYami commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +			{modal === modalType.SELECT_TIME && <SelectTimeModal title="시간을 선택해주세요." />}
. 제거

2024-05-06 09:58 UTC, pizzaYami commented on src/constants/habitGuideConstants.tsx
> +		index: "01",
index를 number타입으로 하는게 더 깔끔해보입니다.

2024-05-10 21:40 UTC, pizzaYami submitted a review, later dismissed

2024-05-13 10:59 UTC, khkh0109 submitted a review, later dismissed

2024-05-19 13:01 UTC, sikkzz requested changes

2024-05-19 13:01 UTC, sikkzz commented on src/constants/habitGuideConstants.tsx
> +			</p>
백틱과 중괄호 없어도 가능 할 거 같네요 아래 전체 데이터들도요

2024-05-19 13:01 UTC, sikkzz commented on src/components/Home/HabitGuide/HabitGuide.tsx
> +	const handleButton = (idx: number) => {
무슨 handler인지 명시가 필요하겠죠?

2024-05-19 13:01 UTC, sikkzz commented on src/components/Home/HabitGuide/HabitGuide.tsx
> +		setActivatedIndex(idx);
```jsx
idx === activatedIndex ? setActivatedIndex(null) : setActivatedIndex(idx);
```

2024-05-19 13:23 UTC, youngTkim commented on src/constants/habitGuideConstants.tsx
> +			</p>
줄바꾸는건 p태그안에 div태그를넣고 gap을 설정해놓으면 될까요? 백틱과 중괄호는 없애고요. <p> <div></div> </p> 이렇게 해놓고 중간에 푸른 강조점 있는것만 <span className="bold"/>로 묶어놓으면 될까요?

2024-05-23 20:24 UTC, closed without merging