[TS-331] onboarding API 연결
ConnectingStar/ConnectingStar-Front pull request #91
Opened 2024-05-12 12:03 UTC by pizzaYami

[TS-331](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109/backlog?assignee=712020%3A2697805c-34c2-4de5-99cb-4aab5f6d607a&selectedIssue=TS-331)

## 💡 변경사항 & 이슈
331번이 아닌 다른 커밋내용들 300번 승인된 후 삭제 예정
/onboarding
온보딩 내용 이름 변경
온보딩 api연결

<br>

## ✍️ 관련 설명
- 온보딩 이름 변경
```
{
    nickName: "",
    gender: "",
    age: "",
    visitorRoute: "",
    habit: "",
    identity: "",
    time: { noon: "오전", hour: "10", minute: "00" },
    location: "",
    behavior: "",
    alert1: { noon: "오전", hour: "09", minute: "50" },
    alert2: { noon: "오전", hour: "10", minute: "10" },
};
```
```
{
    "nickname" : "테스트닉",
    "genderType" : "M",
    "ageRangeType" : "C",
    "referrer" : "들어온 경로",
    "identity" : "정체성테스트",
    "runTime" : { noon: "오전", hour: "09", minute: "50" },
    "place" : "장소",
    "behavior" : "행동",
    "behaviorValue" : 3,
    "behaviorUnit" : "단위",
    "firstAlert" : { noon: "오전", hour: "09", minute: "50" },
    "secondAlert" : { noon: "오전", hour: "09", minute: "50" },
}
```

- onboading post 요청
onboading과 관련된 모든 내용 한꺼번에 post요청 보내기 
ChattingMessage - postOnboarding 함수로 보냅니다.

- chattingPage에서 onboarding관련 모든 내용이 없다면 "/onboarding/createAccount"로 이동시키기
chattingPage - 29번째줄
```
	useEffect(() => {
		const { nickname, genderType, referrer } = userData;
		if (!nickname || !genderType || !referrer) {
			navigate("/onboarding?step=CreateAccount");
		}
	}, []);
```

- SelectGenderModal, SelectAgeModal 데이터 백엔드에서 가져오기
기존 프론트에서 보관하는 데이터를 get요청으로 가져와서 뿌림

- 로컬스토리지로 onboarding여부 파악 삭제
get요청 /user/check-onboarding로 onboarding여부 파악

- 로그인상태에서 onboading오면 홈으로 리다이렉트

<br>

## ⭐️ Review point
커밋내역으로 코드리뷰하시는게 편합니다.
<br>

## 📷 Demo
<br>

2024-05-12 14:50 UTC, sikkzz requested changes

2024-05-12 14:50 UTC, sikkzz commented on src/components/Onboarding/CreateAccount/CreateAccount.tsx
<img width="356" alt="스크린샷 2024-05-12 오후 10 20 45" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/f82d6106-d35d-4d10-a2f4-c8c9582ceb04">

나이 선택시 데이터 나이로 format 하셔야 할 거 같네요

2024-05-12 14:50 UTC, sikkzz commented on src/pages/OnboardingPage.tsx
onboarding step 리팩토링
search params, step constants, path 등 상수화 활용해서 리팩토링 진행
search params가 정해놓은 step들이 아닌 다른 값으로 접근시 splash 값으로 초기화
sign up 컴포넌트 -> guide line 컴포넌트로 변경 (명칭 불확실해서 이해하기 어려움)
thunk action으로 onboarding 여부 조회

2024-05-12 14:50 UTC, sikkzz commented on src/components/Chatting/ChattingMessage.tsx
> +	};
thunk로 만들고 dispatch랑 연결하셔야 할 거 같네요

2024-05-12 14:50 UTC, sikkzz commented on src/components/common/Modal/CommonModal/SelectAgeModal.tsx
> +	}, []);
thunk action

2024-05-12 14:50 UTC, sikkzz commented on src/components/common/Modal/CommonModal/SelectGenderModal/SelectGenderModal.tsx
> +			});
thunk action

2024-05-12 14:51 UTC, sikkzz commented on src/pages/OnboardingPage.tsx
해당 내용들은 제가 리팩토링 진행 했습니다. 코드 보시면서 이해 안가는 부분 있으면 질문 주세요

2024-05-13 10:12 UTC, pizzaYami commented on src/components/common/Modal/CommonModal/SelectAgeModal.tsx
> +	}, []);
age-range-list를 가져오는 api인데
thunk로 만들면 redux에 저장했다가 Selector로 다시 불러와서 사용해야 되나요?

2024-05-13 10:12 UTC, pizzaYami commented on src/components/Chatting/ChattingMessage.tsx
> +	};
만들기는 했는데 제대로 만들었는지 의문이라서 회의시간에 확인 부탁드려요

2024-05-13 11:10 UTC, sikkzz commented on src/components/Chatting/ChattingMessage.tsx
> +	};
커밋 넣어주실래요?

2024-05-13 11:14 UTC, sikkzz commented on src/components/common/Modal/CommonModal/SelectAgeModal.tsx
> +	}, []);
네 똑같습니다. 지금 용주님이 api 불러서 state에 set해주는 작업이나 thunk로 불러서 selector로 가져오는 작업 동일한거에요.

다만 차이점이 있다면 selector로 가져오는 state는 글로벌하게 사용 가능하다는 차이점이 있습니다. 나이 리스트 데이터를 왜 ap로 불러서 가져오는지 이해가 안가지만 api들은 모듈화 시켜놓고 모아서 관리하는게 좋기에 thunk에 넣어놓는게 맞을 거 같아요

2024-05-13 11:14 UTC, pizzaYami commented on src/components/Chatting/ChattingMessage.tsx
> +	};
잠시만요

2024-05-13 11:20 UTC, sikkzz commented on src/components/Chatting/ChattingMessage.tsx
> +	};
리뷰 따로 안달고 이따 구두로 말씀드릴게요

2024-05-14 08:12 UTC, sikkzz requested changes

2024-05-14 08:12 UTC, sikkzz commented on src/api/auth/authSlice.ts
> +	isLoading: boolean;
제거 부탁드려요

2024-05-14 08:12 UTC, sikkzz commented on src/api/auth/authSlice.ts
> +	isLoading: true,
얘도 제거

2024-05-14 08:12 UTC, sikkzz commented on src/api/user/userSlice.ts
> +				console.log(action.payload.data.onboard);
console 제거

2024-05-14 08:12 UTC, sikkzz commented on src/api/user/userThunk.ts
> +export const getIsOnboarding = createAsyncThunk("auth/getIsOnboarding", async (_, thunkOptions) => {
key값 user로 변경

2024-05-14 08:12 UTC, sikkzz commented on src/api/user/userThunk.ts
> +	"auth/postOnboarding",
key값 user로 변경

2024-05-14 08:12 UTC, sikkzz commented on src/components/Chatting/ChattingMessage.tsx
> +				}),
내부 객체를 미리 가공하거나 선언해서 쓰는게 좋겠죠? 지금 이 코드는 너무 가독성이 떨어지니까요

2024-05-14 08:12 UTC, sikkzz commented on src/components/Chatting/ChattingMessage.tsx
> +	const isOnboarding = useAppSelector((state) => state.user.isOnboarding);
구조분해할당 형식으로 수정 가능합니다

2024-05-14 08:12 UTC, sikkzz commented on src/components/Chatting/ChattingMessage.tsx
> +	const userData = useAppSelector((state) => state.user);
userSlice에서 객체 state 하나 선언해서 가져오는게 좋지 않을까요?

2024-05-14 08:12 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +			)}
영택님한테도 리뷰 한번 드렸는데 SelectTimeModal modal type은 1개로만 쓰고 내부에서 데이터값을 조절하면서 쓰는게 맞습니다

2024-05-14 21:17 UTC, pizzaYami commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +			)}
이유를 알 수 있을까요?

2024-05-15 04:34 UTC, sikkzz requested changes

2024-05-15 04:34 UTC, sikkzz commented on src/api/user/userSlice.ts
> +);
제가 말씀드린건 이방식이 아니라 initial state에서 객체로 하나 묶어 달라는 얘기였는데 이렇게 하신 이유가 있나요? 동작하는 방식에 대한 장, 단점과 더불어 이후에 각 state들 CRUD api 동작에 관해서 문제가 없는지 궁금합니다

2024-05-15 04:38 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +			)}
당연한거긴한데 어쨋든 다 켜지는 모달은 SelectTimeModal 하나인데 이걸 modal Type을 3개를 쓸 이유가 없습니다.

영택님 파트 포함해서 modal Type은 Select Time Modal type 하나로 통일하고 props로 구분하든 내부 로직에서 구분하든 하는게 맞습니다. 적으면 type 3개 많으면 6개가 하나의 모달때문에 관리해야하는 타입으로 늘어나는건데 낭비가 너무 심하지 않나요?

깔끔한 코드, 가독성 좋은 코드 좋지만 성능과 효율성 또한 고려해야 하니까요. 개인적으로는 가독성이 그렇게 심하게 떨어지는 부분도 아닌 거 같구요

2024-05-16 10:30 UTC, pizzaYami commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +			)}
시간 모달 타입 하나로 통일하면 ChattingPage에서 시간 모달들을 구분하는게 번거로워지고 title관련되서 state를 따로 만들어서 통일성이 없어지며 SELECT_RUNTIME 모달일때만 progress가 진행되야되서 구분이 어려워지는데 쉽게하는 방법이 있나요?

2024-05-16 10:38 UTC, pizzaYami commented on src/api/user/userSlice.ts
> +);
저번 회의에서 우선 객체로 묶지말자고 하신게 생각나서 이렇게 진행했습니다.

장점
필요한 데이터만 모아둬서 재사용성이 높아지고 값이 변경되었을 때만 해당 셀럭터를 다시 계산해서 성능적으로 좋습니다.

단점
불필요한 코드가 증가하게 되죠

셀렉터 자체는 CRUD API 동작에 직접적인 영향을 주지 않는다고 알고있습니다.

2024-05-16 10:45 UTC, sikkzz commented on src/api/user/userSlice.ts
> +);
![스크린샷 2024-05-16 오후 7 42 52](https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/81bb2fc3-dd54-48c6-a858-f3326cb8b300)

제가 말씀드린 객체로 묶자는건 slice initial state에서 묶자는 얘기였습니다. 이렇게 묶어서 사용하면 구조 분해 할당으로 필요한 정보만 불러올 수 있고 action 동작 관련해서 하나하나 넣어줄 필요가 없다는 장점이 있습니다.

셀렉터 api 동작 관련한거는 저렇게 사용했을 때 닉네임, 나이 등의 정보를 따로따로 하나씩 수정하는 방식의 api로 구성되어있는데 그거에 대해 문제 없냐는 질문입니다

2024-05-16 10:48 UTC, sikkzz commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +			)}
흠 코드를 한번 다시 자세히 보고 말씀드릴게요 혹시 말씀하시는 어려움이 영택님 파트에서도 동일하게 존재하는건가요? 아니면 영택님 파트는 신경안써도 되는건가요?

코드 구성할때 거기도 같이 봐야하는건지 싶어서요

2024-05-17 12:37 UTC, pizzaYami commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +			)}
영택님부분은 상관없습니다!

2024-05-17 12:40 UTC, pizzaYami commented on src/api/user/userSlice.ts
> +);
네네 이해했습니다.

셀렉터 api 동작 관련한거는 저렇게 사용했을 때 닉네임, 나이 등의 정보를 따로따로 하나씩 수정하는 방식의 api로 구성되어있는데 그거에 대해 문제 없냐는 질문입니다
-> 이건 문제없습니다

저번 회의내용때문에 다르게 수정해봤는데 준식님이 예시 주시대로 변경해서 올리겠습니다.

2024-05-19 13:07 UTC, sikkzz requested changes

2024-05-19 13:07 UTC, sikkzz commented on src/api/user/userSlice.ts
> +				state.isOnboarding = true;
이걸 넣어줄 필요는 없지 않나요? 온보딩 여부는 api로 조회해서 state에 넣어주면 될 거 같네요

2024-05-19 13:07 UTC, sikkzz commented
지금 api 다 돌아가시나요? 온보딩, 온보딩 여부 체크, 로그인, 로그아웃 4개 기능 돌아가야 정상인거인데 전 안돌아가는거 같아서요

2024-05-20 07:28 UTC, khkh0109 commented
테스트 해봤는데 로그아웃 하고 다시 로그인 하려고 onboarding oauth-sign-up 경로로 진입하면 다시 홈으로 돌아갑니다..! 

그리고 로그아웃 메소드가 delete라 로그아웃 api 호출 시 405 에러가 발생합니다. 문서에는 get으로 되어있어요 (다른 PR은 남길곳이 없어서 우선 여기에 남겨둡니다)

2024-05-20 10:59 UTC, youngTkim submitted a review, later dismissed

2024-05-21 00:44 UTC, pizzaYami commented on src/api/user/userSlice.ts
> +				state.isOnboarding = true;
getIsOnboarding이 제대로 작동을 안해서 확인이 불가능하니 고쳐지면 수정하겠습니다.

2024-05-21 03:33 UTC, pizzaYami commented on src/api/user/userSlice.ts
> +				state.isOnboarding = true;
```
	useEffect(() => {
		dispatch(getIsOnboarding()).then((res) => {
			res.payload.data.onboard && navigate("/");
		});
	}, []);
```
isOnboarding 제거 후에 이런식으로 불러오는게 맞을까요?

2024-05-21 03:34 UTC, pizzaYami commented
VITE_BASE_URL=https://dev.habitbuddy.me/ 으로 변경하니깐 잘 작동하네요

2024-05-21 09:20 UTC, sikkzz commented
> VITE_BASE_URL=https://dev.habitbuddy.me/ 으로 변경하니깐 잘 작동하네요

음 저는 원래 변경된 url이여서 그거랑 관련 없을텐데 다 정상 동작 하시는건가요?

2024-05-21 09:23 UTC, sikkzz commented on src/api/user/userSlice.ts
> +				state.isOnboarding = true;
이해를 조금 잘 못 하신거 같아요 시간 되실때 잠깐 설명드릴게요

2024-05-22 04:31 UTC, pizzaYami commented
> > VITE_BASE_URL=https://dev.habitbuddy.me/ 으로 변경하니깐 잘 작동하네요
> 
> 음 저는 원래 변경된 url이여서 그거랑 관련 없을텐데 다 정상 동작 하시는건가요?

정상작동합니다
로그인과 로그아웃을 동일한 url로 해야지 제대로 작동하는 것 같네요.

2024-05-22 10:40 UTC, pizzaYami commented on src/api/auth/authThunk.ts
> +		return await axiosInstance.get(END_POINTS.LOGOUT);
로그아웃 나중에 post로 변경하신다고 들었습니다. 그때가서 변경할까요?

2024-05-22 12:42 UTC, pizzaYami commented on src/components/Home/HabitGenerate/HabitGenerate.tsx
> +			)}
modalSlice.ts에서
```
type modalType = string | null;

interface initialStateType {
	modal: modalType;
}
```
modalType이 string|null이 아니라 import해서 넣어야 하지 않나요?

2024-05-22 17:59 UTC, sikkzz approved these changes

2024-05-23 08:03 UTC, khkh0109 approved these changes

2024-05-23 11:55 UTC, merged