[TS-332] onboarding
ConnectingStar/ConnectingStar-Front pull request #92
Opened 2024-05-14 00:01 UTC by pizzaYami

[TS-332](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?assignee=712020%3A2697805c-34c2-4de5-99cb-4aab5f6d607a&selectedIssue=TS-332)

## 💡 변경사항 & 이슈
guide line 이미지 변경
chatting FooterBtn 색 변경
CTA 버튼, 모달 헤딩 워딩 변경
사이드버튼 명칭 변경
onboarding 수정가능한 답변 내용 변경
채팅 스무스하게 내려가는 효과 제거
<br>

## ✍️ 관련 설명
- guide line 이미지 변경
![스크린샷 2024-05-14 오전 8 55 40](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/19ac8b9e-b1bd-4136-b3f5-4ef8142e5df1)

- chatting FooterBtn 색 변경
![스크린샷 2024-05-14 오전 8 55 54](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/ae6877d6-ede9-479f-862d-b4920353c797)

- CTA 버튼, 모달 헤딩 워딩 변경
행동 선택 -> 실천 정도 선택
![스크린샷 2024-05-14 오전 8 56 31](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/757ca2cc-0e45-4042-901b-895cb5abd191)

행동을 입력해 주세요 -> 얼마나 실천할지 입력해 주세요
![스크린샷 2024-05-14 오전 8 56 45](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/d11e38ad-546e-4041-b04f-cfc9dc5e56e9)

- 사이드버튼 명칭 변경 
선택 -> 변경
습관 -> 실천정도
![스크린샷 2024-05-14 오전 8 57 41](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/7d51fba7-ea1a-4046-ad43-196562b2cb69)

- onboarding 수정가능한 답변 내용 변경
습관내용 - 실천정도 추가
<br>

## ⭐️ Review point
![스크린샷 2024-05-14 오전 9 00 07](https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/abc8b980-1c00-4762-8485-3d4382f8339c)

<br>

## 📷 Demo
<br>

2024-05-14 08:14 UTC, sikkzz requested changes

2024-05-14 08:18 UTC, sikkzz requested changes

2024-05-14 08:18 UTC, sikkzz commented on src/components/common/FooterBtn/FooterBtn.Style.ts
> +			background-color: ${buttonColor};
button color props default를 저장해놓는거보다 button colors가 없을때 main_blue로 스타일링 해놓는게 낫지 않을까요?

2024-05-15 04:41 UTC, sikkzz approved these changes

2024-05-18 12:57 UTC, khkh0109 approved these changes

2024-05-18 14:15 UTC, youngTkim approved these changes

2024-05-22 04:29 UTC, merged