[TS-333] 별자리 카드 상세 페이지 API 연결, 일부 리팩토링
ConnectingStar/ConnectingStar-Front pull request #96
Opened 2024-06-01 06:39 UTC by khkh0109

[TS-333](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?assignee=616ccf7525f31300702d29cb&selectedIssue=TS-333)

## 💡 변경사항 & 이슈
- 별자리 상세 페이지 API 연결
- 일부 화면 수정사항 반영
<br>

## ✍️ 관련 설명
### 별자리 상세 페이지 API 연결
- /star-card/:id 에서 확인 가능
- 연결한 API
  - [프로필 별자리 수정](https://documenter.getpostman.com/view/32872720/2sA35G53Dg#37499a6a-95f4-4a9c-b0da-c749c1bf2ab0), [별자리 선택(등록)](https://documenter.getpostman.com/view/32872720/2sA35G53Dg#842edbfc-2045-47c9-8a9e-85e418cdf949), [별자리 카드 상세 조회](https://documenter.getpostman.com/view/32872720/2sA35G53Dg#fbc08495-3aa3-4d60-962d-3db630c9d7da)

### 화면 수정사항 반영
- 카테고리 라벨
  - 기존: 여러개 -> 변경: 한개만
  - 카테고리 라벨이 하나 뿐이라 관련 컴포넌트 삭제, 별자리 상세 페이지 내부로 이동함
- 캐릭터 이름
  - 기존: 캐릭터 이름만 -> 변경: 해금 전 `캐릭터 이름 + 자리`, 해금 후 `캐릭터 이름`

### 로딩스피너 추가
- 로딩스피너 파일은 별자리 상세에만 있어서 우선 components/StarPage에 두었습니다. 
다른 곳에서도 사용한다면 위치를 변경하는게 좋을 것 같아요

### 테스트 방법
- StarMainPage에 있는 API 요청 코드는 테스트를 위한 코드입니다 -> 추후 다른 브랜치에서 삭제 예정
- 테스트 방법
  - 1) 아무 별자리 상세 페이지(/star-card/:id)에 가서 별자리 선택
  - 2) 별자리 메인 페이지(/star)로 가서 버튼을 눌러 별을 다 채우면 해금됨
    - 콘솔에서 남은 별, 해금 유무 확인 가능
<br>

## ⭐️ Review point
- path 상수로 관리하는것 같은데, 지금부터 변경하는건가요? 
- 엔드포인트 관련
  - SELECT_CONSTELLATION은 메소드만 다르고 엔드포인트 동일 -> 이름 어떤지 봐주시면 감사하겠습니다. 
  - 참고: [별자리 선택 등록](https://documenter.getpostman.com/view/32872720/2sA35G53Dg#842edbfc-2045-47c9-8a9e-85e418cdf949), [프로필 별자리 수정](https://documenter.getpostman.com/view/32872720/2sA35G53Dg#37499a6a-95f4-4a9c-b0da-c749c1bf2ab0)
- 이 외에 리덕스 툴킷 관련 코드 작성 방법 맞는지, 카드 상태에 맞게 모달-버튼-기능이 일치하는지
 
확인 부탁드립니다 

<br>

## 📷 Demo
새로 추가한 로딩스피너 화면 
<img width="300" alt="스크린샷 2024-06-01 오후 3 37 43" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/eac60687-0b02-4fcc-820c-6499cab3000b">
<br>

2024-06-03 10:37 UTC, sikkzz requested changes

2024-06-03 10:37 UTC, sikkzz commented on src/api/star/starSlice.ts
> +	name: "starCardDetail",
"star"로 변경 부탁드려요! slice 키값들은 앞에 단어만 따서 간단하게 가는게 좋을 거 같아서요

2024-06-03 10:37 UTC, sikkzz commented on src/api/star/starSlice.ts
> +		},
isProfile은 서버에 저장되지 않아도 되는 데이터인가요? 유저의 정보를 받아왔을때 isProfile 여부도 업데이트가 되어야 한다면 프론트단 state에서만 업데이트할게 아니라 db에 값을 변경해줘야 하는거 같아 보여서요

2024-06-03 10:37 UTC, sikkzz commented on src/api/star/starSlice.ts
> +		},
만약 제가 얘기한 방향이 맞다면 isProfile 여부를 업데이트하는 api가 하나 필요하다고 생각되네요

2024-06-03 10:37 UTC, sikkzz commented on src/api/star/starSlice.ts
> +	},
state명을 좀 더 직관적인 data 느낌의 네이밍으로 변경하는게 좋을 거 같아요

2024-06-03 10:37 UTC, sikkzz commented on src/pages/StarCardDetailPage.tsx
> +			case "COMPLETE":
<img width="481" alt="스크린샷 2024-06-03 오후 7 35 35" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/c07383a4-8f63-4127-8756-7facf2173249">

이 상태들이 꽤나 여러곳에서 사용되는 거 같은데 상수화해서 사용하는게 낫지 않을까요?

2024-06-03 10:37 UTC, sikkzz commented on src/pages/StarMainPage/StarMainPage.tsx
여기 완성 코드 아닌거 같아서 따로 리뷰 안하고 다음 브랜치에서 리뷰할게요

2024-06-03 10:44 UTC, sikkzz commented
1. PATH는 상수화해서 관리하는게 좋기에 저도 리팩토링하면서 계속 바꿔나갈 예정입니다. 변경하는게 좋을 거 같아요
2. 엔드포인트는 Select보다 USER_CONSTELLATION이 낫지 않을까요? 사실 두 api가 같은 엔드포인트 쓰는거 자체가 애매해 보이는데 백엔드 설계다 보니 프론트에서 직관적 이해는 어려울 거 같고 그냥 select보다 user가 나을 거 같아서 말씀드려요
3. 로딩스피너는 어쨋든 common으로 빼주시는게 나을 거 같습니다.
4. 별자리 메인 페이지에서 해금 api가 제대로 작동안하는거 같은데 어쨋든 미완성이라서 다음 브랜치에서 리뷰하려고 합니다. 저는 현재 콘솔에 이렇게 뜨네요.

<img width="589" alt="스크린샷 2024-06-03 오후 7 43 35" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/774b1751-4c4e-42c6-bb2b-75763105029c">

2024-06-03 11:58 UTC, khkh0109 commented on src/api/star/starSlice.ts
> +		},
editProfileImage 요청을 보내면 isProfile이 바뀝니다! (userSlice 부분에 있어요)

프로필 변경 요청 성공하면 isProfile이 true로 바뀌는데 버튼 UI는 바로 바뀌지 않아서 isProfile state만 먼저 업데이트 하도록 reducer를 추가했습니다
혹시 다른 괜찮은 방법 있으시면 말씀 부탁드려요!

2024-06-03 11:59 UTC, khkh0109 commented on src/api/star/starSlice.ts
> +	name: "starCardDetail",
넵 star로 변경하겠습니다!

2024-06-03 11:59 UTC, khkh0109 commented on src/pages/StarCardDetailPage.tsx
> +			case "COMPLETE":
그러네요 실수할수도 있으니 상수화 하겠습니다!

2024-06-03 11:59 UTC, khkh0109 commented on src/pages/StarMainPage/StarMainPage.tsx
넵 TS-346에서 작업중이니 그때 부탁드려요!

2024-06-03 12:04 UTC, khkh0109 commented on src/api/star/starSlice.ts
> +	},
지금은 서버에서 전달하는 키 값 이름을 그대로 사용하고 있는데 그거랑 별개로 
프론트쪽에서 알아보기 편한 직관적인 이름으로 변경하는게 좋은것 같다는 말씀 맞을까요?

2024-06-04 04:11 UTC, khkh0109 commented
### 반영사항 (진행중)
1. Path 상수화 (/star 상수 추가, 나머지는 다른 브랜치에서 변경 예정)
2. 엔드포인트 변경(SELECT_CONSTELLATION -> USER_CONSTELLATION)
3. 로딩스피너 common 폴더로 이동
4. starSlice 이름 변경 (starCardDetail -> star)
5. 별자리 카드 상세 페이지의 상태 상수화 (STAR_CARD_DETAIL_STATUS)

2024-06-07 05:02 UTC, pizzaYami commented
Uploading 화면 기록 2024-06-07 오후 2.00.44.mov…

현재 선택중인 별자리가 /star에서 보여야되는걸로 아는데 보이지 않네요.
아직 구현이 안된건지 궁금합니다!

2024-06-07 05:07 UTC, pizzaYami commented
<img width="360" alt="스크린샷 2024-06-07 오후 2 06 39" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/116322645/5a0762c1-03e0-4b2b-ae5d-0973c2899915">

캐릭터 뒤에 배경은 없는게 맞을까요?

2024-06-07 06:20 UTC, khkh0109 commented
> 2024-06-07.2.00.44.mov 
> 현재 선택중인 별자리가 /star에서 보여야되는걸로 아는데 보이지 않네요. 아직 구현이 안된건지 궁금합니다!

이 브랜치에서는 구현이 안됐습니다! 현재 브랜치는 별자리 상세 페이지만 구현해두었습니다
346 브랜치에서 별자리 메인 페이지 기능을 올릴 예정입니다..!

2024-06-07 07:51 UTC, pizzaYami approved these changes

2024-06-07 09:08 UTC, sikkzz approved these changes

2024-06-07 09:16 UTC, merged