[TS-343] 별자리 카드 API 추가
ConnectingStar/ConnectingStar-Front pull request #97
Opened 2024-06-03 09:22 UTC by khkh0109

[TS-343](https://m2jun.atlassian.net/jira/software/projects/TS/boards/109?assignee=616ccf7525f31300702d29cb&selectedIssue=TS-343)

## 💡 변경사항 & 이슈
별자리 카드 API 연결
<br>

## ✍️ 관련 설명
- /star-card 에서 확인 가능
- TS-333 브랜치와 이어짐
- 탭, 토글 파라미터로 관리할 수 있게 변경 (피그마 화면설계에는 안적혀 있는데 새로고침 시 사용자가 선택한 탭, 토글로 유지하라는 요청 있었음)
- 이미지 수정 요청 드렸는데 아직 반영 안됨 -> 피그마와 다르게 보입니다.. 양해부탁드려요 

### 별자리 카드 상태 
- PROGRESS: 진행중인 별자리
- COMPLETE: 해금된 별자리
- NONE: 미보유

-> 별자리 카드 상태는 이렇게 세 가지가 온다고 합니다 
-> 별자리 카드 상세 상태와 병합하려다 헷갈릴것 같아서 분리했습니다. 혹시 괜찮은 방법 있다면 말씀주세요 

<br>

## ⭐️ Review point
- 디자인, 요구사항과 다른 부분 있는지
- 좀 더 괜찮은 방법/이름 있는지

확인 부탁드립니다 
<br>

## 📷 Demo
<img width="360" alt="스크린샷 2024-06-03 오후 6 20 41" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/77181642/383959c2-1199-464b-b071-fe2d1722ff39">

<br>

2024-06-09 06:30 UTC, sikkzz requested changes

2024-06-09 06:30 UTC, sikkzz commented on src/components/StarPage/StarCard/CategoryTab.tsx
> +					onClick={() => onTabClick(item.param)}
className말고 css props로 조건부 해결하는게 좋을 거 같아요 큰 차이점이 있는건 아니지만 어차피 스타일링 코드가 존재하니까요

2024-06-09 06:30 UTC, sikkzz commented on src/constants/starPageConstants.ts
> +	{ id: 5, title: "휴식ㅣ취미", param: "rest-and-hobby" },
id는 지우고 key값은 title이나 param으로 써도 상관 없을 거 같은데 id를 써야하는 특별한 이유가 있을까요?

2024-06-09 06:30 UTC, sikkzz commented on src/pages/StarCardPage.tsx
> +			}),
여기 api가 id값이 아니라 tab 파라미터 값으로 조회하는게 낫지 않을까요? 

현재 api 엔드포인트를 보면 constellation/list?constellationTypeId=0&isRegistered=false 가 전체 조회 같은데
constellation/list?type=ALL&isRegistered=false 이런식으로요

<img width="251" alt="스크린샷 2024-06-09 오후 3 21 54" src="https://github.com/ConnectingStar/ConnectingStar-Front/assets/100590110/8c382640-a675-4443-b6a2-b1af214efe49">

여기서 사용하는 파라미터들을 키값으로 사용하는게 더 좋지 않나 싶은건데 백엔드측에서 설계 의도 전달받으신게 따로 있을까요?

제가 얘기한 방식으로 하면 코드 간소화도 가능한 부분들이 더 보일거 같기도 하구요

2024-06-09 06:30 UTC, sikkzz commented on src/pages/StarCardPage.tsx
> +					}}
함수 하나만 있어서 중괄호 제거해도 될 거 같아요

2024-06-09 06:30 UTC, sikkzz commented on src/pages/StarCardPage.tsx
> +							{ replace: true },
여기뿐만 아니라 전체적으로 setSearchParams에 replace를 넣어서 사용하시는 특별한 이유가 있으신가요?

2024-06-09 06:30 UTC, sikkzz commented on src/pages/StarCardPage.tsx
> +	const isToggle = searchParams.get(TOGGLE_KEY) === "true";
토글 여부를 searchParams로 관리하시는 이유가 궁금합니다

2024-06-09 06:30 UTC, sikkzz commented on src/components/StarPage/StarCard/Toggle.tsx
제가 만들어놓은 common 컴포넌트에 Toggle을 활용해보시는건 어떠신가요?

2024-06-10 06:14 UTC, khkh0109 commented on src/pages/StarCardPage.tsx
> +			}),
설계 의도를 따로 전달받은게 없는데, 아마 카테고리 탭 목록 조회 API와 연동되는 부분이라 id로 조회할 수 있게 만드신것 같아요 
주말에 카테고리 탭 목록 API 삭제 요청 드렸고 반영되었으니 
id 대신 파라미터 값으로 조회 가능한지 여쭤보겠습니다

2024-06-10 06:14 UTC, khkh0109 commented on src/constants/starPageConstants.ts
> +	{ id: 5, title: "휴식ㅣ취미", param: "rest-and-hobby" },
아래쪽에 비슷한 답을 달았는데 카테고리 별 목록을 id값으로 조회해서 id를 추가했습니다
만약 상의 후 id로 api 조회하지 않는다면 title이나 param으로 사용하는게 좋을것 같네요

2024-06-10 06:20 UTC, khkh0109 commented on src/pages/StarCardPage.tsx
> +							{ replace: true },
이전에 방문한 페이지로 바로 이동하게 하려고 사용했습니다

1) 탭, 토글 상태를 searchParam으로 관리하고 있는데, 뒤로가기 할때 이전에 선택했던 탭/토글로 이동하더라구요
그래서 뒤로가기 버튼 클릭 시 이전에 방문한 페이지로 바로 이동하게 하려고 replace를 사용했습니다

2) `별자리(/star) -> 별자리 카드(/star-card)` 이 경로로 이동 후 뒤로가기를 하면 이전에 방문했던 별자리 페이지(/star)로 이동하지 않는 문제가 있었습니다.. 별자리 카드 페이지를 못벗어나더라구요 

이 두 가지 이유때문에 replace를 넣어주었습니다

2024-06-10 06:21 UTC, khkh0109 commented on src/pages/StarCardPage.tsx
> +	const isToggle = searchParams.get(TOGGLE_KEY) === "true";
토글 on/off 여부를 고정시키기 위해서 사용했습니다
(피그마에는 안적혀 있는데 사용자가 선택한 토글이 계속 유지되어야 한다고 합니다)

별자리 카드 페이지 새로고침 or 별자리 상세 페이지에 방문했다가 뒤로가기로 별자리 카드 페이지로 오면 토글이 유지가 안돼서 searchParams로 관리하게 되었습니다,,

2024-06-10 06:22 UTC, khkh0109 commented on src/components/StarPage/StarCard/Toggle.tsx
넵 공통 Toggle 컴포넌트로 변경했는데 이렇게 사용하는게 맞는지 확인 부탁드려요

2024-06-10 06:23 UTC, khkh0109 commented on src/components/StarPage/StarCard/CategoryTab.tsx
> +					onClick={() => onTabClick(item.param)}
이것도 css props로 변경했습니다 
스타일이 한곳에 모여있으니 이 방식이 더 좋네요

2024-06-10 09:19 UTC, sikkzz requested changes

2024-06-10 09:19 UTC, sikkzz commented on src/pages/StarCardPage.tsx
> +				<ToggleButton isToggle={isToggle} handleTogglePrev={handleToggleClick} />
Toggle Button 컴포넌트를 하나 더 만들면서 props 전달이 한번 늘어나는데 그냥 Toggle Button 컴포넌트 코드를 여기로 빼고 Toggle 공통 컴포넌트만 import해서 쓰는게 더 좋지 않을까요?

Toggle 컴포넌트 사용법은 제대로 사용하셨습니다~

2024-06-10 09:25 UTC, sikkzz requested changes

2024-06-10 09:25 UTC, sikkzz commented on src/pages/StarCardPage.tsx
> +	}, [searchParams]);
코드 변동이 없다는 전제 하에 두 개는 같은 조건의 deps로 useEffect가 작동되기 때문에 하나로 합칠 수 있습니다.

2024-06-10 10:57 UTC, khkh0109 commented on src/pages/StarCardPage.tsx
> +				<ToggleButton isToggle={isToggle} handleTogglePrev={handleToggleClick} />
넵 ToggleButtln이나 Toggle이나 비슷해서 Toggle 바로 import하는 방식으로 변경했습니다 

그리고 useToggleTrigger 훅은 삭제했는데, useState라서 새로고침할때 풀리더라구요 
그래서 이 부분만 url에 고정하는 방식으로 변경했습니다
혹시 더 괜찮은 방식 있으면 말씀해주세요!

2024-06-10 10:59 UTC, khkh0109 commented on src/pages/StarCardPage.tsx
> +	}, [searchParams]);
이 부분도 하나로 합쳤습니다!

2024-06-17 13:10 UTC, pizzaYami approved these changes

2024-06-20 11:01 UTC, sikkzz approved these changes

2024-06-20 11:09 UTC, merged